// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminAuditLogFieldNames          = builder.RawFieldNames(&AdminAuditLog{})
	adminAuditLogRows                = strings.Join(adminAuditLogFieldNames, ",")
	adminAuditLogRowsExpectAutoSet   = strings.Join(stringx.Remove(adminAuditLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminAuditLogRowsWithPlaceHolder = strings.Join(stringx.Remove(adminAuditLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminAuditLogModel interface {
		Insert(ctx context.Context, data *AdminAuditLog) (sql.Result, error)
		FindOne(ctx context.Context, logId uint64) (*AdminAuditLog, error)
		Update(ctx context.Context, data *AdminAuditLog) error
		Delete(ctx context.Context, logId uint64) error
	}

	defaultAdminAuditLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminAuditLog struct {
		LogId       uint64    `db:"log_id"`
		UserId      uint64    `db:"user_id"`
		Uuid        string    `db:"uuid"`
		AuditUserId uint64    `db:"audit_user_id"`
		AuditUuid   string    `db:"audit_uuid"`
		Ip          string    `db:"Ip"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newAdminAuditLogModel(conn sqlx.SqlConn) *defaultAdminAuditLogModel {
	return &defaultAdminAuditLogModel{
		conn:  conn,
		table: "`admin_audit_log`",
	}
}

func (m *defaultAdminAuditLogModel) Delete(ctx context.Context, logId uint64) error {
	query := fmt.Sprintf("delete from %s where `log_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, logId)
	return err
}

func (m *defaultAdminAuditLogModel) FindOne(ctx context.Context, logId uint64) (*AdminAuditLog, error) {
	query := fmt.Sprintf("select %s from %s where `log_id` = ? limit 1", adminAuditLogRows, m.table)
	var resp AdminAuditLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, logId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminAuditLogModel) Insert(ctx context.Context, data *AdminAuditLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, adminAuditLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.AuditUserId, data.AuditUuid, data.Ip)
	return ret, err
}

func (m *defaultAdminAuditLogModel) Update(ctx context.Context, data *AdminAuditLog) error {
	query := fmt.Sprintf("update %s set %s where `log_id` = ?", m.table, adminAuditLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.AuditUserId, data.AuditUuid, data.Ip, data.LogId)
	return err
}

func (m *defaultAdminAuditLogModel) tableName() string {
	return m.table
}
