// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiCallStatsFieldNames          = builder.RawFieldNames(&AiCallStats{})
	aiCallStatsRows                = strings.Join(aiCallStatsFieldNames, ",")
	aiCallStatsRowsExpectAutoSet   = strings.Join(stringx.Remove(aiCallStatsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiCallStatsRowsWithPlaceHolder = strings.Join(stringx.Remove(aiCallStatsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	aiCallStatsModel interface {
		Insert(ctx context.Context, data *AiCallStats) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AiCallStats, error)
		Update(ctx context.Context, data *AiCallStats) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAiCallStatsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiCallStats struct {
		Id                uint64    `db:"id"`                  // 主键ID
		ClientId          string    `db:"client_id"`           // 平台id
		UserId            string    `db:"user_id"`             // 用户唯一标识（如用户ID/手机号/OpenID）
		CallTime          time.Time `db:"call_time"`           // AI调用时间
		CostMs            uint64    `db:"cost_ms"`             // 调用耗时（毫秒）
		QuestionCharCount uint64    `db:"question_char_count"` // 问题字数（中文/英文统一按字符数统计）
		OutputCharCount   uint64    `db:"output_char_count"`   // 输出字数（中文/英文统一按字符数统计）
		ModelName         string    `db:"model_name"`          // 调用的AI模型名（如qwen3-8b、gpt-3.5-turbo）
		CallStatus        int64     `db:"call_status"`         // 调用状态：1-成功，0-失败
	}
)

func newAiCallStatsModel(conn sqlx.SqlConn) *defaultAiCallStatsModel {
	return &defaultAiCallStatsModel{
		conn:  conn,
		table: "`ai_call_stats`",
	}
}

func (m *defaultAiCallStatsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiCallStatsModel) FindOne(ctx context.Context, id uint64) (*AiCallStats, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiCallStatsRows, m.table)
	var resp AiCallStats
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiCallStatsModel) Insert(ctx context.Context, data *AiCallStats) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, aiCallStatsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.CallTime, data.CostMs, data.QuestionCharCount, data.OutputCharCount, data.ModelName, data.CallStatus)
	return ret, err
}

func (m *defaultAiCallStatsModel) Update(ctx context.Context, data *AiCallStats) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiCallStatsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.CallTime, data.CostMs, data.QuestionCharCount, data.OutputCharCount, data.ModelName, data.CallStatus, data.Id)
	return err
}

func (m *defaultAiCallStatsModel) tableName() string {
	return m.table
}
