// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiSessionsFieldNames          = builder.RawFieldNames(&AiSessions{})
	aiSessionsRows                = strings.Join(aiSessionsFieldNames, ",")
	aiSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(aiSessionsFieldNames, "`session_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(aiSessionsFieldNames, "`session_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	aiSessionsModel interface {
		Insert(ctx context.Context, data *AiSessions) (sql.Result, error)
		FindOne(ctx context.Context, sessionId uint64) (*AiSessions, error)
		FindOneByClientIdSessionUuid(ctx context.Context, clientId string, sessionUuid string) (*AiSessions, error)
		Update(ctx context.Context, data *AiSessions) error
		Delete(ctx context.Context, sessionId uint64) error
	}

	defaultAiSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiSessions struct {
		SessionId        uint64         `db:"session_id"`   // 会话ID
		ClientId         string         `db:"client_id"`    // 平台id
		SessionUuid      string         `db:"session_uuid"` // 会话唯一标识符
		CategoryId       int64          `db:"category_id"`  // bunesstype
		EmpCode          string         `db:"emp_code"`
		Keys             string         `db:"keys"`               // keys
		DocumentTypeCode string         `db:"document_type_code"` // 文档类型
		UserId           int64          `db:"user_id"`            // 用户ID
		Tags             string         `db:"tags"`
		SessionTitle     string         `db:"session_title"`     // 会话标题
		SessionStatus    string         `db:"session_status"`    // 会话状态
		Model            string         `db:"model"`             // 使用的AI模型
		SystemPrompt     sql.NullString `db:"system_prompt"`     // 系统提示词
		LastMessageTime  sql.NullTime   `db:"last_message_time"` // 最后消息时间
		MessageCount     uint64         `db:"message_count"`     // 消息总数
		CreatedAt        time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time      `db:"updated_at"`        // 更新时间
	}
)

func newAiSessionsModel(conn sqlx.SqlConn) *defaultAiSessionsModel {
	return &defaultAiSessionsModel{
		conn:  conn,
		table: "`ai_sessions`",
	}
}

func (m *defaultAiSessionsModel) Delete(ctx context.Context, sessionId uint64) error {
	query := fmt.Sprintf("delete from %s where `session_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, sessionId)
	return err
}

func (m *defaultAiSessionsModel) FindOne(ctx context.Context, sessionId uint64) (*AiSessions, error) {
	query := fmt.Sprintf("select %s from %s where `session_id` = ? limit 1", aiSessionsRows, m.table)
	var resp AiSessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, sessionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiSessionsModel) FindOneByClientIdSessionUuid(ctx context.Context, clientId string, sessionUuid string) (*AiSessions, error) {
	var resp AiSessions
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `session_uuid` = ? limit 1", aiSessionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, sessionUuid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiSessionsModel) Insert(ctx context.Context, data *AiSessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, aiSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.SessionUuid, data.CategoryId, data.EmpCode, data.Keys, data.DocumentTypeCode, data.UserId, data.Tags, data.SessionTitle, data.SessionStatus, data.Model, data.SystemPrompt, data.LastMessageTime, data.MessageCount)
	return ret, err
}

func (m *defaultAiSessionsModel) Update(ctx context.Context, newData *AiSessions) error {
	query := fmt.Sprintf("update %s set %s where `session_id` = ?", m.table, aiSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.SessionUuid, newData.CategoryId, newData.EmpCode, newData.Keys, newData.DocumentTypeCode, newData.UserId, newData.Tags, newData.SessionTitle, newData.SessionStatus, newData.Model, newData.SystemPrompt, newData.LastMessageTime, newData.MessageCount, newData.SessionId)
	return err
}

func (m *defaultAiSessionsModel) tableName() string {
	return m.table
}
