// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiUsageStatsFieldNames          = builder.RawFieldNames(&AiUsageStats{})
	aiUsageStatsRows                = strings.Join(aiUsageStatsFieldNames, ",")
	aiUsageStatsRowsExpectAutoSet   = strings.Join(stringx.Remove(aiUsageStatsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiUsageStatsRowsWithPlaceHolder = strings.Join(stringx.Remove(aiUsageStatsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	aiUsageStatsModel interface {
		Insert(ctx context.Context, data *AiUsageStats) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AiUsageStats, error)
		FindOneByClientIdUserIdSessionIdUsageDate(ctx context.Context, clientId string, userId int64, sessionId uint64, usageDate time.Time) (*AiUsageStats, error)
		Update(ctx context.Context, data *AiUsageStats) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAiUsageStatsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiUsageStats struct {
		Id           uint64    `db:"id"`
		ClientId     string    `db:"client_id"`     // 平台id
		UserId       int64     `db:"user_id"`       // 用户ID
		SessionId    uint64    `db:"session_id"`    // 会话ID
		Model        string    `db:"model"`         // AI模型
		UsageDate    time.Time `db:"usage_date"`    // 使用日期
		SessionCount uint64    `db:"session_count"` // 会话数量
		MessageCount uint64    `db:"message_count"` // 消息数量
		TotalTokens  uint64    `db:"total_tokens"`  // 总token数
		TotalCost    float64   `db:"total_cost"`    // 总费用
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
	}
)

func newAiUsageStatsModel(conn sqlx.SqlConn) *defaultAiUsageStatsModel {
	return &defaultAiUsageStatsModel{
		conn:  conn,
		table: "`ai_usage_stats`",
	}
}

func (m *defaultAiUsageStatsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiUsageStatsModel) FindOne(ctx context.Context, id uint64) (*AiUsageStats, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiUsageStatsRows, m.table)
	var resp AiUsageStats
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiUsageStatsModel) FindOneByClientIdUserIdSessionIdUsageDate(ctx context.Context, clientId string, userId int64, sessionId uint64, usageDate time.Time) (*AiUsageStats, error) {
	var resp AiUsageStats
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `user_id` = ? and `session_id` = ? and `usage_date` = ? limit 1", aiUsageStatsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, userId, sessionId, usageDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiUsageStatsModel) Insert(ctx context.Context, data *AiUsageStats) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, aiUsageStatsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.SessionId, data.Model, data.UsageDate, data.SessionCount, data.MessageCount, data.TotalTokens, data.TotalCost)
	return ret, err
}

func (m *defaultAiUsageStatsModel) Update(ctx context.Context, newData *AiUsageStats) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiUsageStatsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.UserId, newData.SessionId, newData.Model, newData.UsageDate, newData.SessionCount, newData.MessageCount, newData.TotalTokens, newData.TotalCost, newData.Id)
	return err
}

func (m *defaultAiUsageStatsModel) tableName() string {
	return m.table
}
