// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	asyncTaskFieldNames          = builder.RawFieldNames(&AsyncTask{})
	asyncTaskRows                = strings.Join(asyncTaskFieldNames, ",")
	asyncTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(asyncTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	asyncTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(asyncTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	asyncTaskModel interface {
		Insert(ctx context.Context, data *AsyncTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AsyncTask, error)
		Update(ctx context.Context, data *AsyncTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAsyncTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AsyncTask struct {
		Id            int64     `db:"id"`             // 主键ID
		ClientId      string    `db:"client_id"`      // 平台id
		TaskType      string    `db:"task_type"`      // 任务类型
		TaskDesc      string    `db:"task_desc"`      // 任务描述
		SourceId      int64     `db:"source_id"`      // 关联表ID
		SourceKey     string    `db:"source_key"`     // 任务类型
		ExecuteResult string    `db:"execute_result"` // 执行结果
		Status        string    `db:"status"`         // init/running/canceled/success/failed
		CreatedAt     time.Time `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`     // 更新时间
	}
)

func newAsyncTaskModel(conn sqlx.SqlConn) *defaultAsyncTaskModel {
	return &defaultAsyncTaskModel{
		conn:  conn,
		table: "`async_task`",
	}
}

func (m *defaultAsyncTaskModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAsyncTaskModel) FindOne(ctx context.Context, id int64) (*AsyncTask, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asyncTaskRows, m.table)
	var resp AsyncTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAsyncTaskModel) Insert(ctx context.Context, data *AsyncTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, asyncTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.TaskType, data.TaskDesc, data.SourceId, data.SourceKey, data.ExecuteResult, data.Status)
	return ret, err
}

func (m *defaultAsyncTaskModel) Update(ctx context.Context, data *AsyncTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, asyncTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.TaskType, data.TaskDesc, data.SourceId, data.SourceKey, data.ExecuteResult, data.Status, data.Id)
	return err
}

func (m *defaultAsyncTaskModel) tableName() string {
	return m.table
}
