// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	blogTagsFieldNames          = builder.RawFieldNames(&BlogTags{})
	blogTagsRows                = strings.Join(blogTagsFieldNames, ",")
	blogTagsRowsExpectAutoSet   = strings.Join(stringx.Remove(blogTagsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	blogTagsRowsWithPlaceHolder = strings.Join(stringx.Remove(blogTagsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	blogTagsModel interface {
		Insert(ctx context.Context, data *BlogTags) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*BlogTags, error)
		Update(ctx context.Context, data *BlogTags) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultBlogTagsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BlogTags struct {
		Id        uint64    `db:"id"`
		Tag       string    `db:"tag"`
		CreatedAt time.Time `db:"created_at"` // 创建时间
	}
)

func newBlogTagsModel(conn sqlx.SqlConn) *defaultBlogTagsModel {
	return &defaultBlogTagsModel{
		conn:  conn,
		table: "`blog_tags`",
	}
}

func (m *defaultBlogTagsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBlogTagsModel) FindOne(ctx context.Context, id uint64) (*BlogTags, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", blogTagsRows, m.table)
	var resp BlogTags
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlogTagsModel) Insert(ctx context.Context, data *BlogTags) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, blogTagsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Tag)
	return ret, err
}

func (m *defaultBlogTagsModel) Update(ctx context.Context, data *BlogTags) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, blogTagsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Tag, data.Id)
	return err
}

func (m *defaultBlogTagsModel) tableName() string {
	return m.table
}
