// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	blogCategoryFieldNames          = builder.RawFieldNames(&BlogCategory{})
	blogCategoryRows                = strings.Join(blogCategoryFieldNames, ",")
	blogCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(blogCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	blogCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(blogCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	blogCategoryModel interface {
		Insert(ctx context.Context, data *BlogCategory) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*BlogCategory, error)
		Update(ctx context.Context, data *BlogCategory) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultBlogCategoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BlogCategory struct {
		Id        uint64    `db:"id"`
		ParentId  uint64    `db:"parent_id"`
		Category  string    `db:"category"`
		CreatedAt time.Time `db:"created_at"` // 创建时间
	}
)

func newBlogCategoryModel(conn sqlx.SqlConn) *defaultBlogCategoryModel {
	return &defaultBlogCategoryModel{
		conn:  conn,
		table: "`blog_category`",
	}
}

func (m *defaultBlogCategoryModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBlogCategoryModel) FindOne(ctx context.Context, id uint64) (*BlogCategory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", blogCategoryRows, m.table)
	var resp BlogCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlogCategoryModel) Insert(ctx context.Context, data *BlogCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, blogCategoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentId, data.Category)
	return ret, err
}

func (m *defaultBlogCategoryModel) Update(ctx context.Context, data *BlogCategory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, blogCategoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ParentId, data.Category, data.Id)
	return err
}

func (m *defaultBlogCategoryModel) tableName() string {
	return m.table
}
