// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	blogFieldNames          = builder.RawFieldNames(&Blog{})
	blogRows                = strings.Join(blogFieldNames, ",")
	blogRowsExpectAutoSet   = strings.Join(stringx.Remove(blogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	blogRowsWithPlaceHolder = strings.Join(stringx.Remove(blogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	blogModel interface {
		Insert(ctx context.Context, data *Blog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Blog, error)
		Update(ctx context.Context, data *Blog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBlogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Blog struct {
		Id            int64     `db:"id"`
		Title         string    `db:"title"`
		SortOrder     uint64    `db:"sort_order"` // 喜欢
		Tags          string    `db:"tags"`
		Categories    string    `db:"categories"`
		Banner        string    `db:"banner"`
		TwitterAuthor string    `db:"twitter_author"`
		UserId        int64     `db:"user_id"`
		Authors       string    `db:"authors"`
		Summary       string    `db:"summary"`
		Content       string    `db:"content"`
		IsApproved    int64     `db:"is_approved"`
		IsPublished   int64     `db:"is_published"`
		CreatedAt     time.Time `db:"created_at"` // 创建时间
		UpdatedAt     time.Time `db:"updated_at"` // 更新时间
		Uuid          string    `db:"uuid"`       // 用户uuid
	}
)

func newBlogModel(conn sqlx.SqlConn) *defaultBlogModel {
	return &defaultBlogModel{
		conn:  conn,
		table: "`blog`",
	}
}

func (m *defaultBlogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBlogModel) FindOne(ctx context.Context, id int64) (*Blog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", blogRows, m.table)
	var resp Blog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlogModel) Insert(ctx context.Context, data *Blog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, blogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.SortOrder, data.Tags, data.Categories, data.Banner, data.TwitterAuthor, data.UserId, data.Authors, data.Summary, data.Content, data.IsApproved, data.IsPublished, data.Uuid)
	return ret, err
}

func (m *defaultBlogModel) Update(ctx context.Context, data *Blog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, blogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.SortOrder, data.Tags, data.Categories, data.Banner, data.TwitterAuthor, data.UserId, data.Authors, data.Summary, data.Content, data.IsApproved, data.IsPublished, data.Uuid, data.Id)
	return err
}

func (m *defaultBlogModel) tableName() string {
	return m.table
}
