// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clientFieldNames          = builder.RawFieldNames(&Client{})
	clientRows                = strings.Join(clientFieldNames, ",")
	clientRowsExpectAutoSet   = strings.Join(stringx.Remove(clientFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	clientRowsWithPlaceHolder = strings.Join(stringx.Remove(clientFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	clientModel interface {
		Insert(ctx context.Context, data *Client) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Client, error)
		FindOneByClientId(ctx context.Context, clientId string) (*Client, error)
		Update(ctx context.Context, data *Client) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultClientModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Client struct {
		Id             uint64       `db:"id"`
		ClientId       string       `db:"client_id"`        // 平台id
		ClientJsonInfo string       `db:"client_json_info"` // 客户端信息(JSON字符串)
		RegistrationIp string       `db:"registration_ip"`  // 注册IP
		Status         int64        `db:"status"`           // 0=待邮箱验证 1=正常 2=停用（历史数据默认1）
		VerifiedAt     sql.NullTime `db:"verified_at"`      // 邮箱验证通过时间
		OwnerEmail     string       `db:"owner_email"`      // 租户负责人邮箱
		CreatedAt      time.Time    `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time    `db:"updated_at"`       // 更新时间
	}
)

func newClientModel(conn sqlx.SqlConn) *defaultClientModel {
	return &defaultClientModel{
		conn:  conn,
		table: "`client`",
	}
}

func (m *defaultClientModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClientModel) FindOne(ctx context.Context, id uint64) (*Client, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clientRows, m.table)
	var resp Client
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientModel) FindOneByClientId(ctx context.Context, clientId string) (*Client, error) {
	var resp Client
	query := fmt.Sprintf("select %s from %s where `client_id` = ? limit 1", clientRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientModel) Insert(ctx context.Context, data *Client) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, clientRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.ClientJsonInfo, data.RegistrationIp, data.Status, data.VerifiedAt, data.OwnerEmail)
	return ret, err
}

func (m *defaultClientModel) Update(ctx context.Context, newData *Client) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, clientRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.ClientJsonInfo, newData.RegistrationIp, newData.Status, newData.VerifiedAt, newData.OwnerEmail, newData.Id)
	return err
}

func (m *defaultClientModel) tableName() string {
	return m.table
}
