// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deptDocumentTypeFieldNames          = builder.RawFieldNames(&DeptDocumentType{})
	deptDocumentTypeRows                = strings.Join(deptDocumentTypeFieldNames, ",")
	deptDocumentTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(deptDocumentTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deptDocumentTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(deptDocumentTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	deptDocumentTypeModel interface {
		Insert(ctx context.Context, data *DeptDocumentType) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DeptDocumentType, error)
		FindOneByClientIdDeptCodeDocumentTypeCode(ctx context.Context, clientId string, deptCode string, documentTypeCode string) (*DeptDocumentType, error)
		Update(ctx context.Context, data *DeptDocumentType) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDeptDocumentTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DeptDocumentType struct {
		Id               int64     `db:"id"`                 // 主键ID
		ClientId         string    `db:"client_id"`          // 平台id
		DeptCode         string    `db:"dept_code"`          // 部门编码，关联frDept.DEPT_CODE
		DocumentTypeCode string    `db:"document_type_code"` // 文档类型编码，关联document_type.code
		CreatedAt        time.Time `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`         // 更新时间
	}
)

func newDeptDocumentTypeModel(conn sqlx.SqlConn) *defaultDeptDocumentTypeModel {
	return &defaultDeptDocumentTypeModel{
		conn:  conn,
		table: "`dept_document_type`",
	}
}

func (m *defaultDeptDocumentTypeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDeptDocumentTypeModel) FindOne(ctx context.Context, id int64) (*DeptDocumentType, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", deptDocumentTypeRows, m.table)
	var resp DeptDocumentType
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeptDocumentTypeModel) FindOneByClientIdDeptCodeDocumentTypeCode(ctx context.Context, clientId string, deptCode string, documentTypeCode string) (*DeptDocumentType, error) {
	var resp DeptDocumentType
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `dept_code` = ? and `document_type_code` = ? limit 1", deptDocumentTypeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, deptCode, documentTypeCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeptDocumentTypeModel) Insert(ctx context.Context, data *DeptDocumentType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, deptDocumentTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.DeptCode, data.DocumentTypeCode)
	return ret, err
}

func (m *defaultDeptDocumentTypeModel) Update(ctx context.Context, newData *DeptDocumentType) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, deptDocumentTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.DeptCode, newData.DocumentTypeCode, newData.Id)
	return err
}

func (m *defaultDeptDocumentTypeModel) tableName() string {
	return m.table
}
