// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	difyOptionsFieldNames          = builder.RawFieldNames(&DifyOptions{})
	difyOptionsRows                = strings.Join(difyOptionsFieldNames, ",")
	difyOptionsRowsExpectAutoSet   = strings.Join(stringx.Remove(difyOptionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	difyOptionsRowsWithPlaceHolder = strings.Join(stringx.Remove(difyOptionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	difyOptionsModel interface {
		Insert(ctx context.Context, data *DifyOptions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*DifyOptions, error)
		FindOneByClientIdName(ctx context.Context, clientId string, name string) (*DifyOptions, error)
		Update(ctx context.Context, data *DifyOptions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultDifyOptionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DifyOptions struct {
		Id          uint64 `db:"id"`
		ClientId    string `db:"client_id"` // 平台id
		Name        string `db:"name"`
		Url         string `db:"url"`
		ApiKey      string `db:"api_key"`
		Description string `db:"description"`
	}
)

func newDifyOptionsModel(conn sqlx.SqlConn) *defaultDifyOptionsModel {
	return &defaultDifyOptionsModel{
		conn:  conn,
		table: "`dify_options`",
	}
}

func (m *defaultDifyOptionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDifyOptionsModel) FindOne(ctx context.Context, id uint64) (*DifyOptions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", difyOptionsRows, m.table)
	var resp DifyOptions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDifyOptionsModel) FindOneByClientIdName(ctx context.Context, clientId string, name string) (*DifyOptions, error) {
	var resp DifyOptions
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `name` = ? limit 1", difyOptionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDifyOptionsModel) Insert(ctx context.Context, data *DifyOptions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, difyOptionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.Name, data.Url, data.ApiKey, data.Description)
	return ret, err
}

func (m *defaultDifyOptionsModel) Update(ctx context.Context, newData *DifyOptions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, difyOptionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.Name, newData.Url, newData.ApiKey, newData.Description, newData.Id)
	return err
}

func (m *defaultDifyOptionsModel) tableName() string {
	return m.table
}
