// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	documentTypeFieldNames          = builder.RawFieldNames(&DocumentType{})
	documentTypeRows                = strings.Join(documentTypeFieldNames, ",")
	documentTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(documentTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	documentTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(documentTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	documentTypeModel interface {
		Insert(ctx context.Context, data *DocumentType) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*DocumentType, error)
		FindOneByClientIdCode(ctx context.Context, clientId string, code string) (*DocumentType, error)
		Update(ctx context.Context, data *DocumentType) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultDocumentTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DocumentType struct {
		Id          uint64    `db:"id"`
		ClientId    string    `db:"client_id"`   // 平台id
		Code        string    `db:"code"`        // 主键ID
		Name        string    `db:"name"`        // 文档类型名称
		IsDisabled  int64     `db:"is_disabled"` // 是否被禁止
		Description string    `db:"description"` // 描述备注
		CreatedAt   time.Time `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`  // 更新时间
	}
)

func newDocumentTypeModel(conn sqlx.SqlConn) *defaultDocumentTypeModel {
	return &defaultDocumentTypeModel{
		conn:  conn,
		table: "`document_type`",
	}
}

func (m *defaultDocumentTypeModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDocumentTypeModel) FindOne(ctx context.Context, id uint64) (*DocumentType, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", documentTypeRows, m.table)
	var resp DocumentType
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDocumentTypeModel) FindOneByClientIdCode(ctx context.Context, clientId string, code string) (*DocumentType, error) {
	var resp DocumentType
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `code` = ? limit 1", documentTypeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDocumentTypeModel) Insert(ctx context.Context, data *DocumentType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, documentTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.Code, data.Name, data.IsDisabled, data.Description)
	return ret, err
}

func (m *defaultDocumentTypeModel) Update(ctx context.Context, newData *DocumentType) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, documentTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.Code, newData.Name, newData.IsDisabled, newData.Description, newData.Id)
	return err
}

func (m *defaultDocumentTypeModel) tableName() string {
	return m.table
}
