// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	empDocumentTypeFieldNames          = builder.RawFieldNames(&EmpDocumentType{})
	empDocumentTypeRows                = strings.Join(empDocumentTypeFieldNames, ",")
	empDocumentTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(empDocumentTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	empDocumentTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(empDocumentTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	empDocumentTypeModel interface {
		Insert(ctx context.Context, data *EmpDocumentType) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EmpDocumentType, error)
		FindOneByClientIdEmpCodeDocumentTypeCode(ctx context.Context, clientId string, empCode string, documentTypeCode string) (*EmpDocumentType, error)
		Update(ctx context.Context, data *EmpDocumentType) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEmpDocumentTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EmpDocumentType struct {
		Id               int64     `db:"id"`                 // 主键ID
		ClientId         string    `db:"client_id"`          // 平台id
		EmpCode          string    `db:"emp_code"`           // 员工编码，关联frEmp.FempCode
		DocumentTypeCode string    `db:"document_type_code"` // 文档类型编码，关联document_type.code
		CreatedAt        time.Time `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`         // 更新时间
	}
)

func newEmpDocumentTypeModel(conn sqlx.SqlConn) *defaultEmpDocumentTypeModel {
	return &defaultEmpDocumentTypeModel{
		conn:  conn,
		table: "`emp_document_type`",
	}
}

func (m *defaultEmpDocumentTypeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEmpDocumentTypeModel) FindOne(ctx context.Context, id int64) (*EmpDocumentType, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", empDocumentTypeRows, m.table)
	var resp EmpDocumentType
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmpDocumentTypeModel) FindOneByClientIdEmpCodeDocumentTypeCode(ctx context.Context, clientId string, empCode string, documentTypeCode string) (*EmpDocumentType, error) {
	var resp EmpDocumentType
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `emp_code` = ? and `document_type_code` = ? limit 1", empDocumentTypeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, empCode, documentTypeCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmpDocumentTypeModel) Insert(ctx context.Context, data *EmpDocumentType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, empDocumentTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.EmpCode, data.DocumentTypeCode)
	return ret, err
}

func (m *defaultEmpDocumentTypeModel) Update(ctx context.Context, newData *EmpDocumentType) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, empDocumentTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.EmpCode, newData.DocumentTypeCode, newData.Id)
	return err
}

func (m *defaultEmpDocumentTypeModel) tableName() string {
	return m.table
}
