// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	empPasswordFieldNames          = builder.RawFieldNames(&EmpPassword{})
	empPasswordRows                = strings.Join(empPasswordFieldNames, ",")
	empPasswordRowsExpectAutoSet   = strings.Join(stringx.Remove(empPasswordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	empPasswordRowsWithPlaceHolder = strings.Join(stringx.Remove(empPasswordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	empPasswordModel interface {
		Insert(ctx context.Context, data *EmpPassword) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*EmpPassword, error)
		FindOneByClientIdEmpCode(ctx context.Context, clientId string, empCode string) (*EmpPassword, error)
		Update(ctx context.Context, data *EmpPassword) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultEmpPasswordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EmpPassword struct {
		Id        uint64    `db:"id"`
		ClientId  string    `db:"client_id"`  // 平台id
		EmpCode   string    `db:"emp_code"`   // 员工编码，关联frEmp.FempCode
		Password  string    `db:"password"`   // 密码（加密存储）
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newEmpPasswordModel(conn sqlx.SqlConn) *defaultEmpPasswordModel {
	return &defaultEmpPasswordModel{
		conn:  conn,
		table: "`emp_password`",
	}
}

func (m *defaultEmpPasswordModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEmpPasswordModel) FindOne(ctx context.Context, id uint64) (*EmpPassword, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", empPasswordRows, m.table)
	var resp EmpPassword
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmpPasswordModel) FindOneByClientIdEmpCode(ctx context.Context, clientId string, empCode string) (*EmpPassword, error) {
	var resp EmpPassword
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `emp_code` = ? limit 1", empPasswordRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, empCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmpPasswordModel) Insert(ctx context.Context, data *EmpPassword) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, empPasswordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.EmpCode, data.Password)
	return ret, err
}

func (m *defaultEmpPasswordModel) Update(ctx context.Context, newData *EmpPassword) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, empPasswordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.EmpCode, newData.Password, newData.Id)
	return err
}

func (m *defaultEmpPasswordModel) tableName() string {
	return m.table
}
