// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	examsCategoryFieldNames          = builder.RawFieldNames(&ExamsCategory{})
	examsCategoryRows                = strings.Join(examsCategoryFieldNames, ",")
	examsCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(examsCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	examsCategoryRowsWithPlaceHolder = strings.Join(stringx.Remove(examsCategoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	examsCategoryModel interface {
		Insert(ctx context.Context, data *ExamsCategory) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ExamsCategory, error)
		Update(ctx context.Context, data *ExamsCategory) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultExamsCategoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ExamsCategory struct {
		Id           uint64    `db:"id"`
		CategoryName string    `db:"category_name"` // 试题分类名
		Sequence     int64     `db:"sequence"`
		State        int64     `db:"state"` // 逻辑删除
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newExamsCategoryModel(conn sqlx.SqlConn) *defaultExamsCategoryModel {
	return &defaultExamsCategoryModel{
		conn:  conn,
		table: "`exams_category`",
	}
}

func (m *defaultExamsCategoryModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultExamsCategoryModel) FindOne(ctx context.Context, id uint64) (*ExamsCategory, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", examsCategoryRows, m.table)
	var resp ExamsCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExamsCategoryModel) Insert(ctx context.Context, data *ExamsCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, examsCategoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CategoryName, data.Sequence, data.State)
	return ret, err
}

func (m *defaultExamsCategoryModel) Update(ctx context.Context, data *ExamsCategory) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, examsCategoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CategoryName, data.Sequence, data.State, data.Id)
	return err
}

func (m *defaultExamsCategoryModel) tableName() string {
	return m.table
}
