// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	examsFieldNames          = builder.RawFieldNames(&Exams{})
	examsRows                = strings.Join(examsFieldNames, ",")
	examsRowsExpectAutoSet   = strings.Join(stringx.Remove(examsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	examsRowsWithPlaceHolder = strings.Join(stringx.Remove(examsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	examsModel interface {
		Insert(ctx context.Context, data *Exams) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Exams, error)
		Update(ctx context.Context, data *Exams) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultExamsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Exams struct {
		Id                   uint64    `db:"id"`
		ExamSname            string    `db:"exam_sname"` // 测试短名字
		UserId               uint64    `db:"user_id"`    // 创建人
		ExamName             string    `db:"exam_name"`  // 题目名称
		SortOrder            int64     `db:"sort_order"`
		Profile              string    `db:"profile"`       // 简单介绍
		Description          string    `db:"description"`   // 描述
		Thumb                string    `db:"thumb"`         // 测卷缩略图
		Cover                string    `db:"cover"`         // 试卷封面
		QuestionKeys         string    `db:"question_keys"` // 题目的key集合
		MaxScore             string    `db:"max_score"`
		OriginalQuestions    string    `db:"original_questions"`
		Questions            string    `db:"questions"`               // 所有题目
		QuestionCount        uint64    `db:"question_count"`          // 题目数量
		TimeLimit            uint64    `db:"time_limit"`              // 限时（单位分钟）
		Free                 uint64    `db:"free"`                    // 0收费，1免费
		Fee                  int64     `db:"fee"`                     // 收费费用
		OneFree              uint64    `db:"one_free"`                // 买一赠一
		EvaluatorUserIds     string    `db:"evaluator_user_ids"`      // 评价者ids
		EvaluateeUserIds     string    `db:"evaluatee_user_ids"`      // 被评者ids
		ReportAverageUserIds string    `db:"report_average_user_ids"` // 统计平均分数--可查看者ids
		ReportDetailUserIds  string    `db:"report_detail_user_ids"`  // 所有人评价分数--可查看者ids
		AuditStatus          uint64    `db:"audit_status"`            // 0未审核，1审核通过，2审核驳回
		AuditMessage         string    `db:"audit_message"`           // 审核信息
		AuditTime            time.Time `db:"audit_time"`              // 审核时间
		Removed              uint64    `db:"removed"`                 // 0：已下架，1：正常
		State                uint64    `db:"state"`                   // 逻辑删除
		CreatedAt            time.Time `db:"created_at"`
		UpdatedAt            time.Time `db:"updated_at"`
		Praise               uint64    `db:"praise"`    // 点赞数
		Feedbacks            string    `db:"feedbacks"` // 测评的反馈
		Summarys             string    `db:"summarys"`  // 概要，总结
		CategoryId           uint64    `db:"category_id"`
		Stops                string    `db:"stops"`        // 试题中断提示
		IsHot                uint64    `db:"isHot"`        // 是否热门
		HomeDisplay          uint64    `db:"home_display"` // 首页展示
		OldJson              string    `db:"old_json"`
	}
)

func newExamsModel(conn sqlx.SqlConn) *defaultExamsModel {
	return &defaultExamsModel{
		conn:  conn,
		table: "`exams`",
	}
}

func (m *defaultExamsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultExamsModel) FindOne(ctx context.Context, id uint64) (*Exams, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", examsRows, m.table)
	var resp Exams
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExamsModel) Insert(ctx context.Context, data *Exams) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, examsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ExamSname, data.UserId, data.ExamName, data.SortOrder, data.Profile, data.Description, data.Thumb, data.Cover, data.QuestionKeys, data.MaxScore, data.OriginalQuestions, data.Questions, data.QuestionCount, data.TimeLimit, data.Free, data.Fee, data.OneFree, data.EvaluatorUserIds, data.EvaluateeUserIds, data.ReportAverageUserIds, data.ReportDetailUserIds, data.AuditStatus, data.AuditMessage, data.AuditTime, data.Removed, data.State, data.Praise, data.Feedbacks, data.Summarys, data.CategoryId, data.Stops, data.IsHot, data.HomeDisplay, data.OldJson)
	return ret, err
}

func (m *defaultExamsModel) Update(ctx context.Context, data *Exams) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, examsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ExamSname, data.UserId, data.ExamName, data.SortOrder, data.Profile, data.Description, data.Thumb, data.Cover, data.QuestionKeys, data.MaxScore, data.OriginalQuestions, data.Questions, data.QuestionCount, data.TimeLimit, data.Free, data.Fee, data.OneFree, data.EvaluatorUserIds, data.EvaluateeUserIds, data.ReportAverageUserIds, data.ReportDetailUserIds, data.AuditStatus, data.AuditMessage, data.AuditTime, data.Removed, data.State, data.Praise, data.Feedbacks, data.Summarys, data.CategoryId, data.Stops, data.IsHot, data.HomeDisplay, data.OldJson, data.Id)
	return err
}

func (m *defaultExamsModel) tableName() string {
	return m.table
}
