// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileLikeFieldNames          = builder.RawFieldNames(&FileLike{})
	fileLikeRows                = strings.Join(fileLikeFieldNames, ",")
	fileLikeRowsExpectAutoSet   = strings.Join(stringx.Remove(fileLikeFieldNames, "`like_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileLikeRowsWithPlaceHolder = strings.Join(stringx.Remove(fileLikeFieldNames, "`like_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileLikeModel interface {
		Insert(ctx context.Context, data *FileLike) (sql.Result, error)
		FindOne(ctx context.Context, likeId uint64) (*FileLike, error)
		FindOneByUserIdPmd5(ctx context.Context, userId uint64, pmd5 string) (*FileLike, error)
		Update(ctx context.Context, data *FileLike) error
		Delete(ctx context.Context, likeId uint64) error
	}

	defaultFileLikeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FileLike struct {
		LikeId   uint64 `db:"like_id"`
		UserId   uint64 `db:"user_id"`
		Username string `db:"username"` // 用户姓名
		Pmd5     string `db:"pmd5"`
		Filename string `db:"filename"` // 歌曲名字
		Degree   int64  `db:"degree"`
	}
)

func newFileLikeModel(conn sqlx.SqlConn) *defaultFileLikeModel {
	return &defaultFileLikeModel{
		conn:  conn,
		table: "`file_like`",
	}
}

func (m *defaultFileLikeModel) Delete(ctx context.Context, likeId uint64) error {
	query := fmt.Sprintf("delete from %s where `like_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, likeId)
	return err
}

func (m *defaultFileLikeModel) FindOne(ctx context.Context, likeId uint64) (*FileLike, error) {
	query := fmt.Sprintf("select %s from %s where `like_id` = ? limit 1", fileLikeRows, m.table)
	var resp FileLike
	err := m.conn.QueryRowCtx(ctx, &resp, query, likeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileLikeModel) FindOneByUserIdPmd5(ctx context.Context, userId uint64, pmd5 string) (*FileLike, error) {
	var resp FileLike
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `pmd5` = ? limit 1", fileLikeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, pmd5)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileLikeModel) Insert(ctx context.Context, data *FileLike) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, fileLikeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Pmd5, data.Filename, data.Degree)
	return ret, err
}

func (m *defaultFileLikeModel) Update(ctx context.Context, newData *FileLike) error {
	query := fmt.Sprintf("update %s set %s where `like_id` = ?", m.table, fileLikeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Username, newData.Pmd5, newData.Filename, newData.Degree, newData.LikeId)
	return err
}

func (m *defaultFileLikeModel) tableName() string {
	return m.table
}
