// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumAttachmentsFieldNames          = builder.RawFieldNames(&ForumAttachments{})
	forumAttachmentsRows                = strings.Join(forumAttachmentsFieldNames, ",")
	forumAttachmentsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumAttachmentsFieldNames, "`attachment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumAttachmentsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumAttachmentsFieldNames, "`attachment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumAttachmentsModel interface {
		Insert(ctx context.Context, data *ForumAttachments) (sql.Result, error)
		FindOne(ctx context.Context, attachmentId uint64) (*ForumAttachments, error)
		Update(ctx context.Context, data *ForumAttachments) error
		Delete(ctx context.Context, attachmentId uint64) error
	}

	defaultForumAttachmentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumAttachments struct {
		AttachmentId     uint64    `db:"attachment_id"`
		TopicId          uint64    `db:"topic_id"`          // 主题ID
		PostId           uint64    `db:"post_id"`           // 回复ID
		UserId           uint64    `db:"user_id"`           // 上传用户ID
		Filename         string    `db:"filename"`          // 文件名
		OriginalFilename string    `db:"original_filename"` // 原始文件名
		FilePath         string    `db:"file_path"`         // 文件路径
		FileSize         uint64    `db:"file_size"`         // 文件大小
		MimeType         string    `db:"mime_type"`         // MIME类型
		DownloadCount    uint64    `db:"download_count"`    // 下载次数
		CreatedAt        time.Time `db:"created_at"`
	}
)

func newForumAttachmentsModel(conn sqlx.SqlConn) *defaultForumAttachmentsModel {
	return &defaultForumAttachmentsModel{
		conn:  conn,
		table: "`forum_attachments`",
	}
}

func (m *defaultForumAttachmentsModel) Delete(ctx context.Context, attachmentId uint64) error {
	query := fmt.Sprintf("delete from %s where `attachment_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, attachmentId)
	return err
}

func (m *defaultForumAttachmentsModel) FindOne(ctx context.Context, attachmentId uint64) (*ForumAttachments, error) {
	query := fmt.Sprintf("select %s from %s where `attachment_id` = ? limit 1", forumAttachmentsRows, m.table)
	var resp ForumAttachments
	err := m.conn.QueryRowCtx(ctx, &resp, query, attachmentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumAttachmentsModel) Insert(ctx context.Context, data *ForumAttachments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, forumAttachmentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TopicId, data.PostId, data.UserId, data.Filename, data.OriginalFilename, data.FilePath, data.FileSize, data.MimeType, data.DownloadCount)
	return ret, err
}

func (m *defaultForumAttachmentsModel) Update(ctx context.Context, data *ForumAttachments) error {
	query := fmt.Sprintf("update %s set %s where `attachment_id` = ?", m.table, forumAttachmentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TopicId, data.PostId, data.UserId, data.Filename, data.OriginalFilename, data.FilePath, data.FileSize, data.MimeType, data.DownloadCount, data.AttachmentId)
	return err
}

func (m *defaultForumAttachmentsModel) tableName() string {
	return m.table
}
