// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumModeratorsFieldNames          = builder.RawFieldNames(&ForumModerators{})
	forumModeratorsRows                = strings.Join(forumModeratorsFieldNames, ",")
	forumModeratorsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumModeratorsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumModeratorsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumModeratorsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumModeratorsModel interface {
		Insert(ctx context.Context, data *ForumModerators) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ForumModerators, error)
		FindOneByForumIdUserId(ctx context.Context, forumId uint64, userId uint64) (*ForumModerators, error)
		Update(ctx context.Context, data *ForumModerators) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultForumModeratorsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumModerators struct {
		Id          uint64    `db:"id"`
		ForumId     uint64    `db:"forum_id"`    // 论坛ID
		UserId      uint64    `db:"user_id"`     // 用户ID
		Permissions string    `db:"permissions"` // 权限列表
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newForumModeratorsModel(conn sqlx.SqlConn) *defaultForumModeratorsModel {
	return &defaultForumModeratorsModel{
		conn:  conn,
		table: "`forum_moderators`",
	}
}

func (m *defaultForumModeratorsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultForumModeratorsModel) FindOne(ctx context.Context, id uint64) (*ForumModerators, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", forumModeratorsRows, m.table)
	var resp ForumModerators
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumModeratorsModel) FindOneByForumIdUserId(ctx context.Context, forumId uint64, userId uint64) (*ForumModerators, error) {
	var resp ForumModerators
	query := fmt.Sprintf("select %s from %s where `forum_id` = ? and `user_id` = ? limit 1", forumModeratorsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, forumId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumModeratorsModel) Insert(ctx context.Context, data *ForumModerators) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, forumModeratorsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ForumId, data.UserId, data.Permissions)
	return ret, err
}

func (m *defaultForumModeratorsModel) Update(ctx context.Context, newData *ForumModerators) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, forumModeratorsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ForumId, newData.UserId, newData.Permissions, newData.Id)
	return err
}

func (m *defaultForumModeratorsModel) tableName() string {
	return m.table
}
