// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumForumsFieldNames          = builder.RawFieldNames(&ForumForums{})
	forumForumsRows                = strings.Join(forumForumsFieldNames, ",")
	forumForumsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumForumsFieldNames, "`forum_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumForumsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumForumsFieldNames, "`forum_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumForumsModel interface {
		Insert(ctx context.Context, data *ForumForums) (sql.Result, error)
		FindOne(ctx context.Context, forumId uint64) (*ForumForums, error)
		Update(ctx context.Context, data *ForumForums) error
		Delete(ctx context.Context, forumId uint64) error
	}

	defaultForumForumsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumForums struct {
		ForumId        uint64         `db:"forum_id"`
		CategoryId     uint64         `db:"category_id"`      // 所属分类ID
		Name           string         `db:"name"`             // 论坛名称
		Description    sql.NullString `db:"description"`      // 论坛描述
		Slug           string         `db:"slug"`             // 论坛别名
		SortOrder      int64          `db:"sort_order"`       // 排序
		IsActive       uint64         `db:"is_active"`        // 是否激活
		AllowGuestRead uint64         `db:"allow_guest_read"` // 允许游客阅读
		AllowGuestPost uint64         `db:"allow_guest_post"` // 允许游客发帖
		CreatedAt      time.Time      `db:"created_at"`
		UpdatedAt      time.Time      `db:"updated_at"`
	}
)

func newForumForumsModel(conn sqlx.SqlConn) *defaultForumForumsModel {
	return &defaultForumForumsModel{
		conn:  conn,
		table: "`forum_forums`",
	}
}

func (m *defaultForumForumsModel) Delete(ctx context.Context, forumId uint64) error {
	query := fmt.Sprintf("delete from %s where `forum_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, forumId)
	return err
}

func (m *defaultForumForumsModel) FindOne(ctx context.Context, forumId uint64) (*ForumForums, error) {
	query := fmt.Sprintf("select %s from %s where `forum_id` = ? limit 1", forumForumsRows, m.table)
	var resp ForumForums
	err := m.conn.QueryRowCtx(ctx, &resp, query, forumId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumForumsModel) Insert(ctx context.Context, data *ForumForums) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, forumForumsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CategoryId, data.Name, data.Description, data.Slug, data.SortOrder, data.IsActive, data.AllowGuestRead, data.AllowGuestPost)
	return ret, err
}

func (m *defaultForumForumsModel) Update(ctx context.Context, data *ForumForums) error {
	query := fmt.Sprintf("update %s set %s where `forum_id` = ?", m.table, forumForumsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CategoryId, data.Name, data.Description, data.Slug, data.SortOrder, data.IsActive, data.AllowGuestRead, data.AllowGuestPost, data.ForumId)
	return err
}

func (m *defaultForumForumsModel) tableName() string {
	return m.table
}
