// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumPostLikesFieldNames          = builder.RawFieldNames(&ForumPostLikes{})
	forumPostLikesRows                = strings.Join(forumPostLikesFieldNames, ",")
	forumPostLikesRowsExpectAutoSet   = strings.Join(stringx.Remove(forumPostLikesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumPostLikesRowsWithPlaceHolder = strings.Join(stringx.Remove(forumPostLikesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumPostLikesModel interface {
		Insert(ctx context.Context, data *ForumPostLikes) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ForumPostLikes, error)
		FindOneByPostIdUserId(ctx context.Context, postId uint64, userId uint64) (*ForumPostLikes, error)
		Update(ctx context.Context, data *ForumPostLikes) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultForumPostLikesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumPostLikes struct {
		Id        uint64    `db:"id"`
		PostId    uint64    `db:"post_id"` // 回复ID
		UserId    uint64    `db:"user_id"` // 用户ID
		CreatedAt time.Time `db:"created_at"`
	}
)

func newForumPostLikesModel(conn sqlx.SqlConn) *defaultForumPostLikesModel {
	return &defaultForumPostLikesModel{
		conn:  conn,
		table: "`forum_post_likes`",
	}
}

func (m *defaultForumPostLikesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultForumPostLikesModel) FindOne(ctx context.Context, id uint64) (*ForumPostLikes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", forumPostLikesRows, m.table)
	var resp ForumPostLikes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumPostLikesModel) FindOneByPostIdUserId(ctx context.Context, postId uint64, userId uint64) (*ForumPostLikes, error) {
	var resp ForumPostLikes
	query := fmt.Sprintf("select %s from %s where `post_id` = ? and `user_id` = ? limit 1", forumPostLikesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumPostLikesModel) Insert(ctx context.Context, data *ForumPostLikes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, forumPostLikesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.UserId)
	return ret, err
}

func (m *defaultForumPostLikesModel) Update(ctx context.Context, newData *ForumPostLikes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, forumPostLikesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PostId, newData.UserId, newData.Id)
	return err
}

func (m *defaultForumPostLikesModel) tableName() string {
	return m.table
}
