// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumReportsFieldNames          = builder.RawFieldNames(&ForumReports{})
	forumReportsRows                = strings.Join(forumReportsFieldNames, ",")
	forumReportsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumReportsFieldNames, "`report_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumReportsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumReportsFieldNames, "`report_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumReportsModel interface {
		Insert(ctx context.Context, data *ForumReports) (sql.Result, error)
		FindOne(ctx context.Context, reportId uint64) (*ForumReports, error)
		Update(ctx context.Context, data *ForumReports) error
		Delete(ctx context.Context, reportId uint64) error
	}

	defaultForumReportsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumReports struct {
		ReportId       uint64         `db:"report_id"`
		ReporterId     uint64         `db:"reporter_id"`      // 举报用户ID
		ReportedUserId uint64         `db:"reported_user_id"` // 被举报用户ID
		TopicId        uint64         `db:"topic_id"`         // 相关主题ID
		PostId         uint64         `db:"post_id"`          // 相关回复ID
		Reason         string         `db:"reason"`           // 举报原因
		Description    sql.NullString `db:"description"`      // 详细描述
		Status         string         `db:"status"`           // 处理状态
		HandledBy      uint64         `db:"handled_by"`       // 处理人ID
		HandledAt      sql.NullTime   `db:"handled_at"`       // 处理时间
		CreatedAt      time.Time      `db:"created_at"`
	}
)

func newForumReportsModel(conn sqlx.SqlConn) *defaultForumReportsModel {
	return &defaultForumReportsModel{
		conn:  conn,
		table: "`forum_reports`",
	}
}

func (m *defaultForumReportsModel) Delete(ctx context.Context, reportId uint64) error {
	query := fmt.Sprintf("delete from %s where `report_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, reportId)
	return err
}

func (m *defaultForumReportsModel) FindOne(ctx context.Context, reportId uint64) (*ForumReports, error) {
	query := fmt.Sprintf("select %s from %s where `report_id` = ? limit 1", forumReportsRows, m.table)
	var resp ForumReports
	err := m.conn.QueryRowCtx(ctx, &resp, query, reportId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumReportsModel) Insert(ctx context.Context, data *ForumReports) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, forumReportsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ReporterId, data.ReportedUserId, data.TopicId, data.PostId, data.Reason, data.Description, data.Status, data.HandledBy, data.HandledAt)
	return ret, err
}

func (m *defaultForumReportsModel) Update(ctx context.Context, data *ForumReports) error {
	query := fmt.Sprintf("update %s set %s where `report_id` = ?", m.table, forumReportsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ReporterId, data.ReportedUserId, data.TopicId, data.PostId, data.Reason, data.Description, data.Status, data.HandledBy, data.HandledAt, data.ReportId)
	return err
}

func (m *defaultForumReportsModel) tableName() string {
	return m.table
}
