// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumUserStatsFieldNames          = builder.RawFieldNames(&ForumUserStats{})
	forumUserStatsRows                = strings.Join(forumUserStatsFieldNames, ",")
	forumUserStatsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumUserStatsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumUserStatsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumUserStatsFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumUserStatsModel interface {
		Insert(ctx context.Context, data *ForumUserStats) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*ForumUserStats, error)
		Update(ctx context.Context, data *ForumUserStats) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultForumUserStatsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumUserStats struct {
		UserId         uint64       `db:"user_id"`          // 用户ID
		TopicCount     uint64       `db:"topic_count"`      // 发帖数量
		PostCount      uint64       `db:"post_count"`       // 回复数量
		LikeReceived   uint64       `db:"like_received"`    // 收到点赞数
		LikeGiven      uint64       `db:"like_given"`       // 给出点赞数
		LastActivityAt sql.NullTime `db:"last_activity_at"` // 最后活动时间
		CreatedAt      time.Time    `db:"created_at"`
		UpdatedAt      time.Time    `db:"updated_at"`
	}
)

func newForumUserStatsModel(conn sqlx.SqlConn) *defaultForumUserStatsModel {
	return &defaultForumUserStatsModel{
		conn:  conn,
		table: "`forum_user_stats`",
	}
}

func (m *defaultForumUserStatsModel) Delete(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultForumUserStatsModel) FindOne(ctx context.Context, userId uint64) (*ForumUserStats, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", forumUserStatsRows, m.table)
	var resp ForumUserStats
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumUserStatsModel) Insert(ctx context.Context, data *ForumUserStats) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, forumUserStatsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TopicCount, data.PostCount, data.LikeReceived, data.LikeGiven, data.LastActivityAt)
	return ret, err
}

func (m *defaultForumUserStatsModel) Update(ctx context.Context, data *ForumUserStats) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, forumUserStatsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TopicCount, data.PostCount, data.LikeReceived, data.LikeGiven, data.LastActivityAt, data.UserId)
	return err
}

func (m *defaultForumUserStatsModel) tableName() string {
	return m.table
}
