// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumTopicsFieldNames          = builder.RawFieldNames(&ForumTopics{})
	forumTopicsRows                = strings.Join(forumTopicsFieldNames, ",")
	forumTopicsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumTopicsFieldNames, "`topic_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumTopicsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumTopicsFieldNames, "`topic_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumTopicsModel interface {
		Insert(ctx context.Context, data *ForumTopics) (sql.Result, error)
		FindOne(ctx context.Context, topicId uint64) (*ForumTopics, error)
		Update(ctx context.Context, data *ForumTopics) error
		Delete(ctx context.Context, topicId uint64) error
	}

	defaultForumTopicsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumTopics struct {
		TopicId         uint64         `db:"topic_id"`
		ForumId         uint64         `db:"forum_id"`           // 所属论坛ID
		UserId          uint64         `db:"user_id"`            // 发帖用户ID
		Title           string         `db:"title"`              // 帖子标题
		Content         sql.NullString `db:"content"`            // 帖子内容
		Slug            string         `db:"slug"`               // 帖子别名
		IsSticky        uint64         `db:"is_sticky"`          // 是否置顶
		IsLocked        uint64         `db:"is_locked"`          // 是否锁定
		IsAnnouncement  uint64         `db:"is_announcement"`    // 是否公告
		ViewCount       uint64         `db:"view_count"`         // 浏览次数
		ReplyCount      uint64         `db:"reply_count"`        // 回复次数
		LastReplyUserId uint64         `db:"last_reply_user_id"` // 最后回复用户ID
		LastReplyAt     sql.NullTime   `db:"last_reply_at"`      // 最后回复时间
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newForumTopicsModel(conn sqlx.SqlConn) *defaultForumTopicsModel {
	return &defaultForumTopicsModel{
		conn:  conn,
		table: "`forum_topics`",
	}
}

func (m *defaultForumTopicsModel) Delete(ctx context.Context, topicId uint64) error {
	query := fmt.Sprintf("delete from %s where `topic_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, topicId)
	return err
}

func (m *defaultForumTopicsModel) FindOne(ctx context.Context, topicId uint64) (*ForumTopics, error) {
	query := fmt.Sprintf("select %s from %s where `topic_id` = ? limit 1", forumTopicsRows, m.table)
	var resp ForumTopics
	err := m.conn.QueryRowCtx(ctx, &resp, query, topicId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumTopicsModel) Insert(ctx context.Context, data *ForumTopics) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, forumTopicsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ForumId, data.UserId, data.Title, data.Content, data.Slug, data.IsSticky, data.IsLocked, data.IsAnnouncement, data.ViewCount, data.ReplyCount, data.LastReplyUserId, data.LastReplyAt)
	return ret, err
}

func (m *defaultForumTopicsModel) Update(ctx context.Context, data *ForumTopics) error {
	query := fmt.Sprintf("update %s set %s where `topic_id` = ?", m.table, forumTopicsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ForumId, data.UserId, data.Title, data.Content, data.Slug, data.IsSticky, data.IsLocked, data.IsAnnouncement, data.ViewCount, data.ReplyCount, data.LastReplyUserId, data.LastReplyAt, data.TopicId)
	return err
}

func (m *defaultForumTopicsModel) tableName() string {
	return m.table
}
