// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumTopicSubscriptionsFieldNames          = builder.RawFieldNames(&ForumTopicSubscriptions{})
	forumTopicSubscriptionsRows                = strings.Join(forumTopicSubscriptionsFieldNames, ",")
	forumTopicSubscriptionsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumTopicSubscriptionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumTopicSubscriptionsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumTopicSubscriptionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumTopicSubscriptionsModel interface {
		Insert(ctx context.Context, data *ForumTopicSubscriptions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ForumTopicSubscriptions, error)
		FindOneByTopicIdUserId(ctx context.Context, topicId uint64, userId uint64) (*ForumTopicSubscriptions, error)
		Update(ctx context.Context, data *ForumTopicSubscriptions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultForumTopicSubscriptionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumTopicSubscriptions struct {
		Id        uint64    `db:"id"`
		TopicId   uint64    `db:"topic_id"` // 主题ID
		UserId    uint64    `db:"user_id"`  // 用户ID
		CreatedAt time.Time `db:"created_at"`
	}
)

func newForumTopicSubscriptionsModel(conn sqlx.SqlConn) *defaultForumTopicSubscriptionsModel {
	return &defaultForumTopicSubscriptionsModel{
		conn:  conn,
		table: "`forum_topic_subscriptions`",
	}
}

func (m *defaultForumTopicSubscriptionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultForumTopicSubscriptionsModel) FindOne(ctx context.Context, id uint64) (*ForumTopicSubscriptions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", forumTopicSubscriptionsRows, m.table)
	var resp ForumTopicSubscriptions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumTopicSubscriptionsModel) FindOneByTopicIdUserId(ctx context.Context, topicId uint64, userId uint64) (*ForumTopicSubscriptions, error) {
	var resp ForumTopicSubscriptions
	query := fmt.Sprintf("select %s from %s where `topic_id` = ? and `user_id` = ? limit 1", forumTopicSubscriptionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, topicId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumTopicSubscriptionsModel) Insert(ctx context.Context, data *ForumTopicSubscriptions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, forumTopicSubscriptionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TopicId, data.UserId)
	return ret, err
}

func (m *defaultForumTopicSubscriptionsModel) Update(ctx context.Context, newData *ForumTopicSubscriptions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, forumTopicSubscriptionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TopicId, newData.UserId, newData.Id)
	return err
}

func (m *defaultForumTopicSubscriptionsModel) tableName() string {
	return m.table
}
