// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumBansFieldNames          = builder.RawFieldNames(&ForumBans{})
	forumBansRows                = strings.Join(forumBansFieldNames, ",")
	forumBansRowsExpectAutoSet   = strings.Join(stringx.Remove(forumBansFieldNames, "`ban_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumBansRowsWithPlaceHolder = strings.Join(stringx.Remove(forumBansFieldNames, "`ban_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumBansModel interface {
		Insert(ctx context.Context, data *ForumBans) (sql.Result, error)
		FindOne(ctx context.Context, banId uint64) (*ForumBans, error)
		Update(ctx context.Context, data *ForumBans) error
		Delete(ctx context.Context, banId uint64) error
	}

	defaultForumBansModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumBans struct {
		BanId       uint64       `db:"ban_id"`
		UserId      uint64       `db:"user_id"`      // 被禁用户ID
		BannedBy    uint64       `db:"banned_by"`    // 禁言人ID
		ForumId     uint64       `db:"forum_id"`     // 论坛ID
		Reason      string       `db:"reason"`       // 禁言原因
		ExpiresAt   sql.NullTime `db:"expires_at"`   // 过期时间
		IsPermanent uint64       `db:"is_permanent"` // 是否永久禁言
		CreatedAt   time.Time    `db:"created_at"`
	}
)

func newForumBansModel(conn sqlx.SqlConn) *defaultForumBansModel {
	return &defaultForumBansModel{
		conn:  conn,
		table: "`forum_bans`",
	}
}

func (m *defaultForumBansModel) Delete(ctx context.Context, banId uint64) error {
	query := fmt.Sprintf("delete from %s where `ban_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, banId)
	return err
}

func (m *defaultForumBansModel) FindOne(ctx context.Context, banId uint64) (*ForumBans, error) {
	query := fmt.Sprintf("select %s from %s where `ban_id` = ? limit 1", forumBansRows, m.table)
	var resp ForumBans
	err := m.conn.QueryRowCtx(ctx, &resp, query, banId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumBansModel) Insert(ctx context.Context, data *ForumBans) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, forumBansRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.BannedBy, data.ForumId, data.Reason, data.ExpiresAt, data.IsPermanent)
	return ret, err
}

func (m *defaultForumBansModel) Update(ctx context.Context, data *ForumBans) error {
	query := fmt.Sprintf("update %s set %s where `ban_id` = ?", m.table, forumBansRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.BannedBy, data.ForumId, data.Reason, data.ExpiresAt, data.IsPermanent, data.BanId)
	return err
}

func (m *defaultForumBansModel) tableName() string {
	return m.table
}
