// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumNotificationsFieldNames          = builder.RawFieldNames(&ForumNotifications{})
	forumNotificationsRows                = strings.Join(forumNotificationsFieldNames, ",")
	forumNotificationsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumNotificationsFieldNames, "`notification_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumNotificationsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumNotificationsFieldNames, "`notification_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumNotificationsModel interface {
		Insert(ctx context.Context, data *ForumNotifications) (sql.Result, error)
		FindOne(ctx context.Context, notificationId uint64) (*ForumNotifications, error)
		Update(ctx context.Context, data *ForumNotifications) error
		Delete(ctx context.Context, notificationId uint64) error
	}

	defaultForumNotificationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumNotifications struct {
		NotificationId uint64         `db:"notification_id"`
		UserId         uint64         `db:"user_id"`      // 接收用户ID
		FromUserId     uint64         `db:"from_user_id"` // 发送用户ID
		Type           string         `db:"type"`         // 通知类型
		Title          string         `db:"title"`        // 通知标题
		Content        sql.NullString `db:"content"`      // 通知内容
		RelatedId      uint64         `db:"related_id"`   // 相关ID
		IsRead         uint64         `db:"is_read"`      // 是否已读
		CreatedAt      time.Time      `db:"created_at"`
	}
)

func newForumNotificationsModel(conn sqlx.SqlConn) *defaultForumNotificationsModel {
	return &defaultForumNotificationsModel{
		conn:  conn,
		table: "`forum_notifications`",
	}
}

func (m *defaultForumNotificationsModel) Delete(ctx context.Context, notificationId uint64) error {
	query := fmt.Sprintf("delete from %s where `notification_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, notificationId)
	return err
}

func (m *defaultForumNotificationsModel) FindOne(ctx context.Context, notificationId uint64) (*ForumNotifications, error) {
	query := fmt.Sprintf("select %s from %s where `notification_id` = ? limit 1", forumNotificationsRows, m.table)
	var resp ForumNotifications
	err := m.conn.QueryRowCtx(ctx, &resp, query, notificationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumNotificationsModel) Insert(ctx context.Context, data *ForumNotifications) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, forumNotificationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FromUserId, data.Type, data.Title, data.Content, data.RelatedId, data.IsRead)
	return ret, err
}

func (m *defaultForumNotificationsModel) Update(ctx context.Context, data *ForumNotifications) error {
	query := fmt.Sprintf("update %s set %s where `notification_id` = ?", m.table, forumNotificationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FromUserId, data.Type, data.Title, data.Content, data.RelatedId, data.IsRead, data.NotificationId)
	return err
}

func (m *defaultForumNotificationsModel) tableName() string {
	return m.table
}
