// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumTopicViewsFieldNames          = builder.RawFieldNames(&ForumTopicViews{})
	forumTopicViewsRows                = strings.Join(forumTopicViewsFieldNames, ",")
	forumTopicViewsRowsExpectAutoSet   = strings.Join(stringx.Remove(forumTopicViewsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumTopicViewsRowsWithPlaceHolder = strings.Join(stringx.Remove(forumTopicViewsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumTopicViewsModel interface {
		Insert(ctx context.Context, data *ForumTopicViews) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ForumTopicViews, error)
		Update(ctx context.Context, data *ForumTopicViews) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultForumTopicViewsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumTopicViews struct {
		Id        uint64         `db:"id"`
		TopicId   uint64         `db:"topic_id"`   // 主题ID
		UserId    uint64         `db:"user_id"`    // 用户ID
		IpAddress string         `db:"ip_address"` // IP地址
		UserAgent sql.NullString `db:"user_agent"` // 用户代理
		ViewedAt  time.Time      `db:"viewed_at"`
	}
)

func newForumTopicViewsModel(conn sqlx.SqlConn) *defaultForumTopicViewsModel {
	return &defaultForumTopicViewsModel{
		conn:  conn,
		table: "`forum_topic_views`",
	}
}

func (m *defaultForumTopicViewsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultForumTopicViewsModel) FindOne(ctx context.Context, id uint64) (*ForumTopicViews, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", forumTopicViewsRows, m.table)
	var resp ForumTopicViews
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumTopicViewsModel) Insert(ctx context.Context, data *ForumTopicViews) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, forumTopicViewsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TopicId, data.UserId, data.IpAddress, data.UserAgent, data.ViewedAt)
	return ret, err
}

func (m *defaultForumTopicViewsModel) Update(ctx context.Context, data *ForumTopicViews) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, forumTopicViewsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TopicId, data.UserId, data.IpAddress, data.UserAgent, data.ViewedAt, data.Id)
	return err
}

func (m *defaultForumTopicViewsModel) tableName() string {
	return m.table
}
