// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forumCategoriesFieldNames          = builder.RawFieldNames(&ForumCategories{})
	forumCategoriesRows                = strings.Join(forumCategoriesFieldNames, ",")
	forumCategoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(forumCategoriesFieldNames, "`category_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	forumCategoriesRowsWithPlaceHolder = strings.Join(stringx.Remove(forumCategoriesFieldNames, "`category_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	forumCategoriesModel interface {
		Insert(ctx context.Context, data *ForumCategories) (sql.Result, error)
		FindOne(ctx context.Context, categoryId uint64) (*ForumCategories, error)
		Update(ctx context.Context, data *ForumCategories) error
		Delete(ctx context.Context, categoryId uint64) error
	}

	defaultForumCategoriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ForumCategories struct {
		CategoryId  uint64         `db:"category_id"`
		Name        string         `db:"name"`        // 分类名称
		Description sql.NullString `db:"description"` // 分类描述
		Slug        string         `db:"slug"`        // 分类别名
		ParentId    uint64         `db:"parent_id"`   // 父分类ID
		SortOrder   int64          `db:"sort_order"`  // 排序
		IsActive    uint64         `db:"is_active"`   // 是否激活
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newForumCategoriesModel(conn sqlx.SqlConn) *defaultForumCategoriesModel {
	return &defaultForumCategoriesModel{
		conn:  conn,
		table: "`forum_categories`",
	}
}

func (m *defaultForumCategoriesModel) Delete(ctx context.Context, categoryId uint64) error {
	query := fmt.Sprintf("delete from %s where `category_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, categoryId)
	return err
}

func (m *defaultForumCategoriesModel) FindOne(ctx context.Context, categoryId uint64) (*ForumCategories, error) {
	query := fmt.Sprintf("select %s from %s where `category_id` = ? limit 1", forumCategoriesRows, m.table)
	var resp ForumCategories
	err := m.conn.QueryRowCtx(ctx, &resp, query, categoryId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForumCategoriesModel) Insert(ctx context.Context, data *ForumCategories) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, forumCategoriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Slug, data.ParentId, data.SortOrder, data.IsActive)
	return ret, err
}

func (m *defaultForumCategoriesModel) Update(ctx context.Context, data *ForumCategories) error {
	query := fmt.Sprintf("update %s set %s where `category_id` = ?", m.table, forumCategoriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Slug, data.ParentId, data.SortOrder, data.IsActive, data.CategoryId)
	return err
}

func (m *defaultForumCategoriesModel) tableName() string {
	return m.table
}
