// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	frDeptFieldNames          = builder.RawFieldNames(&FrDept{})
	frDeptRows                = strings.Join(frDeptFieldNames, ",")
	frDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(frDeptFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	frDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(frDeptFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	frDeptModel interface {
		Insert(ctx context.Context, data *FrDept) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FrDept, error)
		FindOneByClientIdDeptCode(ctx context.Context, clientId string, deptCode string) (*FrDept, error)
		Update(ctx context.Context, data *FrDept) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFrDeptModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FrDept struct {
		Id         int64  `db:"id"`
		ClientId   string `db:"client_id"` // 平台id
		Gsdm       string `db:"gsdm"`
		DeptCode   string `db:"dept_code"`
		DeptName   string `db:"dept_name"`
		ParentCode string `db:"parent_code"`
		EndMark    string `db:"end_mark"`
		GRADE      int64  `db:"GRADE"`
		Kind       string `db:"kind"`
		B0110      string `db:"b0110"`
	}
)

func newFrDeptModel(conn sqlx.SqlConn) *defaultFrDeptModel {
	return &defaultFrDeptModel{
		conn:  conn,
		table: "`fr_dept`",
	}
}

func (m *defaultFrDeptModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFrDeptModel) FindOne(ctx context.Context, id int64) (*FrDept, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", frDeptRows, m.table)
	var resp FrDept
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrDeptModel) FindOneByClientIdDeptCode(ctx context.Context, clientId string, deptCode string) (*FrDept, error) {
	var resp FrDept
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `dept_code` = ? limit 1", frDeptRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, deptCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrDeptModel) Insert(ctx context.Context, data *FrDept) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, frDeptRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.Gsdm, data.DeptCode, data.DeptName, data.ParentCode, data.EndMark, data.GRADE, data.Kind, data.B0110)
	return ret, err
}

func (m *defaultFrDeptModel) Update(ctx context.Context, newData *FrDept) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, frDeptRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.Gsdm, newData.DeptCode, newData.DeptName, newData.ParentCode, newData.EndMark, newData.GRADE, newData.Kind, newData.B0110, newData.Id)
	return err
}

func (m *defaultFrDeptModel) tableName() string {
	return m.table
}
