// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	frEmpFieldNames          = builder.RawFieldNames(&FrEmp{})
	frEmpRows                = strings.Join(frEmpFieldNames, ",")
	frEmpRowsExpectAutoSet   = strings.Join(stringx.Remove(frEmpFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	frEmpRowsWithPlaceHolder = strings.Join(stringx.Remove(frEmpFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	frEmpModel interface {
		Insert(ctx context.Context, data *FrEmp) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FrEmp, error)
		Update(ctx context.Context, data *FrEmp) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFrEmpModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FrEmp struct {
		Id        int64         `db:"id"`
		ClientId  string        `db:"client_id"` // 平台id
		Frylb     string        `db:"frylb"`
		Status    int64         `db:"status"`
		FempName  string        `db:"femp_name"`
		DeptCode  string        `db:"dept_code"`
		FdeptId   sql.NullInt64 `db:"fdept_id"`
		FempCode  string        `db:"femp_code"`
		Fposition string        `db:"fposition"`
		Fbranch   string        `db:"fbranch"`
		Mobile    string        `db:"mobile"` // 手机号
		Email     string        `db:"email"`  // 邮箱
	}
)

func newFrEmpModel(conn sqlx.SqlConn) *defaultFrEmpModel {
	return &defaultFrEmpModel{
		conn:  conn,
		table: "`fr_emp`",
	}
}

func (m *defaultFrEmpModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFrEmpModel) FindOne(ctx context.Context, id int64) (*FrEmp, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", frEmpRows, m.table)
	var resp FrEmp
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrEmpModel) Insert(ctx context.Context, data *FrEmp) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, frEmpRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.Frylb, data.Status, data.FempName, data.DeptCode, data.FdeptId, data.FempCode, data.Fposition, data.Fbranch, data.Mobile, data.Email)
	return ret, err
}

func (m *defaultFrEmpModel) Update(ctx context.Context, data *FrEmp) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, frEmpRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.Frylb, data.Status, data.FempName, data.DeptCode, data.FdeptId, data.FempCode, data.Fposition, data.Fbranch, data.Mobile, data.Email, data.Id)
	return err
}

func (m *defaultFrEmpModel) tableName() string {
	return m.table
}
