// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	frPermissionsFieldNames          = builder.RawFieldNames(&FrPermissions{})
	frPermissionsRows                = strings.Join(frPermissionsFieldNames, ",")
	frPermissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(frPermissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	frPermissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(frPermissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	frPermissionsModel interface {
		Insert(ctx context.Context, data *FrPermissions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FrPermissions, error)
		FindOneByPermission(ctx context.Context, permission string) (*FrPermissions, error)
		Update(ctx context.Context, data *FrPermissions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFrPermissionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FrPermissions struct {
		Id          uint64 `db:"id"`
		Permission  string `db:"permission"`  // 角色编码（唯一标识，如：admin、user）
		Description string `db:"description"` // 角色编码（唯一标识，如：admin、user）
	}
)

func newFrPermissionsModel(conn sqlx.SqlConn) *defaultFrPermissionsModel {
	return &defaultFrPermissionsModel{
		conn:  conn,
		table: "`fr_permissions`",
	}
}

func (m *defaultFrPermissionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFrPermissionsModel) FindOne(ctx context.Context, id uint64) (*FrPermissions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", frPermissionsRows, m.table)
	var resp FrPermissions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrPermissionsModel) FindOneByPermission(ctx context.Context, permission string) (*FrPermissions, error) {
	var resp FrPermissions
	query := fmt.Sprintf("select %s from %s where `permission` = ? limit 1", frPermissionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, permission)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrPermissionsModel) Insert(ctx context.Context, data *FrPermissions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, frPermissionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Permission, data.Description)
	return ret, err
}

func (m *defaultFrPermissionsModel) Update(ctx context.Context, newData *FrPermissions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, frPermissionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Permission, newData.Description, newData.Id)
	return err
}

func (m *defaultFrPermissionsModel) tableName() string {
	return m.table
}
