// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	frRolesFieldNames          = builder.RawFieldNames(&FrRoles{})
	frRolesRows                = strings.Join(frRolesFieldNames, ",")
	frRolesRowsExpectAutoSet   = strings.Join(stringx.Remove(frRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	frRolesRowsWithPlaceHolder = strings.Join(stringx.Remove(frRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	frRolesModel interface {
		Insert(ctx context.Context, data *FrRoles) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FrRoles, error)
		FindOneByClientIdRole(ctx context.Context, clientId string, role string) (*FrRoles, error)
		Update(ctx context.Context, data *FrRoles) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFrRolesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FrRoles struct {
		Id       uint64 `db:"id"`
		ClientId string `db:"client_id"` // 平台id
		Role     string `db:"role"`      // 角色编码（唯一标识，如：admin、user）
		Name     string `db:"name"`      // 描述
	}
)

func newFrRolesModel(conn sqlx.SqlConn) *defaultFrRolesModel {
	return &defaultFrRolesModel{
		conn:  conn,
		table: "`fr_roles`",
	}
}

func (m *defaultFrRolesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFrRolesModel) FindOne(ctx context.Context, id uint64) (*FrRoles, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", frRolesRows, m.table)
	var resp FrRoles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrRolesModel) FindOneByClientIdRole(ctx context.Context, clientId string, role string) (*FrRoles, error) {
	var resp FrRoles
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `role` = ? limit 1", frRolesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, role)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrRolesModel) Insert(ctx context.Context, data *FrRoles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, frRolesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.Role, data.Name)
	return ret, err
}

func (m *defaultFrRolesModel) Update(ctx context.Context, newData *FrRoles) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, frRolesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.Role, newData.Name, newData.Id)
	return err
}

func (m *defaultFrRolesModel) tableName() string {
	return m.table
}
