// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	frUserRolesFieldNames          = builder.RawFieldNames(&FrUserRoles{})
	frUserRolesRows                = strings.Join(frUserRolesFieldNames, ",")
	frUserRolesRowsExpectAutoSet   = strings.Join(stringx.Remove(frUserRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	frUserRolesRowsWithPlaceHolder = strings.Join(stringx.Remove(frUserRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	frUserRolesModel interface {
		Insert(ctx context.Context, data *FrUserRoles) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FrUserRoles, error)
		FindOneByClientIdEmpCodeRole(ctx context.Context, clientId string, empCode string, role string) (*FrUserRoles, error)
		Update(ctx context.Context, data *FrUserRoles) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFrUserRolesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FrUserRoles struct {
		Id       uint64 `db:"id"`        // ID，主键
		ClientId string `db:"client_id"` // 平台id
		EmpCode  string `db:"emp_code"`  // 员工号码
		Role     string `db:"role"`      // 角色编码（唯一标识，如：admin、user）
	}
)

func newFrUserRolesModel(conn sqlx.SqlConn) *defaultFrUserRolesModel {
	return &defaultFrUserRolesModel{
		conn:  conn,
		table: "`fr_user_roles`",
	}
}

func (m *defaultFrUserRolesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFrUserRolesModel) FindOne(ctx context.Context, id uint64) (*FrUserRoles, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", frUserRolesRows, m.table)
	var resp FrUserRoles
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrUserRolesModel) FindOneByClientIdEmpCodeRole(ctx context.Context, clientId string, empCode string, role string) (*FrUserRoles, error) {
	var resp FrUserRoles
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `emp_code` = ? and `role` = ? limit 1", frUserRolesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, empCode, role)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFrUserRolesModel) Insert(ctx context.Context, data *FrUserRoles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, frUserRolesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.EmpCode, data.Role)
	return ret, err
}

func (m *defaultFrUserRolesModel) Update(ctx context.Context, newData *FrUserRoles) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, frUserRolesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.EmpCode, newData.Role, newData.Id)
	return err
}

func (m *defaultFrUserRolesModel) tableName() string {
	return m.table
}
