// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	invitationFieldNames          = builder.RawFieldNames(&Invitation{})
	invitationRows                = strings.Join(invitationFieldNames, ",")
	invitationRowsExpectAutoSet   = strings.Join(stringx.Remove(invitationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	invitationRowsWithPlaceHolder = strings.Join(stringx.Remove(invitationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	invitationModel interface {
		Insert(ctx context.Context, data *Invitation) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Invitation, error)
		Update(ctx context.Context, data *Invitation) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultInvitationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Invitation struct {
		Id              uint64    `db:"id"`
		OrgId           uint64    `db:"org_id"`
		InviterId       uint64    `db:"inviter_id"`    // 邀请者
		InviteeEmail    string    `db:"invitee_email"` // 被邀请者邮箱
		Role            string    `db:"role"`
		Status          string    `db:"status"`
		InvitationToken string    `db:"invitation_token"`
		CreatedAt       time.Time `db:"created_at"`
		UpdatedAt       time.Time `db:"updated_at"`
		InviteeId       uint64    `db:"invitee_id"` // 被邀请者id
	}
)

func newInvitationModel(conn sqlx.SqlConn) *defaultInvitationModel {
	return &defaultInvitationModel{
		conn:  conn,
		table: "`invitation`",
	}
}

func (m *defaultInvitationModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInvitationModel) FindOne(ctx context.Context, id uint64) (*Invitation, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", invitationRows, m.table)
	var resp Invitation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInvitationModel) Insert(ctx context.Context, data *Invitation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, invitationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrgId, data.InviterId, data.InviteeEmail, data.Role, data.Status, data.InvitationToken, data.InviteeId)
	return ret, err
}

func (m *defaultInvitationModel) Update(ctx context.Context, data *Invitation) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, invitationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrgId, data.InviterId, data.InviteeEmail, data.Role, data.Status, data.InvitationToken, data.InviteeId, data.Id)
	return err
}

func (m *defaultInvitationModel) tableName() string {
	return m.table
}
