// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeUserMasteredFieldNames          = builder.RawFieldNames(&KnowledgeUserMastered{})
	knowledgeUserMasteredRows                = strings.Join(knowledgeUserMasteredFieldNames, ",")
	knowledgeUserMasteredRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeUserMasteredFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeUserMasteredRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeUserMasteredFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeUserMasteredModel interface {
		Insert(ctx context.Context, data *KnowledgeUserMastered) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*KnowledgeUserMastered, error)
		FindOneByUserIdKpId(ctx context.Context, userId uint64, kpId uint64) (*KnowledgeUserMastered, error)
		Update(ctx context.Context, data *KnowledgeUserMastered) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultKnowledgeUserMasteredModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeUserMastered struct {
		Id           uint64    `db:"id"`
		UserId       uint64    `db:"user_id"`
		KpId         uint64    `db:"kp_id"`
		Score        uint64    `db:"score"` // 掌握分数（0-100）
		MasteredTime time.Time `db:"mastered_time"`
	}
)

func newKnowledgeUserMasteredModel(conn sqlx.SqlConn) *defaultKnowledgeUserMasteredModel {
	return &defaultKnowledgeUserMasteredModel{
		conn:  conn,
		table: "`knowledge_user_mastered`",
	}
}

func (m *defaultKnowledgeUserMasteredModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKnowledgeUserMasteredModel) FindOne(ctx context.Context, id uint64) (*KnowledgeUserMastered, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", knowledgeUserMasteredRows, m.table)
	var resp KnowledgeUserMastered
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeUserMasteredModel) FindOneByUserIdKpId(ctx context.Context, userId uint64, kpId uint64) (*KnowledgeUserMastered, error) {
	var resp KnowledgeUserMastered
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `kp_id` = ? limit 1", knowledgeUserMasteredRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, kpId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeUserMasteredModel) Insert(ctx context.Context, data *KnowledgeUserMastered) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, knowledgeUserMasteredRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.KpId, data.Score, data.MasteredTime)
	return ret, err
}

func (m *defaultKnowledgeUserMasteredModel) Update(ctx context.Context, newData *KnowledgeUserMastered) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, knowledgeUserMasteredRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.KpId, newData.Score, newData.MasteredTime, newData.Id)
	return err
}

func (m *defaultKnowledgeUserMasteredModel) tableName() string {
	return m.table
}
