// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeCourseFieldNames          = builder.RawFieldNames(&KnowledgeCourse{})
	knowledgeCourseRows                = strings.Join(knowledgeCourseFieldNames, ",")
	knowledgeCourseRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeCourseFieldNames, "`kc_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeCourseRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeCourseFieldNames, "`kc_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeCourseModel interface {
		Insert(ctx context.Context, data *KnowledgeCourse) (sql.Result, error)
		FindOne(ctx context.Context, kcId uint64) (*KnowledgeCourse, error)
		FindOneByName(ctx context.Context, name string) (*KnowledgeCourse, error)
		Update(ctx context.Context, data *KnowledgeCourse) error
		Delete(ctx context.Context, kcId uint64) error
	}

	defaultKnowledgeCourseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeCourse struct {
		KcId        uint64 `db:"kc_id"`
		Fee         int64  `db:"fee"`
		Name        string `db:"name"`
		Banner      string `db:"banner"` // 头图
		SortOrder   int64  `db:"sort_order"`
		Category    string `db:"category"`
		Level       int64  `db:"level"` // 1=基础, 2=进阶, 3=高阶
		Description string `db:"description"`
		KpTree      string `db:"kp_tree"`
	}
)

func newKnowledgeCourseModel(conn sqlx.SqlConn) *defaultKnowledgeCourseModel {
	return &defaultKnowledgeCourseModel{
		conn:  conn,
		table: "`knowledge_course`",
	}
}

func (m *defaultKnowledgeCourseModel) Delete(ctx context.Context, kcId uint64) error {
	query := fmt.Sprintf("delete from %s where `kc_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, kcId)
	return err
}

func (m *defaultKnowledgeCourseModel) FindOne(ctx context.Context, kcId uint64) (*KnowledgeCourse, error) {
	query := fmt.Sprintf("select %s from %s where `kc_id` = ? limit 1", knowledgeCourseRows, m.table)
	var resp KnowledgeCourse
	err := m.conn.QueryRowCtx(ctx, &resp, query, kcId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeCourseModel) FindOneByName(ctx context.Context, name string) (*KnowledgeCourse, error) {
	var resp KnowledgeCourse
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", knowledgeCourseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeCourseModel) Insert(ctx context.Context, data *KnowledgeCourse) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, knowledgeCourseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Fee, data.Name, data.Banner, data.SortOrder, data.Category, data.Level, data.Description, data.KpTree)
	return ret, err
}

func (m *defaultKnowledgeCourseModel) Update(ctx context.Context, newData *KnowledgeCourse) error {
	query := fmt.Sprintf("update %s set %s where `kc_id` = ?", m.table, knowledgeCourseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Fee, newData.Name, newData.Banner, newData.SortOrder, newData.Category, newData.Level, newData.Description, newData.KpTree, newData.KcId)
	return err
}

func (m *defaultKnowledgeCourseModel) tableName() string {
	return m.table
}
