// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeResourceFieldNames          = builder.RawFieldNames(&KnowledgeResource{})
	knowledgeResourceRows                = strings.Join(knowledgeResourceFieldNames, ",")
	knowledgeResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeResourceFieldNames, "`kr_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgeResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgeResourceFieldNames, "`kr_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgeResourceModel interface {
		Insert(ctx context.Context, data *KnowledgeResource) (sql.Result, error)
		FindOne(ctx context.Context, krId uint64) (*KnowledgeResource, error)
		Update(ctx context.Context, data *KnowledgeResource) error
		Delete(ctx context.Context, krId uint64) error
	}

	defaultKnowledgeResourceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeResource struct {
		KrId       uint64 `db:"kr_id"`
		Type       string `db:"type"` // 视频/习题/讲义
		Name       string `db:"name"`
		Content    string `db:"content"` // 资源内容或链接
		Iframe     string `db:"iframe"`
		Url        string `db:"url"`
		Difficulty int64  `db:"difficulty"` // 1-5级难度
	}
)

func newKnowledgeResourceModel(conn sqlx.SqlConn) *defaultKnowledgeResourceModel {
	return &defaultKnowledgeResourceModel{
		conn:  conn,
		table: "`knowledge_resource`",
	}
}

func (m *defaultKnowledgeResourceModel) Delete(ctx context.Context, krId uint64) error {
	query := fmt.Sprintf("delete from %s where `kr_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, krId)
	return err
}

func (m *defaultKnowledgeResourceModel) FindOne(ctx context.Context, krId uint64) (*KnowledgeResource, error) {
	query := fmt.Sprintf("select %s from %s where `kr_id` = ? limit 1", knowledgeResourceRows, m.table)
	var resp KnowledgeResource
	err := m.conn.QueryRowCtx(ctx, &resp, query, krId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeResourceModel) Insert(ctx context.Context, data *KnowledgeResource) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, knowledgeResourceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Type, data.Name, data.Content, data.Iframe, data.Url, data.Difficulty)
	return ret, err
}

func (m *defaultKnowledgeResourceModel) Update(ctx context.Context, data *KnowledgeResource) error {
	query := fmt.Sprintf("update %s set %s where `kr_id` = ?", m.table, knowledgeResourceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Type, data.Name, data.Content, data.Iframe, data.Url, data.Difficulty, data.KrId)
	return err
}

func (m *defaultKnowledgeResourceModel) tableName() string {
	return m.table
}
