// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgePointFieldNames          = builder.RawFieldNames(&KnowledgePoint{})
	knowledgePointRows                = strings.Join(knowledgePointFieldNames, ",")
	knowledgePointRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgePointFieldNames, "`kp_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	knowledgePointRowsWithPlaceHolder = strings.Join(stringx.Remove(knowledgePointFieldNames, "`kp_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	knowledgePointModel interface {
		Insert(ctx context.Context, data *KnowledgePoint) (sql.Result, error)
		FindOne(ctx context.Context, kpId uint64) (*KnowledgePoint, error)
		FindOneByName(ctx context.Context, name string) (*KnowledgePoint, error)
		Update(ctx context.Context, data *KnowledgePoint) error
		Delete(ctx context.Context, kpId uint64) error
	}

	defaultKnowledgePointModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgePoint struct {
		KpId        uint64    `db:"kp_id"`
		Name        string    `db:"name"`
		Category    string    `db:"category"`
		SubCategory string    `db:"sub_category"` // 子类
		Level       int64     `db:"level"`        // 1=基础, 2=进阶, 3=高阶
		Description string    `db:"description"`
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newKnowledgePointModel(conn sqlx.SqlConn) *defaultKnowledgePointModel {
	return &defaultKnowledgePointModel{
		conn:  conn,
		table: "`knowledge_point`",
	}
}

func (m *defaultKnowledgePointModel) Delete(ctx context.Context, kpId uint64) error {
	query := fmt.Sprintf("delete from %s where `kp_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, kpId)
	return err
}

func (m *defaultKnowledgePointModel) FindOne(ctx context.Context, kpId uint64) (*KnowledgePoint, error) {
	query := fmt.Sprintf("select %s from %s where `kp_id` = ? limit 1", knowledgePointRows, m.table)
	var resp KnowledgePoint
	err := m.conn.QueryRowCtx(ctx, &resp, query, kpId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgePointModel) FindOneByName(ctx context.Context, name string) (*KnowledgePoint, error) {
	var resp KnowledgePoint
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", knowledgePointRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgePointModel) Insert(ctx context.Context, data *KnowledgePoint) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, knowledgePointRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Category, data.SubCategory, data.Level, data.Description)
	return ret, err
}

func (m *defaultKnowledgePointModel) Update(ctx context.Context, newData *KnowledgePoint) error {
	query := fmt.Sprintf("update %s set %s where `kp_id` = ?", m.table, knowledgePointRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Category, newData.SubCategory, newData.Level, newData.Description, newData.KpId)
	return err
}

func (m *defaultKnowledgePointModel) tableName() string {
	return m.table
}
