// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	kpKrFieldNames          = builder.RawFieldNames(&KpKr{})
	kpKrRows                = strings.Join(kpKrFieldNames, ",")
	kpKrRowsExpectAutoSet   = strings.Join(stringx.Remove(kpKrFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	kpKrRowsWithPlaceHolder = strings.Join(stringx.Remove(kpKrFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	kpKrModel interface {
		Insert(ctx context.Context, data *KpKr) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*KpKr, error)
		FindOneByKpIdKrId(ctx context.Context, kpId uint64, krId uint64) (*KpKr, error)
		Update(ctx context.Context, data *KpKr) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultKpKrModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KpKr struct {
		Id   uint64 `db:"id"`
		KpId uint64 `db:"kp_id"`
		KrId uint64 `db:"kr_id"`
	}
)

func newKpKrModel(conn sqlx.SqlConn) *defaultKpKrModel {
	return &defaultKpKrModel{
		conn:  conn,
		table: "`kp_kr`",
	}
}

func (m *defaultKpKrModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKpKrModel) FindOne(ctx context.Context, id uint64) (*KpKr, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", kpKrRows, m.table)
	var resp KpKr
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKpKrModel) FindOneByKpIdKrId(ctx context.Context, kpId uint64, krId uint64) (*KpKr, error) {
	var resp KpKr
	query := fmt.Sprintf("select %s from %s where `kp_id` = ? and `kr_id` = ? limit 1", kpKrRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, kpId, krId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKpKrModel) Insert(ctx context.Context, data *KpKr) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, kpKrRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.KpId, data.KrId)
	return ret, err
}

func (m *defaultKpKrModel) Update(ctx context.Context, newData *KpKr) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, kpKrRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.KpId, newData.KrId, newData.Id)
	return err
}

func (m *defaultKpKrModel) tableName() string {
	return m.table
}
