// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	kpPrerequisiteFieldNames          = builder.RawFieldNames(&KpPrerequisite{})
	kpPrerequisiteRows                = strings.Join(kpPrerequisiteFieldNames, ",")
	kpPrerequisiteRowsExpectAutoSet   = strings.Join(stringx.Remove(kpPrerequisiteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	kpPrerequisiteRowsWithPlaceHolder = strings.Join(stringx.Remove(kpPrerequisiteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	kpPrerequisiteModel interface {
		Insert(ctx context.Context, data *KpPrerequisite) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*KpPrerequisite, error)
		FindOneByParentKpIdChildKpId(ctx context.Context, parentKpId uint64, childKpId uint64) (*KpPrerequisite, error)
		Update(ctx context.Context, data *KpPrerequisite) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultKpPrerequisiteModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KpPrerequisite struct {
		Id         uint64 `db:"id"`
		ParentKpId uint64 `db:"parent_kp_id"`
		ChildKpId  uint64 `db:"child_kp_id"`
	}
)

func newKpPrerequisiteModel(conn sqlx.SqlConn) *defaultKpPrerequisiteModel {
	return &defaultKpPrerequisiteModel{
		conn:  conn,
		table: "`kp_prerequisite`",
	}
}

func (m *defaultKpPrerequisiteModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKpPrerequisiteModel) FindOne(ctx context.Context, id uint64) (*KpPrerequisite, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", kpPrerequisiteRows, m.table)
	var resp KpPrerequisite
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKpPrerequisiteModel) FindOneByParentKpIdChildKpId(ctx context.Context, parentKpId uint64, childKpId uint64) (*KpPrerequisite, error) {
	var resp KpPrerequisite
	query := fmt.Sprintf("select %s from %s where `parent_kp_id` = ? and `child_kp_id` = ? limit 1", kpPrerequisiteRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, parentKpId, childKpId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKpPrerequisiteModel) Insert(ctx context.Context, data *KpPrerequisite) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, kpPrerequisiteRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ParentKpId, data.ChildKpId)
	return ret, err
}

func (m *defaultKpPrerequisiteModel) Update(ctx context.Context, newData *KpPrerequisite) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, kpPrerequisiteRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ParentKpId, newData.ChildKpId, newData.Id)
	return err
}

func (m *defaultKpPrerequisiteModel) tableName() string {
	return m.table
}
