// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	maintainInfoFieldNames          = builder.RawFieldNames(&MaintainInfo{})
	maintainInfoRows                = strings.Join(maintainInfoFieldNames, ",")
	maintainInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(maintainInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	maintainInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(maintainInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	maintainInfoModel interface {
		Insert(ctx context.Context, data *MaintainInfo) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*MaintainInfo, error)
		Update(ctx context.Context, data *MaintainInfo) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMaintainInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MaintainInfo struct {
		Id         uint64         `db:"id"`          // 信息ID
		Type       string         `db:"type"`        // 类型
		Title      string         `db:"title"`       // 标题
		Md5        string         `db:"md5"`         // 信息的md5
		SourceFile string         `db:"source_file"` // 源文件
		UserId     uint64         `db:"user_id"`     // 上传人ID
		Info       sql.NullString `db:"info"`        // 单个信息
		CreatedAt  time.Time      `db:"created_at"`
		UpdatedAt  time.Time      `db:"updated_at"`
	}
)

func newMaintainInfoModel(conn sqlx.SqlConn) *defaultMaintainInfoModel {
	return &defaultMaintainInfoModel{
		conn:  conn,
		table: "`maintain_info`",
	}
}

func (m *defaultMaintainInfoModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMaintainInfoModel) FindOne(ctx context.Context, id uint64) (*MaintainInfo, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", maintainInfoRows, m.table)
	var resp MaintainInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMaintainInfoModel) Insert(ctx context.Context, data *MaintainInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, maintainInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Type, data.Title, data.Md5, data.SourceFile, data.UserId, data.Info)
	return ret, err
}

func (m *defaultMaintainInfoModel) Update(ctx context.Context, data *MaintainInfo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, maintainInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Type, data.Title, data.Md5, data.SourceFile, data.UserId, data.Info, data.Id)
	return err
}

func (m *defaultMaintainInfoModel) tableName() string {
	return m.table
}
