// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	momentCommentLikeFieldNames          = builder.RawFieldNames(&MomentCommentLike{})
	momentCommentLikeRows                = strings.Join(momentCommentLikeFieldNames, ",")
	momentCommentLikeRowsExpectAutoSet   = strings.Join(stringx.Remove(momentCommentLikeFieldNames, "`like_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	momentCommentLikeRowsWithPlaceHolder = strings.Join(stringx.Remove(momentCommentLikeFieldNames, "`like_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	momentCommentLikeModel interface {
		Insert(ctx context.Context, data *MomentCommentLike) (sql.Result, error)
		FindOne(ctx context.Context, likeId int64) (*MomentCommentLike, error)
		FindOneByCommentIdUserId(ctx context.Context, commentId int64, userId int64) (*MomentCommentLike, error)
		Update(ctx context.Context, data *MomentCommentLike) error
		Delete(ctx context.Context, likeId int64) error
	}

	defaultMomentCommentLikeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MomentCommentLike struct {
		LikeId    int64 `db:"like_id"`
		CommentId int64 `db:"comment_id"` // 评论id
		UserId    int64 `db:"user_id"`    // 点赞用户id
	}
)

func newMomentCommentLikeModel(conn sqlx.SqlConn) *defaultMomentCommentLikeModel {
	return &defaultMomentCommentLikeModel{
		conn:  conn,
		table: "`moment_comment_like`",
	}
}

func (m *defaultMomentCommentLikeModel) Delete(ctx context.Context, likeId int64) error {
	query := fmt.Sprintf("delete from %s where `like_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, likeId)
	return err
}

func (m *defaultMomentCommentLikeModel) FindOne(ctx context.Context, likeId int64) (*MomentCommentLike, error) {
	query := fmt.Sprintf("select %s from %s where `like_id` = ? limit 1", momentCommentLikeRows, m.table)
	var resp MomentCommentLike
	err := m.conn.QueryRowCtx(ctx, &resp, query, likeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMomentCommentLikeModel) FindOneByCommentIdUserId(ctx context.Context, commentId int64, userId int64) (*MomentCommentLike, error) {
	var resp MomentCommentLike
	query := fmt.Sprintf("select %s from %s where `comment_id` = ? and `user_id` = ? limit 1", momentCommentLikeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, commentId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMomentCommentLikeModel) Insert(ctx context.Context, data *MomentCommentLike) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, momentCommentLikeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CommentId, data.UserId)
	return ret, err
}

func (m *defaultMomentCommentLikeModel) Update(ctx context.Context, newData *MomentCommentLike) error {
	query := fmt.Sprintf("update %s set %s where `like_id` = ?", m.table, momentCommentLikeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CommentId, newData.UserId, newData.LikeId)
	return err
}

func (m *defaultMomentCommentLikeModel) tableName() string {
	return m.table
}
