// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	momentCommentFieldNames          = builder.RawFieldNames(&MomentComment{})
	momentCommentRows                = strings.Join(momentCommentFieldNames, ",")
	momentCommentRowsExpectAutoSet   = strings.Join(stringx.Remove(momentCommentFieldNames, "`comment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	momentCommentRowsWithPlaceHolder = strings.Join(stringx.Remove(momentCommentFieldNames, "`comment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	momentCommentModel interface {
		Insert(ctx context.Context, data *MomentComment) (sql.Result, error)
		FindOne(ctx context.Context, commentId int64) (*MomentComment, error)
		Update(ctx context.Context, data *MomentComment) error
		Delete(ctx context.Context, commentId int64) error
	}

	defaultMomentCommentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MomentComment struct {
		CommentId int64     `db:"comment_id"`
		MomentId  int64     `db:"moment_id"` // 动态id
		UserId    int64     `db:"user_id"`   // 评论用户id
		Nickname  string    `db:"nickname"`
		Content   string    `db:"content"`    // 评论内容
		ParentId  int64     `db:"parent_id"`  // 被评论人的id
		LikeCount int64     `db:"like_count"` // 回复  1是 0否
		CreatedAt time.Time `db:"created_at"` // 创建时间
		Avatar    string    `db:"avatar"`
		Uuid      string    `db:"uuid"`
	}
)

func newMomentCommentModel(conn sqlx.SqlConn) *defaultMomentCommentModel {
	return &defaultMomentCommentModel{
		conn:  conn,
		table: "`moment_comment`",
	}
}

func (m *defaultMomentCommentModel) Delete(ctx context.Context, commentId int64) error {
	query := fmt.Sprintf("delete from %s where `comment_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, commentId)
	return err
}

func (m *defaultMomentCommentModel) FindOne(ctx context.Context, commentId int64) (*MomentComment, error) {
	query := fmt.Sprintf("select %s from %s where `comment_id` = ? limit 1", momentCommentRows, m.table)
	var resp MomentComment
	err := m.conn.QueryRowCtx(ctx, &resp, query, commentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMomentCommentModel) Insert(ctx context.Context, data *MomentComment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, momentCommentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MomentId, data.UserId, data.Nickname, data.Content, data.ParentId, data.LikeCount, data.Avatar, data.Uuid)
	return ret, err
}

func (m *defaultMomentCommentModel) Update(ctx context.Context, data *MomentComment) error {
	query := fmt.Sprintf("update %s set %s where `comment_id` = ?", m.table, momentCommentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MomentId, data.UserId, data.Nickname, data.Content, data.ParentId, data.LikeCount, data.Avatar, data.Uuid, data.CommentId)
	return err
}

func (m *defaultMomentCommentModel) tableName() string {
	return m.table
}
