// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	playLogFieldNames          = builder.RawFieldNames(&PlayLog{})
	playLogRows                = strings.Join(playLogFieldNames, ",")
	playLogRowsExpectAutoSet   = strings.Join(stringx.Remove(playLogFieldNames, "`play_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	playLogRowsWithPlaceHolder = strings.Join(stringx.Remove(playLogFieldNames, "`play_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	playLogModel interface {
		Insert(ctx context.Context, data *PlayLog) (sql.Result, error)
		FindOne(ctx context.Context, playId uint64) (*PlayLog, error)
		Update(ctx context.Context, data *PlayLog) error
		Delete(ctx context.Context, playId uint64) error
	}

	defaultPlayLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PlayLog struct {
		PlayId    uint64    `db:"play_id"`
		UserId    uint64    `db:"user_id"`
		Username  string    `db:"username"` // 用户姓名
		Songname  string    `db:"songname"` // 歌曲名字
		CreatedAt time.Time `db:"created_at"`
		Pmd5      string    `db:"pmd5"`
	}
)

func newPlayLogModel(conn sqlx.SqlConn) *defaultPlayLogModel {
	return &defaultPlayLogModel{
		conn:  conn,
		table: "`play_log`",
	}
}

func (m *defaultPlayLogModel) Delete(ctx context.Context, playId uint64) error {
	query := fmt.Sprintf("delete from %s where `play_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, playId)
	return err
}

func (m *defaultPlayLogModel) FindOne(ctx context.Context, playId uint64) (*PlayLog, error) {
	query := fmt.Sprintf("select %s from %s where `play_id` = ? limit 1", playLogRows, m.table)
	var resp PlayLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, playId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayLogModel) Insert(ctx context.Context, data *PlayLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, playLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Songname, data.Pmd5)
	return ret, err
}

func (m *defaultPlayLogModel) Update(ctx context.Context, data *PlayLog) error {
	query := fmt.Sprintf("update %s set %s where `play_id` = ?", m.table, playLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Songname, data.Pmd5, data.PlayId)
	return err
}

func (m *defaultPlayLogModel) tableName() string {
	return m.table
}
