// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rawDocumentsFieldNames          = builder.RawFieldNames(&RawDocuments{})
	rawDocumentsRows                = strings.Join(rawDocumentsFieldNames, ",")
	rawDocumentsRowsExpectAutoSet   = strings.Join(stringx.Remove(rawDocumentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rawDocumentsRowsWithPlaceHolder = strings.Join(stringx.Remove(rawDocumentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	rawDocumentsModel interface {
		Insert(ctx context.Context, data *RawDocuments) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RawDocuments, error)
		Update(ctx context.Context, data *RawDocuments) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRawDocumentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RawDocuments struct {
		Id            int64        `db:"id"`            // 主键ID
		ClientId      string       `db:"client_id"`     // 平台id
		DocumentCode  string       `db:"document_code"` // 文档类型编码
		FileMd5       string       `db:"file_md5"`      // 文件MD5
		FileName      string       `db:"file_name"`     // 文件名称
		Tag           string       `db:"tag"`
		Content       string       `db:"content"`
		ContentOrg    string       `db:"content_org"`
		FileList      string       `db:"file_list"`
		FilePath      string       `db:"file_path"`     // 文件存储路径
		FileSize      int64        `db:"file_size"`     // 文件大小
		ZipFileName   string       `db:"zip_file_name"` // 压缩文件名称
		ZipFileSize   int64        `db:"zip_file_size"` // 压缩文件大小
		CreatedAt     time.Time    `db:"created_at"`    // 创建时间
		UpdatedAt     time.Time    `db:"updated_at"`    // 更新时间
		IsAudit       int64        `db:"is_audit"`
		IsToMd        int64        `db:"is_to_md"` // 是否转为MD
		IsToAi        int64        `db:"is_to_ai"` // 是否转为AI
		UploadUser    string       `db:"upload_user"`
		UploadEmpcode string       `db:"upload_empcode"`
		AuditUser     string       `db:"audit_user"`
		AuditedAt     sql.NullTime `db:"audited_at"`
		Status        string       `db:"status"`
		StatusMsg     string       `db:"status_msg"`
	}
)

func newRawDocumentsModel(conn sqlx.SqlConn) *defaultRawDocumentsModel {
	return &defaultRawDocumentsModel{
		conn:  conn,
		table: "`raw_documents`",
	}
}

func (m *defaultRawDocumentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRawDocumentsModel) FindOne(ctx context.Context, id int64) (*RawDocuments, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rawDocumentsRows, m.table)
	var resp RawDocuments
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRawDocumentsModel) Insert(ctx context.Context, data *RawDocuments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, rawDocumentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.DocumentCode, data.FileMd5, data.FileName, data.Tag, data.Content, data.ContentOrg, data.FileList, data.FilePath, data.FileSize, data.ZipFileName, data.ZipFileSize, data.IsAudit, data.IsToMd, data.IsToAi, data.UploadUser, data.UploadEmpcode, data.AuditUser, data.AuditedAt, data.Status, data.StatusMsg)
	return ret, err
}

func (m *defaultRawDocumentsModel) Update(ctx context.Context, data *RawDocuments) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rawDocumentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.DocumentCode, data.FileMd5, data.FileName, data.Tag, data.Content, data.ContentOrg, data.FileList, data.FilePath, data.FileSize, data.ZipFileName, data.ZipFileSize, data.IsAudit, data.IsToMd, data.IsToAi, data.UploadUser, data.UploadEmpcode, data.AuditUser, data.AuditedAt, data.Status, data.StatusMsg, data.Id)
	return err
}

func (m *defaultRawDocumentsModel) tableName() string {
	return m.table
}
