// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	serversInfoFieldNames          = builder.RawFieldNames(&ServersInfo{})
	serversInfoRows                = strings.Join(serversInfoFieldNames, ",")
	serversInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(serversInfoFieldNames, "`server_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	serversInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(serversInfoFieldNames, "`server_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	serversInfoModel interface {
		Insert(ctx context.Context, data *ServersInfo) (sql.Result, error)
		FindOne(ctx context.Context, serverId uint64) (*ServersInfo, error)
		FindOneByServerName(ctx context.Context, serverName string) (*ServersInfo, error)
		Update(ctx context.Context, data *ServersInfo) error
		Delete(ctx context.Context, serverId uint64) error
	}

	defaultServersInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ServersInfo struct {
		ServerId   uint64 `db:"server_id"`
		ServerName string `db:"server_name"` // 服务器名称
		ServerInfo string `db:"server_info"`
	}
)

func newServersInfoModel(conn sqlx.SqlConn) *defaultServersInfoModel {
	return &defaultServersInfoModel{
		conn:  conn,
		table: "`servers_info`",
	}
}

func (m *defaultServersInfoModel) Delete(ctx context.Context, serverId uint64) error {
	query := fmt.Sprintf("delete from %s where `server_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, serverId)
	return err
}

func (m *defaultServersInfoModel) FindOne(ctx context.Context, serverId uint64) (*ServersInfo, error) {
	query := fmt.Sprintf("select %s from %s where `server_id` = ? limit 1", serversInfoRows, m.table)
	var resp ServersInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, serverId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultServersInfoModel) FindOneByServerName(ctx context.Context, serverName string) (*ServersInfo, error) {
	var resp ServersInfo
	query := fmt.Sprintf("select %s from %s where `server_name` = ? limit 1", serversInfoRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, serverName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultServersInfoModel) Insert(ctx context.Context, data *ServersInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, serversInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ServerName, data.ServerInfo)
	return ret, err
}

func (m *defaultServersInfoModel) Update(ctx context.Context, newData *ServersInfo) error {
	query := fmt.Sprintf("update %s set %s where `server_id` = ?", m.table, serversInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ServerName, newData.ServerInfo, newData.ServerId)
	return err
}

func (m *defaultServersInfoModel) tableName() string {
	return m.table
}
