// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	songPm5FieldNames          = builder.RawFieldNames(&SongPm5{})
	songPm5Rows                = strings.Join(songPm5FieldNames, ",")
	songPm5RowsExpectAutoSet   = strings.Join(stringx.Remove(songPm5FieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	songPm5RowsWithPlaceHolder = strings.Join(stringx.Remove(songPm5FieldNames, "`pmd5`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	songPm5Model interface {
		Insert(ctx context.Context, data *SongPm5) (sql.Result, error)
		FindOne(ctx context.Context, pmd5 string) (*SongPm5, error)
		Update(ctx context.Context, data *SongPm5) error
		Delete(ctx context.Context, pmd5 string) error
	}

	defaultSongPm5Model struct {
		conn  sqlx.SqlConn
		table string
	}

	SongPm5 struct {
		Pmd5     string `db:"pmd5"`
		Songname string `db:"songname"` // 歌曲名字
	}
)

func newSongPm5Model(conn sqlx.SqlConn) *defaultSongPm5Model {
	return &defaultSongPm5Model{
		conn:  conn,
		table: "`song_pm5`",
	}
}

func (m *defaultSongPm5Model) Delete(ctx context.Context, pmd5 string) error {
	query := fmt.Sprintf("delete from %s where `pmd5` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, pmd5)
	return err
}

func (m *defaultSongPm5Model) FindOne(ctx context.Context, pmd5 string) (*SongPm5, error) {
	query := fmt.Sprintf("select %s from %s where `pmd5` = ? limit 1", songPm5Rows, m.table)
	var resp SongPm5
	err := m.conn.QueryRowCtx(ctx, &resp, query, pmd5)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSongPm5Model) Insert(ctx context.Context, data *SongPm5) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, songPm5RowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Pmd5, data.Songname)
	return ret, err
}

func (m *defaultSongPm5Model) Update(ctx context.Context, data *SongPm5) error {
	query := fmt.Sprintf("update %s set %s where `pmd5` = ?", m.table, songPm5RowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Songname, data.Pmd5)
	return err
}

func (m *defaultSongPm5Model) tableName() string {
	return m.table
}
