// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userStatsFieldNames          = builder.RawFieldNames(&UserStats{})
	userStatsRows                = strings.Join(userStatsFieldNames, ",")
	userStatsRowsExpectAutoSet   = strings.Join(stringx.Remove(userStatsFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userStatsRowsWithPlaceHolder = strings.Join(stringx.Remove(userStatsFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userStatsModel interface {
		Insert(ctx context.Context, data *UserStats) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*UserStats, error)
		Update(ctx context.Context, data *UserStats) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultUserStatsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserStats struct {
		UserId              uint64    `db:"user_id"`
		MyTestsCount        uint64    `db:"my_tests_count"`
		MyCertsCount        uint64    `db:"my_certs_count"`
		VisitedCount        uint64    `db:"visited_count"`
		VisitedmeCount      uint64    `db:"visitedme_count"`
		LikedCount          uint64    `db:"liked_count"`
		LikedmeCount        uint64    `db:"likedme_count"`
		MutuallikedCount    uint64    `db:"mutualliked_count"`
		CommentCount        uint64    `db:"comment_count"`
		CommentmeCount      uint64    `db:"commentme_count"`
		ListenCount         uint64    `db:"listen_count"`
		MomentsCount        uint64    `db:"moments_count"`
		MomentslikeCount    uint64    `db:"momentslike_count"`
		MomentsthumsupCount uint64    `db:"momentsthumsup_count"`
		ActivedAt           time.Time `db:"actived_at"`
		LoginedAt           time.Time `db:"logined_at"`
	}
)

func newUserStatsModel(conn sqlx.SqlConn) *defaultUserStatsModel {
	return &defaultUserStatsModel{
		conn:  conn,
		table: "`user_stats`",
	}
}

func (m *defaultUserStatsModel) Delete(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultUserStatsModel) FindOne(ctx context.Context, userId uint64) (*UserStats, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userStatsRows, m.table)
	var resp UserStats
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStatsModel) Insert(ctx context.Context, data *UserStats) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userStatsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MyTestsCount, data.MyCertsCount, data.VisitedCount, data.VisitedmeCount, data.LikedCount, data.LikedmeCount, data.MutuallikedCount, data.CommentCount, data.CommentmeCount, data.ListenCount, data.MomentsCount, data.MomentslikeCount, data.MomentsthumsupCount, data.ActivedAt, data.LoginedAt)
	return ret, err
}

func (m *defaultUserStatsModel) Update(ctx context.Context, data *UserStats) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userStatsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MyTestsCount, data.MyCertsCount, data.VisitedCount, data.VisitedmeCount, data.LikedCount, data.LikedmeCount, data.MutuallikedCount, data.CommentCount, data.CommentmeCount, data.ListenCount, data.MomentsCount, data.MomentslikeCount, data.MomentsthumsupCount, data.ActivedAt, data.LoginedAt, data.UserId)
	return err
}

func (m *defaultUserStatsModel) tableName() string {
	return m.table
}
