// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAcquireCourseFieldNames          = builder.RawFieldNames(&UserAcquireCourse{})
	userAcquireCourseRows                = strings.Join(userAcquireCourseFieldNames, ",")
	userAcquireCourseRowsExpectAutoSet   = strings.Join(stringx.Remove(userAcquireCourseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAcquireCourseRowsWithPlaceHolder = strings.Join(stringx.Remove(userAcquireCourseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAcquireCourseModel interface {
		Insert(ctx context.Context, data *UserAcquireCourse) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAcquireCourse, error)
		FindOneByUserIdAcqKcId(ctx context.Context, userId uint64, acqKcId uint64) (*UserAcquireCourse, error)
		Update(ctx context.Context, data *UserAcquireCourse) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAcquireCourseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAcquireCourse struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`   // 用户的id
		Uuid      string    `db:"uuid"`      // 用户的uuid
		AcqKcId   uint64    `db:"acq_kc_id"` // 课程ID
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserAcquireCourseModel(conn sqlx.SqlConn) *defaultUserAcquireCourseModel {
	return &defaultUserAcquireCourseModel{
		conn:  conn,
		table: "`user_acquire_course`",
	}
}

func (m *defaultUserAcquireCourseModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAcquireCourseModel) FindOne(ctx context.Context, id uint64) (*UserAcquireCourse, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAcquireCourseRows, m.table)
	var resp UserAcquireCourse
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAcquireCourseModel) FindOneByUserIdAcqKcId(ctx context.Context, userId uint64, acqKcId uint64) (*UserAcquireCourse, error) {
	var resp UserAcquireCourse
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `acq_kc_id` = ? limit 1", userAcquireCourseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, acqKcId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAcquireCourseModel) Insert(ctx context.Context, data *UserAcquireCourse) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userAcquireCourseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.AcqKcId)
	return ret, err
}

func (m *defaultUserAcquireCourseModel) Update(ctx context.Context, newData *UserAcquireCourse) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAcquireCourseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Uuid, newData.AcqKcId, newData.Id)
	return err
}

func (m *defaultUserAcquireCourseModel) tableName() string {
	return m.table
}
