// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{})
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usersRowsWithPlaceHolder = strings.Join(stringx.Remove(usersFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*Users, error)
		FindOneByUsername(ctx context.Context, username string) (*Users, error)
		FindOneByUuid(ctx context.Context, uuid string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		UserId          uint64    `db:"user_id"`
		Uuid            string    `db:"uuid"`          // 全局唯一ID
		Username        string    `db:"username"`      // 用户姓名
		Nickname        string    `db:"nickname"`      // 昵称
		Email           string    `db:"email"`         // 用户邮箱
		Phone           string    `db:"phone"`         // 电话号码
		PasswordHash    string    `db:"password_hash"` // 用户密码
		CreatedAt       time.Time `db:"created_at"`
		UpdatedAt       time.Time `db:"updated_at"`
		IsDeleted       uint64    `db:"is_deleted"`    // 删除标记
		IsMaster        uint64    `db:"is_master"`     // 主账号
		ShareBalance    uint64    `db:"share_balance"` // 是否共享主账号余额
		AccX            string    `db:"acc_x"`         // twitter account
		AccGoogle       string    `db:"acc_google"`    // google account
		HeadUrl         string    `db:"head_url"`      // 头像
		OpenId          string    `db:"open_id"`       // 微信openid
		UnionId         string    `db:"union_id"`      // 微信 unionid
		SysRole         string    `db:"sys_role"`      // superadmin,admin,user
		IsPhoneVerified uint64    `db:"is_phone_verified"`
		IsEmailVerified uint64    `db:"is_email_verified"`
		Birthday        uint64    `db:"birthday"`
		Age             uint64    `db:"age"`
		Country         string    `db:"country"`
		Province        string    `db:"province"`
		City            string    `db:"city"`
		District        string    `db:"district"`
		Height          uint64    `db:"height"`
		Weight          uint64    `db:"weight"`
		Education       string    `db:"education"`
		Sex             uint64    `db:"sex"`
		Occupation      string    `db:"occupation"`
		Brief           string    `db:"brief"`
		Income          uint64    `db:"income"`
		MaritalStatus   string    `db:"marital_status"`
		HomeTown        string    `db:"home_town"`
		HomeCity        string    `db:"home_city"`
		HomeCountry     string    `db:"home_country"`
		HomeProvince    string    `db:"home_province"`
		HomeDistrict    string    `db:"home_district"`
		Location        string    `db:"location"`
		Religion        string    `db:"religion"`
		Hobbies         string    `db:"hobbies"`
		Tags            string    `db:"tags"`
		Photo           string    `db:"photo"`
		Introduction    string    `db:"introduction"`
		VipLevel        uint64    `db:"vip_level"`
		IsVerified      uint64    `db:"is_verified"` // 是否实名认证
		Ocean           string    `db:"ocean"`
		Science         uint64    `db:"science"`
		HasPhoto        uint64    `db:"has_photo"`
		HomeLat         uint64    `db:"home_lat"`
		HomeLng         uint64    `db:"home_lng"`
		Lat             uint64    `db:"lat"`
		Lng             uint64    `db:"lng"`
		Photos          string    `db:"photos"`
		Avatar          string    `db:"avatar"`
		BoyCount        uint64    `db:"boy_count"` // 儿子数量
		GirlCount       uint64    `db:"girl_count"`
		VipExpiredAt    time.Time `db:"vip_expired_at"`
		LoginedAt       time.Time `db:"logined_at"`
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: "`users`",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, userId uint64) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByUsername(ctx context.Context, username string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByUuid(ctx context.Context, uuid string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where `uuid` = ? limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, uuid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, usersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Username, data.Nickname, data.Email, data.Phone, data.PasswordHash, data.IsDeleted, data.IsMaster, data.ShareBalance, data.AccX, data.AccGoogle, data.HeadUrl, data.OpenId, data.UnionId, data.SysRole, data.IsPhoneVerified, data.IsEmailVerified, data.Birthday, data.Age, data.Country, data.Province, data.City, data.District, data.Height, data.Weight, data.Education, data.Sex, data.Occupation, data.Brief, data.Income, data.MaritalStatus, data.HomeTown, data.HomeCity, data.HomeCountry, data.HomeProvince, data.HomeDistrict, data.Location, data.Religion, data.Hobbies, data.Tags, data.Photo, data.Introduction, data.VipLevel, data.IsVerified, data.Ocean, data.Science, data.HasPhoto, data.HomeLat, data.HomeLng, data.Lat, data.Lng, data.Photos, data.Avatar, data.BoyCount, data.GirlCount, data.VipExpiredAt, data.LoginedAt)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, usersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Uuid, newData.Username, newData.Nickname, newData.Email, newData.Phone, newData.PasswordHash, newData.IsDeleted, newData.IsMaster, newData.ShareBalance, newData.AccX, newData.AccGoogle, newData.HeadUrl, newData.OpenId, newData.UnionId, newData.SysRole, newData.IsPhoneVerified, newData.IsEmailVerified, newData.Birthday, newData.Age, newData.Country, newData.Province, newData.City, newData.District, newData.Height, newData.Weight, newData.Education, newData.Sex, newData.Occupation, newData.Brief, newData.Income, newData.MaritalStatus, newData.HomeTown, newData.HomeCity, newData.HomeCountry, newData.HomeProvince, newData.HomeDistrict, newData.Location, newData.Religion, newData.Hobbies, newData.Tags, newData.Photo, newData.Introduction, newData.VipLevel, newData.IsVerified, newData.Ocean, newData.Science, newData.HasPhoto, newData.HomeLat, newData.HomeLng, newData.Lat, newData.Lng, newData.Photos, newData.Avatar, newData.BoyCount, newData.GirlCount, newData.VipExpiredAt, newData.LoginedAt, newData.UserId)
	return err
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
