// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAuditLogFieldNames          = builder.RawFieldNames(&UserAuditLog{})
	userAuditLogRows                = strings.Join(userAuditLogFieldNames, ",")
	userAuditLogRowsExpectAutoSet   = strings.Join(stringx.Remove(userAuditLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAuditLogRowsWithPlaceHolder = strings.Join(stringx.Remove(userAuditLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAuditLogModel interface {
		Insert(ctx context.Context, data *UserAuditLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserAuditLog, error)
		Update(ctx context.Context, data *UserAuditLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserAuditLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAuditLog struct {
		Id          int64     `db:"id"`            // 主键ID
		KindKey     string    `db:"kind_key"`      // 日志分类KEY
		SourceId    int64     `db:"source_id"`     // 来源ID
		SourceTitle string    `db:"source_title"`  // 来源标题
		UserId      int64     `db:"user_id"`       // 用户ID
		Username    string    `db:"username"`      // 用户名称
		AuditUserId int64     `db:"audit_user_id"` // 审核人ID
		AuditBy     string    `db:"audit_by"`      // 审核人
		AuditType   string    `db:"audit_type"`    // 审核类型：例如初审、复审等，根据具体业务定义
		Result      int64     `db:"result"`        // 审核结果：1-通过（成功），2-拒绝（失败）
		Remark      string    `db:"remark"`        // 审核备注
		CreatedAt   time.Time `db:"created_at"`    // 创建时间
	}
)

func newUserAuditLogModel(conn sqlx.SqlConn) *defaultUserAuditLogModel {
	return &defaultUserAuditLogModel{
		conn:  conn,
		table: "`user_audit_log`",
	}
}

func (m *defaultUserAuditLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAuditLogModel) FindOne(ctx context.Context, id int64) (*UserAuditLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAuditLogRows, m.table)
	var resp UserAuditLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuditLogModel) Insert(ctx context.Context, data *UserAuditLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userAuditLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.KindKey, data.SourceId, data.SourceTitle, data.UserId, data.Username, data.AuditUserId, data.AuditBy, data.AuditType, data.Result, data.Remark)
	return ret, err
}

func (m *defaultUserAuditLogModel) Update(ctx context.Context, data *UserAuditLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAuditLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.KindKey, data.SourceId, data.SourceTitle, data.UserId, data.Username, data.AuditUserId, data.AuditBy, data.AuditType, data.Result, data.Remark, data.Id)
	return err
}

func (m *defaultUserAuditLogModel) tableName() string {
	return m.table
}
