// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFriendsApplyFieldNames          = builder.RawFieldNames(&UserFriendsApply{})
	userFriendsApplyRows                = strings.Join(userFriendsApplyFieldNames, ",")
	userFriendsApplyRowsExpectAutoSet   = strings.Join(stringx.Remove(userFriendsApplyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFriendsApplyRowsWithPlaceHolder = strings.Join(stringx.Remove(userFriendsApplyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userFriendsApplyModel interface {
		Insert(ctx context.Context, data *UserFriendsApply) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserFriendsApply, error)
		FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*UserFriendsApply, error)
		Update(ctx context.Context, data *UserFriendsApply) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserFriendsApplyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserFriendsApply struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`
		FriendId  uint64    `db:"friend_id"` // 被申请的懂友
		Checked   int64     `db:"checked"`   // 1:已查看，0：没查看
		State     int64     `db:"state"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newUserFriendsApplyModel(conn sqlx.SqlConn) *defaultUserFriendsApplyModel {
	return &defaultUserFriendsApplyModel{
		conn:  conn,
		table: "`user_friends_apply`",
	}
}

func (m *defaultUserFriendsApplyModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserFriendsApplyModel) FindOne(ctx context.Context, id uint64) (*UserFriendsApply, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFriendsApplyRows, m.table)
	var resp UserFriendsApply
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendsApplyModel) FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*UserFriendsApply, error) {
	var resp UserFriendsApply
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", userFriendsApplyRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, friendId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendsApplyModel) Insert(ctx context.Context, data *UserFriendsApply) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userFriendsApplyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Checked, data.State)
	return ret, err
}

func (m *defaultUserFriendsApplyModel) Update(ctx context.Context, newData *UserFriendsApply) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFriendsApplyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.Checked, newData.State, newData.Id)
	return err
}

func (m *defaultUserFriendsApplyModel) tableName() string {
	return m.table
}
