// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByEmpIdIsDeleted(ctx context.Context, empId string, isDeleted int64) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id                    int64     `db:"id"`                      // 用户ID
		EmpId                 string    `db:"emp_id"`                  // 工号
		Phone                 string    `db:"phone"`                   // 手机号
		Name                  string    `db:"name"`                    // 姓名
		CompanyId             int64     `db:"company_id"`              // 所属公司ID
		OrgId                 int64     `db:"org_id"`                  // 所属组织ID
		PasswordHash          string    `db:"password_hash"`           // 密码哈希
		LastLoginAt           time.Time `db:"last_login_at"`           // 最后登录时间
		LoginCount            int64     `db:"login_count"`             // 登录次数
		AuditStatus           int64     `db:"audit_status"`            // 审核状态：0-未注册，1-待审核，2-审核通过，3-审核拒绝
		Status                int64     `db:"status"`                  // 状态：0-待审核，1-已通过，2-已拒绝，3-已注销
		AuditUserId           int64     `db:"audit_user_id"`           // 审核人ID
		AuditTime             time.Time `db:"audit_time"`              // 审核时间
		Points                int64     `db:"points"`                  // 积分点
		Type                  int64     `db:"type"`                    // 用户类型：1-普通用户 2-专家用户
		IsDeleted             int64     `db:"is_deleted"`              // 逻辑删除：0-未删除，1-已删除
		CreatedAt             time.Time `db:"created_at"`              // 创建时间
		PasswordResetRequired int64     `db:"password_reset_required"` // 是否强制改密码
		PointsLevel           int64     `db:"points_level"`            // 积分等级：0-白丁，1-青铜，2-白银，3-黄金，4-钻石，5-王者
		Avatar                string    `db:"avatar"`                  // 头像
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByEmpIdIsDeleted(ctx context.Context, empId string, isDeleted int64) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where `emp_id` = ? and `is_deleted` = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, empId, isDeleted)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.EmpId, data.Phone, data.Name, data.CompanyId, data.OrgId, data.PasswordHash, data.LastLoginAt, data.LoginCount, data.AuditStatus, data.Status, data.AuditUserId, data.AuditTime, data.Points, data.Type, data.IsDeleted, data.PasswordResetRequired, data.PointsLevel, data.Avatar)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.EmpId, newData.Phone, newData.Name, newData.CompanyId, newData.OrgId, newData.PasswordHash, newData.LastLoginAt, newData.LoginCount, newData.AuditStatus, newData.Status, newData.AuditUserId, newData.AuditTime, newData.Points, newData.Type, newData.IsDeleted, newData.PasswordResetRequired, newData.PointsLevel, newData.Avatar, newData.Id)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
