// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAcquireUserFieldNames          = builder.RawFieldNames(&UserAcquireUser{})
	userAcquireUserRows                = strings.Join(userAcquireUserFieldNames, ",")
	userAcquireUserRowsExpectAutoSet   = strings.Join(stringx.Remove(userAcquireUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAcquireUserRowsWithPlaceHolder = strings.Join(stringx.Remove(userAcquireUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAcquireUserModel interface {
		Insert(ctx context.Context, data *UserAcquireUser) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAcquireUser, error)
		FindOneByUserIdAcqUserId(ctx context.Context, userId uint64, acqUserId uint64) (*UserAcquireUser, error)
		Update(ctx context.Context, data *UserAcquireUser) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAcquireUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAcquireUser struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`     // 用户的id
		Uuid      string    `db:"uuid"`        // 用户的uuid
		AcqUserId uint64    `db:"acq_user_id"` // 其他用户的id
		AcqUuid   string    `db:"acq_uuid"`    // 其他用户的uuid
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserAcquireUserModel(conn sqlx.SqlConn) *defaultUserAcquireUserModel {
	return &defaultUserAcquireUserModel{
		conn:  conn,
		table: "`user_acquire_user`",
	}
}

func (m *defaultUserAcquireUserModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAcquireUserModel) FindOne(ctx context.Context, id uint64) (*UserAcquireUser, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAcquireUserRows, m.table)
	var resp UserAcquireUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAcquireUserModel) FindOneByUserIdAcqUserId(ctx context.Context, userId uint64, acqUserId uint64) (*UserAcquireUser, error) {
	var resp UserAcquireUser
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `acq_user_id` = ? limit 1", userAcquireUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, acqUserId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAcquireUserModel) Insert(ctx context.Context, data *UserAcquireUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userAcquireUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.AcqUserId, data.AcqUuid)
	return ret, err
}

func (m *defaultUserAcquireUserModel) Update(ctx context.Context, newData *UserAcquireUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAcquireUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Uuid, newData.AcqUserId, newData.AcqUuid, newData.Id)
	return err
}

func (m *defaultUserAcquireUserModel) tableName() string {
	return m.table
}
