// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFriendsFieldNames          = builder.RawFieldNames(&UserFriends{})
	userFriendsRows                = strings.Join(userFriendsFieldNames, ",")
	userFriendsRowsExpectAutoSet   = strings.Join(stringx.Remove(userFriendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFriendsRowsWithPlaceHolder = strings.Join(stringx.Remove(userFriendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userFriendsModel interface {
		Insert(ctx context.Context, data *UserFriends) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserFriends, error)
		FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*UserFriends, error)
		Update(ctx context.Context, data *UserFriends) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserFriendsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserFriends struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`   // 用户的id
		FriendId  uint64    `db:"friend_id"` // 好友的id
		State     int64     `db:"state"`     // 记录的状态
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
		Times     uint64    `db:"times"`      // 我访问对方次数
		ComeTimes uint64    `db:"come_times"` // 对方来的次数
	}
)

func newUserFriendsModel(conn sqlx.SqlConn) *defaultUserFriendsModel {
	return &defaultUserFriendsModel{
		conn:  conn,
		table: "`user_friends`",
	}
}

func (m *defaultUserFriendsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserFriendsModel) FindOne(ctx context.Context, id uint64) (*UserFriends, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFriendsRows, m.table)
	var resp UserFriends
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendsModel) FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*UserFriends, error) {
	var resp UserFriends
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", userFriendsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, friendId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendsModel) Insert(ctx context.Context, data *UserFriends) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userFriendsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.State, data.Times, data.ComeTimes)
	return ret, err
}

func (m *defaultUserFriendsModel) Update(ctx context.Context, newData *UserFriends) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFriendsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.State, newData.Times, newData.ComeTimes, newData.Id)
	return err
}

func (m *defaultUserFriendsModel) tableName() string {
	return m.table
}
