// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAuthIdcardFieldNames          = builder.RawFieldNames(&UserAuthIdcard{})
	userAuthIdcardRows                = strings.Join(userAuthIdcardFieldNames, ",")
	userAuthIdcardRowsExpectAutoSet   = strings.Join(stringx.Remove(userAuthIdcardFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAuthIdcardRowsWithPlaceHolder = strings.Join(stringx.Remove(userAuthIdcardFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAuthIdcardModel interface {
		Insert(ctx context.Context, data *UserAuthIdcard) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAuthIdcard, error)
		Update(ctx context.Context, data *UserAuthIdcard) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAuthIdcardModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAuthIdcard struct {
		Id               uint64         `db:"id"`
		UserId           int64          `db:"user_id"`
		ReqName          string         `db:"req_name"`       // 用户输入姓名
		ReqIdcardNum     string         `db:"req_idcard_num"` // 用户输入身份证号
		ImageFront       string         `db:"image_front"`
		ImageBack        string         `db:"image_back"`
		AuditStatus      int64          `db:"audit_status"` // 1:审核中，2：审核通过，3：审核未通过，0：未上传审核
		FailReason       sql.NullString `db:"fail_reason"`
		State            int64          `db:"state"`
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
		Address          string         `db:"Address"`
		Birthday         string         `db:"birthday"`
		ValidityPeriod   string         `db:"validity_period"`
		Name             string         `db:"name"`              // 身份证姓名
		Gender           int64          `db:"gender"`            // 身份证性别
		IssuingAuthority string         `db:"issuing_authority"` // 发证机关
		Ethnicity        string         `db:"ethnicity"`         // 民族
		IdcardNum        string         `db:"idcard_num"`        // 身份证号
		AuditUserId      uint64         `db:"audit_user_id"`     // 审核人ID
		AuditAt          time.Time      `db:"audit_at"`          // 审核时间
	}
)

func newUserAuthIdcardModel(conn sqlx.SqlConn) *defaultUserAuthIdcardModel {
	return &defaultUserAuthIdcardModel{
		conn:  conn,
		table: "`user_auth_idcard`",
	}
}

func (m *defaultUserAuthIdcardModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAuthIdcardModel) FindOne(ctx context.Context, id uint64) (*UserAuthIdcard, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAuthIdcardRows, m.table)
	var resp UserAuthIdcard
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuthIdcardModel) Insert(ctx context.Context, data *UserAuthIdcard) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userAuthIdcardRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ReqName, data.ReqIdcardNum, data.ImageFront, data.ImageBack, data.AuditStatus, data.FailReason, data.State, data.Address, data.Birthday, data.ValidityPeriod, data.Name, data.Gender, data.IssuingAuthority, data.Ethnicity, data.IdcardNum, data.AuditUserId, data.AuditAt)
	return ret, err
}

func (m *defaultUserAuthIdcardModel) Update(ctx context.Context, data *UserAuthIdcard) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAuthIdcardRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ReqName, data.ReqIdcardNum, data.ImageFront, data.ImageBack, data.AuditStatus, data.FailReason, data.State, data.Address, data.Birthday, data.ValidityPeriod, data.Name, data.Gender, data.IssuingAuthority, data.Ethnicity, data.IdcardNum, data.AuditUserId, data.AuditAt, data.Id)
	return err
}

func (m *defaultUserAuthIdcardModel) tableName() string {
	return m.table
}
