// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAcquireExamFieldNames          = builder.RawFieldNames(&UserAcquireExam{})
	userAcquireExamRows                = strings.Join(userAcquireExamFieldNames, ",")
	userAcquireExamRowsExpectAutoSet   = strings.Join(stringx.Remove(userAcquireExamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAcquireExamRowsWithPlaceHolder = strings.Join(stringx.Remove(userAcquireExamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAcquireExamModel interface {
		Insert(ctx context.Context, data *UserAcquireExam) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAcquireExam, error)
		FindOneByUserIdAcqExamId(ctx context.Context, userId uint64, acqExamId uint64) (*UserAcquireExam, error)
		Update(ctx context.Context, data *UserAcquireExam) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAcquireExamModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAcquireExam struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`     // 用户的id
		Uuid      string    `db:"uuid"`        // 用户的uuid
		AcqExamId uint64    `db:"acq_exam_id"` // 测试的ID
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserAcquireExamModel(conn sqlx.SqlConn) *defaultUserAcquireExamModel {
	return &defaultUserAcquireExamModel{
		conn:  conn,
		table: "`user_acquire_exam`",
	}
}

func (m *defaultUserAcquireExamModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAcquireExamModel) FindOne(ctx context.Context, id uint64) (*UserAcquireExam, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAcquireExamRows, m.table)
	var resp UserAcquireExam
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAcquireExamModel) FindOneByUserIdAcqExamId(ctx context.Context, userId uint64, acqExamId uint64) (*UserAcquireExam, error) {
	var resp UserAcquireExam
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `acq_exam_id` = ? limit 1", userAcquireExamRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, acqExamId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAcquireExamModel) Insert(ctx context.Context, data *UserAcquireExam) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userAcquireExamRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.AcqExamId)
	return ret, err
}

func (m *defaultUserAcquireExamModel) Update(ctx context.Context, newData *UserAcquireExam) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAcquireExamRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Uuid, newData.AcqExamId, newData.Id)
	return err
}

func (m *defaultUserAcquireExamModel) tableName() string {
	return m.table
}
