// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userUploadPhotoFieldNames          = builder.RawFieldNames(&UserUploadPhoto{})
	userUploadPhotoRows                = strings.Join(userUploadPhotoFieldNames, ",")
	userUploadPhotoRowsExpectAutoSet   = strings.Join(stringx.Remove(userUploadPhotoFieldNames, "`photo_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userUploadPhotoRowsWithPlaceHolder = strings.Join(stringx.Remove(userUploadPhotoFieldNames, "`photo_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userUploadPhotoModel interface {
		Insert(ctx context.Context, data *UserUploadPhoto) (sql.Result, error)
		FindOne(ctx context.Context, photoId uint64) (*UserUploadPhoto, error)
		Update(ctx context.Context, data *UserUploadPhoto) error
		Delete(ctx context.Context, photoId uint64) error
	}

	defaultUserUploadPhotoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserUploadPhoto struct {
		PhotoId     uint64    `db:"photo_id"`
		UserId      uint64    `db:"user_id"`
		AuditUserId uint64    `db:"audit_user_id"`
		PhotoUrl    string    `db:"photo_url"` // 图像地址
		IsAudited   int64     `db:"is_audited"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
		AuditedAt   time.Time `db:"audited_at"`
	}
)

func newUserUploadPhotoModel(conn sqlx.SqlConn) *defaultUserUploadPhotoModel {
	return &defaultUserUploadPhotoModel{
		conn:  conn,
		table: "`user_upload_photo`",
	}
}

func (m *defaultUserUploadPhotoModel) Delete(ctx context.Context, photoId uint64) error {
	query := fmt.Sprintf("delete from %s where `photo_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, photoId)
	return err
}

func (m *defaultUserUploadPhotoModel) FindOne(ctx context.Context, photoId uint64) (*UserUploadPhoto, error) {
	query := fmt.Sprintf("select %s from %s where `photo_id` = ? limit 1", userUploadPhotoRows, m.table)
	var resp UserUploadPhoto
	err := m.conn.QueryRowCtx(ctx, &resp, query, photoId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserUploadPhotoModel) Insert(ctx context.Context, data *UserUploadPhoto) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userUploadPhotoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AuditUserId, data.PhotoUrl, data.IsAudited, data.AuditedAt)
	return ret, err
}

func (m *defaultUserUploadPhotoModel) Update(ctx context.Context, data *UserUploadPhoto) error {
	query := fmt.Sprintf("update %s set %s where `photo_id` = ?", m.table, userUploadPhotoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AuditUserId, data.PhotoUrl, data.IsAudited, data.AuditedAt, data.PhotoId)
	return err
}

func (m *defaultUserUploadPhotoModel) tableName() string {
	return m.table
}
