// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersLoginLogFieldNames          = builder.RawFieldNames(&UsersLoginLog{})
	usersLoginLogRows                = strings.Join(usersLoginLogFieldNames, ",")
	usersLoginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(usersLoginLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usersLoginLogRowsWithPlaceHolder = strings.Join(stringx.Remove(usersLoginLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	usersLoginLogModel interface {
		Insert(ctx context.Context, data *UsersLoginLog) (sql.Result, error)
		FindOne(ctx context.Context, logId uint64) (*UsersLoginLog, error)
		Update(ctx context.Context, data *UsersLoginLog) error
		Delete(ctx context.Context, logId uint64) error
	}

	defaultUsersLoginLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UsersLoginLog struct {
		LogId     uint64    `db:"log_id"`
		UserId    uint64    `db:"user_id"`
		Uuid      string    `db:"uuid"` // 全局唯一ID
		Ip        string    `db:"Ip"`
		LoginedAt time.Time `db:"logined_at"`
	}
)

func newUsersLoginLogModel(conn sqlx.SqlConn) *defaultUsersLoginLogModel {
	return &defaultUsersLoginLogModel{
		conn:  conn,
		table: "`users_login_log`",
	}
}

func (m *defaultUsersLoginLogModel) Delete(ctx context.Context, logId uint64) error {
	query := fmt.Sprintf("delete from %s where `log_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, logId)
	return err
}

func (m *defaultUsersLoginLogModel) FindOne(ctx context.Context, logId uint64) (*UsersLoginLog, error) {
	query := fmt.Sprintf("select %s from %s where `log_id` = ? limit 1", usersLoginLogRows, m.table)
	var resp UsersLoginLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, logId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersLoginLogModel) Insert(ctx context.Context, data *UsersLoginLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, usersLoginLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.Ip, data.LoginedAt)
	return ret, err
}

func (m *defaultUsersLoginLogModel) Update(ctx context.Context, data *UsersLoginLog) error {
	query := fmt.Sprintf("update %s set %s where `log_id` = ?", m.table, usersLoginLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Uuid, data.Ip, data.LoginedAt, data.LogId)
	return err
}

func (m *defaultUsersLoginLogModel) tableName() string {
	return m.table
}
