// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBlackListFieldNames          = builder.RawFieldNames(&UserBlackList{})
	userBlackListRows                = strings.Join(userBlackListFieldNames, ",")
	userBlackListRowsExpectAutoSet   = strings.Join(stringx.Remove(userBlackListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userBlackListRowsWithPlaceHolder = strings.Join(stringx.Remove(userBlackListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userBlackListModel interface {
		Insert(ctx context.Context, data *UserBlackList) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserBlackList, error)
		FindOneByUserIdBlackId(ctx context.Context, userId uint64, blackId uint64) (*UserBlackList, error)
		Update(ctx context.Context, data *UserBlackList) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserBlackListModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserBlackList struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`  // 用户的id
		BlackId   uint64    `db:"black_id"` // 其他用户的id
		CreatedAt time.Time `db:"created_at"`
	}
)

func newUserBlackListModel(conn sqlx.SqlConn) *defaultUserBlackListModel {
	return &defaultUserBlackListModel{
		conn:  conn,
		table: "`user_black_list`",
	}
}

func (m *defaultUserBlackListModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserBlackListModel) FindOne(ctx context.Context, id uint64) (*UserBlackList, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBlackListRows, m.table)
	var resp UserBlackList
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBlackListModel) FindOneByUserIdBlackId(ctx context.Context, userId uint64, blackId uint64) (*UserBlackList, error) {
	var resp UserBlackList
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `black_id` = ? limit 1", userBlackListRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, blackId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBlackListModel) Insert(ctx context.Context, data *UserBlackList) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userBlackListRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.BlackId)
	return ret, err
}

func (m *defaultUserBlackListModel) Update(ctx context.Context, newData *UserBlackList) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userBlackListRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.BlackId, newData.Id)
	return err
}

func (m *defaultUserBlackListModel) tableName() string {
	return m.table
}
