// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userVisitorsFieldNames          = builder.RawFieldNames(&UserVisitors{})
	userVisitorsRows                = strings.Join(userVisitorsFieldNames, ",")
	userVisitorsRowsExpectAutoSet   = strings.Join(stringx.Remove(userVisitorsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userVisitorsRowsWithPlaceHolder = strings.Join(stringx.Remove(userVisitorsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userVisitorsModel interface {
		Insert(ctx context.Context, data *UserVisitors) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserVisitors, error)
		FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*UserVisitors, error)
		Update(ctx context.Context, data *UserVisitors) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserVisitorsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserVisitors struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"` // 用户的id
		FriendId  uint64    `db:"friend_id"`
		Times     int64     `db:"times"` // 记录的状态
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
		ComeTimes uint64    `db:"come_times"`
		VisiteAt  time.Time `db:"visite_at"`
	}
)

func newUserVisitorsModel(conn sqlx.SqlConn) *defaultUserVisitorsModel {
	return &defaultUserVisitorsModel{
		conn:  conn,
		table: "`user_visitors`",
	}
}

func (m *defaultUserVisitorsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserVisitorsModel) FindOne(ctx context.Context, id uint64) (*UserVisitors, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userVisitorsRows, m.table)
	var resp UserVisitors
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserVisitorsModel) FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*UserVisitors, error) {
	var resp UserVisitors
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", userVisitorsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, friendId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserVisitorsModel) Insert(ctx context.Context, data *UserVisitors) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userVisitorsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Times, data.ComeTimes, data.VisiteAt)
	return ret, err
}

func (m *defaultUserVisitorsModel) Update(ctx context.Context, newData *UserVisitors) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userVisitorsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.Times, newData.ComeTimes, newData.VisiteAt, newData.Id)
	return err
}

func (m *defaultUserVisitorsModel) tableName() string {
	return m.table
}
