// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AIChatRemoveDocumentRequest struct {
	Filename string `json:"filename"` // 要移除的文件名（与上传时一致）
}

type AIChatUploadDocumentData struct {
	Filename string `json:"filename"` // 上传的文件名
	Message  string `json:"message"`  // 提示信息，如「已识别并缓存，发送消息时将作为参考」
}

type AIChatUploadDocumentRequest struct {
}

type AIChatUploadDocumentResponse struct {
	Response
	Data *AIChatUploadDocumentData `json:"data,optional"`
}

type AIMessage struct {
	Role      string   `json:"role"`
	Content   string   `json:"content"`
	Thinking  string   `json:"thinking,omitempty,optional"`
	CreatedAt int64    `json:"created_at,omitempty"`     // 时间戳
	Files     []string `json:"files,omitempty,optional"` // 参考资料/附件
}

type AIRagDocumentItem struct {
	Source          string  `json:"source"`
	Content         string  `json:"content"`
	FileName        string  `json:"fileName,optional"`
	Path            string  `json:"path,optional"`
	RawDocId        int64   `json:"rawDocId,optional"`
	Page            int     `json:"page,optional"`
	QdrantId        string  `json:"qdrantId,optional"`
	SimilarityScore float64 `json:"similarityScore"`
	RerankScore     float64 `json:"rerankScore,optional"`
}

type AIRagRerankDiag struct {
	UsedRerank    bool   `json:"usedRerank"`
	Error         string `json:"error,optional"`
	RerankTopK    int    `json:"rerankTopK,optional"`
	OriginalCount int    `json:"originalCount,optional"`
	RerankedCount int    `json:"rerankedCount,optional"`
}

type AIRagRetrieveData struct {
	Documents        []AIRagDocumentItem `json:"documents"`
	RawSearchUsed    bool                `json:"rawSearchUsed"`
	VectorSearchUsed bool                `json:"vectorSearchUsed"`
	FullTextMs       int64               `json:"fullTextMs"`
	MainSearchMs     int64               `json:"mainSearchMs"`
	SubSearchMs      int64               `json:"subSearchMs"`
	RerankConfigured bool                `json:"rerankConfigured"`
	SummaryRerank    *AIRagRerankDiag    `json:"summaryRerank,omitempty"`
	ChunkRerank      *AIRagRerankDiag    `json:"chunkRerank,omitempty"`
}

type AIRagRetrieveRequest struct {
	Message      string   `json:"message"`
	DocumentCode string   `json:"documentCode"`
	Tags         []string `json:"tags,omitempty,optional"`
	Skiprag      bool     `json:"skiprag,omitempty,optional"`
}

type AIRagRetrieveResponse struct {
	Response
	Data *AIRagRetrieveData `json:"data,omitempty"`
}

type AISessionChatData struct {
	Session  string `json:"session,omitempty"`
	Response string `json:"response"`
}

type AISessionChatRequest struct {
	Message      string   `json:"message"`
	CategoryId   int64    `json:"categoryId,optional"`
	Keys         string   `json:"keys,omitempty"`
	BusinessId   int64    `json:"businessId,optional"`
	Session      string   `json:"session,omitempty"`
	Think        bool     `json:"think,omitempty"`
	Prompt       string   `json:"prompt,omitempty"`
	Model        string   `json:"model,omitempty"`
	DocumentCode string   `json:"documentCode,optional"`
	Tags         []string `json:"tags,omitempty,optional"`
	Test         bool     `json:"test,omitempty,optional"`
	Skiprag      bool     `json:"skiprag,omitempty,optional"`
}

type AISessionChatResponse struct {
	Response
	Data AISessionChatData `json:"data"`
}

type AdminAduitIdcardRequest struct {
	Id          uint64 `json:"id"`
	AuditStatus int64  `json:"audit_status"`
	FailReason  string `json:"fail_reason"`
}

type AdminChangeFileDocumentTypeRequest struct {
	FileName        string `json:"fileName"`
	OldDocumentCode string `json:"oldDocumentCode"`
	NewDocumentCode string `json:"newDocumentCode"`
}

type AdminClientCreateRequest struct {
	ClientId   string `json:"clientId"`            // 要创建的 clientId
	Name       string `json:"name"`                // client 名称
	Desp       string `json:"desp,optional"`       // 描述
	OwnerEmail string `json:"ownerEmail,optional"` // 负责人邮箱（可选）
}

type AdminClientDeleteRequest struct {
	ClientId string `json:"clientId"` // 要删除的 clientId
}

type AdminClientInfo struct {
	ClientId       string `json:"clientId"`
	Name           string `json:"name"`
	Desp           string `json:"desp,optional"`
	ClientJsonInfo string `json:"clientJsonInfo,optional"` // 便于排查，前端可不展示
	CreatedAt      string `json:"createdAt,optional"`
	UpdatedAt      string `json:"updatedAt,optional"`
}

type AdminClientListData struct {
	List  []AdminClientInfo `json:"list"`
	Total int64             `json:"total"`
}

type AdminClientListRequest struct {
	PageRequest
	ClientId string `json:"clientId,optional"` // 模糊筛选
}

type AdminClientListResponse struct {
	Response
	Data *AdminClientListData `json:"data,omitempty"`
}

type AdminOrderRecordsListRequest struct {
	UserId         uint64 `json:"userId,optional"`
	OrderType      uint   `json:"orderType,optional"`
	BeginCreatedAt uint64 `json:"beginCreatedAt,optional"`
	EndCreatedAt   uint64 `json:"endCreatedAt,optional"`
	OrderNo        string `json:"orderNo,optional"`
	PageRequest
}

type AdminResetPasswordRequest struct {
	EmpCode  string `json:"empCode"`  // 员工编码
	Password string `json:"password"` // 新密码
}

type AdminSetRoleRequest struct {
	EmpCode string `json:"empCode"` // 员工编码
	Role    string `json:"role"`    // 角色
}

type AdminUserBalanceRequest struct {
	UserId uint64 `json:"userId"`
}

type AdminUserBalanceResponse struct {
	Response
	Data *AdminUserBalanceResponseData `json:"data,omitempty"`
}

type AdminUserBalanceResponseData struct {
	UserBalance []UserBalance `json:"userBalance"`
}

type AdminUserDeleteRequest struct {
	UserIds []uint64 `json:"userIds"`
}

type AdminUserListRequest struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	PageRequest
}

type AdminUserListResponse struct {
	Response
	Data AdminUserListResponseData `json:"data,omitempty"`
}

type AdminUserListResponseData struct {
	Users []UserResponseData `json:"users"`
	Total uint64             `json:"total"`
}

type AdminUserUpdateRequest struct {
	UserId    uint64 `json:"userId"`
	Username  string `json:"username,optional"`
	Nickname  string `json:"nickname,optional"`
	Phone     string `json:"phone,optional"`
	Email     string `json:"email,optional"`
	IsDeleted uint64 `json:"isDeleted,optional"`
	SysRole   string `json:"sysRole,optional"`
}

type AiCallStatsQueryData struct {
	TotalCount           int64    `json:"totalCount"`           // 调用总次数
	UserCount            int64    `json:"userCount"`            // 去重用户数
	ModelCount           int64    `json:"modelCount"`           // 模型种类数
	AvgCostMs            float64  `json:"avgCostMs"`            // 平均耗时（毫秒）
	SumQuestionCharCount int64    `json:"sumQuestionCharCount"` // 问题总字数
	SumOutputCharCount   int64    `json:"sumOutputCharCount"`   // 输出总字数
	ModelNames           []string `json:"modelNames"`           // 模型名称列表（可选，便于前端展示）
}

type AiCallStatsQueryRequest struct {
	StartTime string `json:"startTime"` // 开始时间，格式 2006-01-02 或 2006-01-02 15:04:05
	EndTime   string `json:"endTime"`   // 结束时间，格式 2006-01-02 或 2006-01-02 15:04:05
}

type AiCallStatsQueryResponse struct {
	Response
	Data *AiCallStatsQueryData `json:"data,omitempty"`
}

type AiLogFileItem struct {
	Name     string `json:"name"`
	DateTime int64  `json:"datetime"` // 文件修改时间 Unix 时间戳
}

type ApplyResponse struct {
	Code string `json:"code"`
}

type AssignRoleRequest struct {
	UserId uint64 `json:"userId" validate:"required"`
	RoleId uint64 `json:"roleId" validate:"required"`
}

type AsyncTaskItem struct {
	Id            int64  `json:"id"`
	ClientId      string `json:"clientId"`
	TaskType      string `json:"taskType"`
	TaskDesc      string `json:"taskDesc"`
	SourceId      int64  `json:"sourceId"`
	SourceKey     string `json:"sourceKey"`
	ExecuteResult string `json:"executeResult,optional"`
	Status        string `json:"status"`
	CreatedAt     int64  `json:"createdAt"`
	UpdatedAt     int64  `json:"updatedAt"`
}

type AuditRawDocumentsRequest struct {
	Id      int64 `json:"id"`
	IsAudit int64 `json:"isAudit"`
}

type BindEmailRequest struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type BindPhoneRequest struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type BlogAdminCreateRequest struct {
	Title       string `json:"title"`
	Alias       string `json:"alias,optional"` // 别名，唯一
	Summary     string `json:"summary,optional"`
	Content     string `json:"content"`
	Tags        string `json:"tags,optional"`
	Categories  string `json:"categories,optional"`
	Authors     string `json:"authors,optional"`
	Banner      string `json:"banner,optional"`
	IsPublished int64  `json:"isPublished,optional"` // 0/1
}

type BlogAdminDeleteRequest struct {
	Id int64 `json:"id"`
}

type BlogAdminGetRequest struct {
	Id int64 `json:"id"`
}

type BlogAdminListRequest struct {
	PageRequest
	Keyword     string `json:"keyword,optional"`
	IsPublished int64  `json:"isPublished,optional"` // -1=全部,0=未发布,1=已发布
}

type BlogAdminUpdateRequest struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Alias       string `json:"alias,optional"` // 别名，唯一
	Summary     string `json:"summary,optional"`
	Content     string `json:"content"`
	Tags        string `json:"tags,optional"`
	Categories  string `json:"categories,optional"`
	Authors     string `json:"authors,optional"`
	Banner      string `json:"banner,optional"`
	IsPublished int64  `json:"isPublished,optional"` // 0/1
}

type BlogItem struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Alias       string `json:"alias,optional"`
	Summary     string `json:"summary,optional"`
	Content     string `json:"content,optional"`
	Tags        string `json:"tags,optional"`
	Categories  string `json:"categories,optional"`
	Authors     string `json:"authors,optional"`
	Banner      string `json:"banner,optional"`
	IsPublished int64  `json:"isPublished"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type BlogListData struct {
	List  []BlogItem `json:"list"`
	Total int64      `json:"total"`
}

type BlogListPublicRequest struct {
	PageRequest
	Keyword string `json:"keyword,optional"`
}

type BlogListResponse struct {
	Response
	Data *BlogListData `json:"data,omitempty"`
}

type BlogReadRequest struct {
	Slug string `path:"slug"` // alias 或 id
}

type BlogReadResponse struct {
	Response
	Data *BlogItem `json:"data,omitempty"`
}

type CallLLMOneShotData struct {
	Content string `json:"content"` // LLM 回复内容
}

type CallLLMOneShotRequest struct {
	Prompt      string  `json:"prompt"`               // 用户提示词
	Temperature float64 `json:"temperature,optional"` // 温度参数，默认 0.3
	MaxTokens   int64   `json:"maxTokens,optional"`   // 最大 tokens，默认 512
}

type CallLLMOneShotResponse struct {
	Response
	Data *CallLLMOneShotData `json:"data"`
}

type CancelAsyncTaskRequest struct {
	Id int64 `json:"id"` // async_task.id
}

type CancelAuditRawDocumentsRequest struct {
	Id int64 `json:"id"`
}

type CancelConvertDocumentRequest struct {
	Id int64 `json:"id"` // 文档ID
}

type CaptchaResponse struct {
	Response
	Data CaptchaResponseData `json:"data,omitempty"`
}

type CaptchaResponseData struct {
	CaptchaId   string `json:"captchaId"`
	ImageBase64 string `json:"imageBase64"`
}

type ChangeRawDocumentsTagRequest struct {
	Id  int64  `json:"id"`
	Tag string `json:"tag"`
}

type CheckRawDocumentsFileExistsData struct {
	List         []RawDocumentFileStatus `json:"list"`
	Total        int64                   `json:"total"`
	ExistsCount  int64                   `json:"existsCount"`
	MissingCount int64                   `json:"missingCount"`
}

type CheckRawDocumentsFileExistsResponse struct {
	Response
	Data CheckRawDocumentsFileExistsData `json:"data"`
}

type ConvertDocumentToMDData struct {
	Id       int64  `json:"id"`
	FileName string `json:"fileName"`
	Content  string `json:"content"` // Markdown 内容
}

type ConvertDocumentToMDRequest struct {
	Id int64 `json:"id"` // 文档ID
}

type ConvertDocumentToMDResponse struct {
	Response
	Data *ConvertDocumentToMDData `json:"data,omitempty"`
}

type ConvertDocumentToZIPData struct {
	Id           int64    `json:"id"`
	FileName     string   `json:"fileName"`
	ZipFilePath  string   `json:"zipFilePath"`  // ZIP 文件保存路径
	ExtractedDir string   `json:"extractedDir"` // 解压后的目录路径
	FileList     []string `json:"fileList"`     // 解压后的文件列表
}

type ConvertDocumentToZIPResponse struct {
	Response
	Data *ConvertDocumentToZIPData `json:"data,omitempty"`
}

type CreateOrgRequest struct {
	OrgName   string `json:"orgName"`
	IsPrivate uint64 `json:"isPrivate"`
	IsDefault uint64 `json:"isDefault,optional"`
}

type CreateOrgResp struct {
	Response
	Data Organization `json:"data,omitempty"`
}

type CreatePermissionRequest struct {
	Name        string `json:"name" validate:"required"`
	Code        string `json:"code" validate:"required"`
	Description string `json:"description"`
}

type CreateRoleRequest struct {
	Name        string   `json:"name" validate:"required"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions"`
}

type CreateTransactionRecordsRequest struct {
	UserId       uint64 `json:"userId"`
	OrgId        uint64 `json:"orgId"`
	TransType    uint64 `json:"transType"`
	PayType      string `json:"payType"`
	CurrencyCode string `json:"currencyCode"`
	Detail       string `json:"detail"`
	OrderNo      string `json:"orderNo"`
	Amount       int64  `json:"amount"`
	Balance      int64  `json:"balance"`
}

type DeleteAsyncTaskRequest struct {
	Id int64 `json:"id"` // async_task.id
}

type DeleteOrgRequest struct {
	OrgId uint64 `json:"orgId"`
}

type DeletePermissionRequest struct {
	Id uint64 `json:"id"`
}

type DeleteRawDocumentsRequest struct {
	Ids []int64 `json:"ids"`
}

type DeleteRoleRequest struct {
	Id uint64 `json:"id"`
}

type Discount struct {
	DiscountId uint64 `json:"discountId"`         // Discount ID
	OrgId      uint64 `json:"orgId"`              // Organization ID
	IsDeleted  int64  `json:"isDeleted"`          // Soft delete flag
	DeletedAt  uint64 `json:"deletedAt,optional"` // Deletion time
	CreatedAt  uint64 `json:"createdAt"`          // Creation time
	CreatedBy  uint64 `json:"createdBy"`          // Creator ID
	Memo       string `json:"memo,optional"`      // Optional memo
	Name       string `json:"name,optional"`      // Optional name
	Startdate  uint64 `json:"startDate"`          // Discount start date
	Enddate    uint64 `json:"endDate"`            // Discount end date
	Discount   int64  `json:"discount"`           // Discount value (100 means 10.0)
}

type DocumentsRequest struct {
	Code string `json:"code"`
}

type DocumentsType struct {
	Code        string   `json:"code,optional"`
	Name        string   `json:"name"`
	IsDisabled  int64    `json:"isDisabled,optional"`
	Description string   `json:"description"`
	Tags        []string `json:"tags,optional"`
	CreatedAt   int64    `json:"createdAt,optional"`
	UpdatedAt   int64    `json:"updatedAt,optional"`
}

type DocumentsTypeData struct {
	List  []DocumentsType `json:"list"`
	Total int64           `json:"total"`
}

type DownloadRawDocumentsRequest struct {
	Id int64 `path:"id"`
}

type DownloadRequest struct {
	File string `path:"file"`
}

type EmailcodeloginRequest struct {
	ClientId string `json:"clientId"` // 平台id
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type FileApplyRequest struct {
	File string `json:"file"`
}

type FileGetRequest struct {
	File string `path:"file"`
}

type FileItem struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	IsDirectory bool   `json:"isDirectory"`
	Size        int64  `json:"size"`
	CreatedAt   uint64 `json:"createdAt"`
	UpdatedAt   uint64 `json:"updatedAt"`
}

type FileLikeRequest struct {
	File   string `json:"file"`
	Degree int64  `json:"degree"`
}

type FileReadRequest struct {
	File string `json:"file"`
}

type FrPermissionCreateRequest struct {
	Permission  string `json:"permission"`  // 权限编码
	Description string `json:"description"` // 权限描述
}

type FrPermissionDeleteRequest struct {
	Permission string `json:"permission"` // 权限编码
}

type FrPermissionGetRequest struct {
	Permission string `json:"permission"` // 权限编码
}

type FrPermissionGetResponse struct {
	Response
	Data *FrPermissionInfo `json:"data,omitempty"`
}

type FrPermissionInfo struct {
	Permission  string `json:"permission"`  // 权限编码
	Description string `json:"description"` // 权限描述
}

type FrPermissionListData struct {
	List  []FrPermissionInfo `json:"list"`
	Total int64              `json:"total"`
}

type FrPermissionListRequest struct {
	PageRequest
	Permission  string `json:"permission,optional"`  // 权限编码（可选，用于筛选）
	Description string `json:"description,optional"` // 权限描述（可选，用于筛选）
}

type FrPermissionListResponse struct {
	Response
	Data *FrPermissionListData `json:"data,omitempty"`
}

type FrPermissionUpdateRequest struct {
	Permission  string `json:"permission"`  // 权限编码
	Description string `json:"description"` // 权限描述
}

type FrRoleCreateRequest struct {
	Role string `json:"role"` // 角色编码
	Name string `json:"name"` // 角色名称/描述
}

type FrRoleDeleteRequest struct {
	Role string `json:"role"` // 角色编码
}

type FrRoleGetRequest struct {
	Role string `json:"role"` // 角色编码
}

type FrRoleGetResponse struct {
	Response
	Data *FrRoleInfo `json:"data,omitempty"`
}

type FrRoleInfo struct {
	Role string `json:"role"` // 角色编码
	Name string `json:"name"` // 角色名称/描述
}

type FrRoleListData struct {
	List  []FrRoleInfo `json:"list"`
	Total int64        `json:"total"`
}

type FrRoleListRequest struct {
	PageRequest
	Role string `json:"role,optional"` // 角色编码（可选，用于筛选）
	Name string `json:"name,optional"` // 角色名称（可选，用于筛选）
}

type FrRoleListResponse struct {
	Response
	Data *FrRoleListData `json:"data,omitempty"`
}

type FrRolePermissionCreateRequest struct {
	Role       string `json:"role"`       // 角色编码
	Permission string `json:"permission"` // 权限编码
}

type FrRolePermissionDeleteRequest struct {
	Id uint64 `json:"id"` // 关联ID
}

type FrRolePermissionGetRequest struct {
	Id uint64 `json:"id"` // 关联ID
}

type FrRolePermissionGetResponse struct {
	Response
	Data *FrRolePermissionInfo `json:"data,omitempty"`
}

type FrRolePermissionInfo struct {
	Id         uint64 `json:"id"`         // 关联ID
	Role       string `json:"role"`       // 角色编码
	Permission string `json:"permission"` // 权限编码
}

type FrRolePermissionListData struct {
	List  []FrRolePermissionInfo `json:"list"`
	Total int64                  `json:"total"`
}

type FrRolePermissionListRequest struct {
	PageRequest
	Role       string `json:"role,optional"`       // 角色编码（可选，用于筛选）
	Permission string `json:"permission,optional"` // 权限编码（可选，用于筛选）
}

type FrRolePermissionListResponse struct {
	Response
	Data *FrRolePermissionListData `json:"data,omitempty"`
}

type FrRolePermissionUpdateRequest struct {
	Id         uint64 `json:"id"`         // 关联ID
	Role       string `json:"role"`       // 角色编码
	Permission string `json:"permission"` // 权限编码
}

type FrRoleUpdateRequest struct {
	Role string `json:"role"` // 角色编码
	Name string `json:"name"` // 角色名称/描述
}

type FrTagCreateRequest struct {
	Tag string `json:"tag"` // 标签名称
}

type FrTagDeleteRequest struct {
	Tag string `json:"tag"` // 标签名称
}

type FrTagGetRequest struct {
	Tag string `json:"tag"` // 标签名称
}

type FrTagGetResponse struct {
	Response
	Data *FrTagInfo `json:"data,omitempty"`
}

type FrTagInfo struct {
	Tag string `json:"tag"` // 标签名称
}

type FrTagListData struct {
	List  []FrTagInfo `json:"list"`
	Total int64       `json:"total"`
}

type FrTagListRequest struct {
	PageRequest
	Tag string `json:"tag,optional"` // 标签名称（可选，用于筛选）
}

type FrTagListResponse struct {
	Response
	Data *FrTagListData `json:"data,omitempty"`
}

type FrTagUpdateRequest struct {
	OldTag string `json:"oldTag"` // 旧标签名称
	NewTag string `json:"newTag"` // 新标签名称
}

type FrUserRoleCreateRequest struct {
	EmpCode string `json:"empCode"` // 员工编码
	Role    string `json:"role"`    // 角色编码
}

type FrUserRoleDeleteRequest struct {
	Id uint64 `json:"id"` // 关联ID
}

type FrUserRoleGetRequest struct {
	Id uint64 `json:"id"` // 关联ID
}

type FrUserRoleGetResponse struct {
	Response
	Data *FrUserRoleInfo `json:"data,omitempty"`
}

type FrUserRoleInfo struct {
	Id      uint64 `json:"id"`      // 关联ID
	EmpCode string `json:"empCode"` // 员工编码
	Role    string `json:"role"`    // 角色编码
}

type FrUserRoleListData struct {
	List  []FrUserRoleInfo `json:"list"`
	Total int64            `json:"total"`
}

type FrUserRoleListRequest struct {
	PageRequest
	EmpCode string `json:"empCode,optional"` // 员工编码（可选，用于筛选）
	Role    string `json:"role,optional"`    // 角色编码（可选，用于筛选）
}

type FrUserRoleListResponse struct {
	Response
	Data *FrUserRoleListData `json:"data,omitempty"`
}

type FrUserRoleUpdateRequest struct {
	Id      uint64 `json:"id"`      // 关联ID
	EmpCode string `json:"empCode"` // 员工编码
	Role    string `json:"role"`    // 角色编码
}

type GetAIConfigByNameCodeRequest struct {
	Name         string `json:"name"`
	DocumentCode string `json:"documentCode,optional"`
}

type GetAIConfigByNameRequest struct {
	Name         string `path:"name"`
	DocumentCode string `path:"documentCode,optional"`
}

type GetAIConfigByNameResp struct {
	Response
	Data *KnowdataAIConfigInfo `json:"data,omitempty"`
}

type GetAiLogListResponse struct {
	Response
	Data *GetAiLogListResponseData `json:"data,omitempty"`
}

type GetAiLogListResponseData struct {
	List []AiLogFileItem `json:"list"`
}

type GetAiLogResponse struct {
	Response
	Data *GetAiLogResponseData `json:"data,omitempty"`
}

type GetAiLogResponseData struct {
	Content string `json:"content"`
}

type GetAsyncTaskWatermarkData struct {
	Watermark string `json:"watermark"` // Unix 纳秒时间戳字符串；尚无变更记录时为空
}

type GetAsyncTaskWatermarkRequest struct {
}

type GetAsyncTaskWatermarkResponse struct {
	Response
	Data *GetAsyncTaskWatermarkData `json:"data,omitempty"`
}

type GetDifyOptionData struct {
	Name        string `json:"name"`
	Url         string `json:"url"`
	ApiKey      string `json:"apiKey"`
	Description string `json:"description,optional"`
}

type GetDifyOptionListData struct {
	List  []GetDifyOptionData `json:"list"`
	Total int64               `json:"total"`
}

type GetDifyOptionListResponse struct {
	Response
	Data *GetDifyOptionListData `json:"data,omitempty"`
}

type GetDifyOptionReq struct {
	Name string `json:"name,optional"`
}

type GetDifyOptionResponse struct {
	Response
	Data *GetDifyOptionData `json:"data,omitempty"`
}

type GetDistinctTagsData struct {
	Tags []string `json:"tags"`
}

type GetDistinctTagsRequest struct {
	DocumentCode string `json:"documentCode,optional"`
}

type GetDistinctTagsResponse struct {
	Response
	Data GetDistinctTagsData `json:"data"`
}

type GetDocumentsTypeResponse struct {
	Response
	Data *DocumentsType `json:"data"`
}

type GetFilePartialMD5Request struct {
	Path string `json:"path"` // Target file path
}

type GetFilePartialMD5Response struct {
	Response
	MD5 string `json:"md5"`
}

type GetQdrantCollectionListResponse struct {
	Response
	Data *GetQdrantCollectionListResponseData `json:"data,omitempty"`
}

type GetQdrantCollectionListResponseData struct {
	List []string `json:"list"`
}

type GetRawDocQaLlmLogListResponse struct {
	Response
	Data *GetRawDocQaLlmLogListResponseData `json:"data,omitempty"`
}

type GetRawDocQaLlmLogListResponseData struct {
	List []AiLogFileItem `json:"list"`
}

type GetRawDocumentQdrantChunksData struct {
	DocumentId        int64                   `json:"documentId"`
	FileName          string                  `json:"fileName"`
	DocumentCode      string                  `json:"documentCode"`
	IsAudit           int64                   `json:"isAudit"`
	MainCollection    string                  `json:"mainCollection"`
	SummaryCollection string                  `json:"summaryCollection"`
	MainChunks        []RawDocQdrantChunkItem `json:"mainChunks"`
	SummaryChunks     []RawDocQdrantChunkItem `json:"summaryChunks"`
	MainTotal         int64                   `json:"mainTotal"`
	SummaryTotal      int64                   `json:"summaryTotal"`
}

type GetRawDocumentQdrantChunksRequest struct {
	Id int64 `json:"id"`
}

type GetRawDocumentQdrantChunksResponse struct {
	Response
	Data *GetRawDocumentQdrantChunksData `json:"data,omitempty"`
}

type GetRawDocumentsByFilenameRequest struct {
	FileName string `json:"fileName"` // 原始文件名（例如：abc.md）
}

type GetRawDocumentsContentDiffData struct {
	Id         int64  `json:"id"`
	FileName   string `json:"fileName"`
	ContentOrg string `json:"contentOrg"`
	Content    string `json:"content"`
}

type GetRawDocumentsContentDiffRequest struct {
	Id int64 `json:"id"`
}

type GetRawDocumentsContentDiffResponse struct {
	Response
	Data *GetRawDocumentsContentDiffData `json:"data"`
}

type GetRawDocumentsRequest struct {
	Id int64 `json:"id"`
}

type GetRawDocumentsResp struct {
	Response
	Data *RawDocuments `json:"data"`
}

type GetRoleRequest struct {
	Id uint64 `json:"id"`
}

type GetRoleResponse struct {
	Response
	Data GetRoleResponseData `json:"data,omitempty"`
}

type GetRoleResponseData struct {
	Role        Role         `json:"role"`
	Permissions []Permission `json:"permissions"`
}

type GetUsersRoleRequest struct {
	UserId uint64 `json:"userId"`
}

type GetVerifyIdcardData struct {
	Id          uint64 `json:"id"`
	IdcardFront string `json:"idcard_front"`
	IdcardBack  string `json:"idcard_back"`
	Name        string `json:"name"`
	Idcard      string `json:"idcard"`
}

type GetVerifyIdcardListData struct {
	List  []GetVerifyIdcardListDataItem `json:"list"`
	Total int64                         `json:"total"`
}

type GetVerifyIdcardListDataItem struct {
	Id               uint64 `json:"id"`
	UserId           int64  `json:"user_id"`
	ReqName          string `json:"req_name"`
	ReqIdcardNum     string `json:"req_idcard_num"`
	ImageFront       string `json:"image_front"`
	ImageBack        string `json:"image_back"`
	AuditStatus      int64  `json:"audit_status"`
	FailReason       string `json:"fail_reason"`
	State            int64  `json:"state"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
	Address          string `json:"address"`
	Birthday         string `json:"birthday"`
	ValidityPeriod   string `json:"validity_period"`
	Name             string `json:"name"`
	Gender           int64  `json:"gender"`
	IssuingAuthority string `json:"issuing_authority"`
	Ethnicity        string `json:"ethnicity"`
	IdcardNum        string `json:"idcard_num"`
	AuditUserId      uint64 `json:"audit_user_id"`
	AuditAt          int64  `json:"audit_at"`
}

type GetVerifyIdcardListRequest struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetVerifyIdcardListResponse struct {
	Response
	Data *GetVerifyIdcardListData `json:"data"`
}

type GetVerifyIdcardRequest struct {
}

type GetVerifyIdcardResponse struct {
	Response
	Data *GetVerifyIdcardData `json:"data,optional"`
}

type GetpermissionRequest struct {
	Id uint64 `json:"id"`
}

type KnowdataAIConfigInfo struct {
	Id           int64  `json:"id"`           // AI配置ID
	Name         string `json:"name"`         // 值
	DocumentCode string `json:"documentCode"` // 文档代码
	Value        string `json:"value"`        // 名称
	CreatedAt    string `json:"createdAt"`    // 创建时间
	CreatedBy    string `json:"createdBy"`    // 创建人
	UpdatedAt    string `json:"updatedAt"`    // 修改时间
	UpdatedBy    string `json:"updatedBy"`    // 修改人
}

type KnowdataAIConfigListRequest struct {
	PathPageRequest
	Name         string `form:"name,optional"`         // 名称
	DocumentCode string `form:"documentCode,optional"` // 文档类型编码
}

type KnowdataCreateAIConfigRequest struct {
	DocumentCode string `json:"documentCode,optional"`
	Name         string `json:"name"`  // 名称
	Value        string `json:"value"` // 值
}

type KnowdataUpdateAIConfigRequest struct {
	Id           int64  `json:"id"` // AI配置ID
	DocumentCode string `json:"documentCode,optional"`
	Name         string `json:"name"`  // 值
	Value        string `json:"value"` // 名称
}

type HelloRequest struct {
	Name string `path:"name,options=you|me"`
}

type HistoryListResponse struct {
	Response
	Sessions []SessionInfo `json:"sessions"` // 会话列表
}

type HtmlResponse struct {
	ContentType string `header:"Content-Type"` // Set content type header
	Body        string `json:"body"`           // HTML content
}

type IndexRawDocumentToQdrantRequest struct {
	Id             int64  `json:"id"`                      // 原始文档 ID
	CollectionName string `json:"collectionName,optional"` // Qdrant 集合名，空则用配置前缀+DocumentCode
}

type KnowsourceChangePasswordRequest struct {
	EmpCode     string `json:"empCode"`     // 员工编码
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码
}

type KnowsourceContactBindConfirmRequest struct {
	Channel  string `json:"channel"`
	NewEmail string `json:"newEmail,optional"`
	NewPhone string `json:"newPhone,optional"`
	Code     string `json:"code"`
}

type KnowsourceContactBindSendRequest struct {
	Channel  string `json:"channel"` // email | phone
	NewEmail string `json:"newEmail,optional"`
	NewPhone string `json:"newPhone,optional"`
}

type KnowsourceDeptCreateRequest struct {
	DeptCode   string `json:"deptCode"`            // 部门编码
	DeptName   string `json:"deptName"`            // 部门名称
	ParentCode string `json:"parentCode,optional"` // 父部门编码
	GSDM       string `json:"gsdm,optional"`       // 公司代码
	Grade      int64  `json:"grade,optional"`      // 级别
	EndMark    string `json:"endMark,optional"`    // 结束标记
	Kind       string `json:"kind,optional"`       // 类型
	B0110      string `json:"b0110,optional"`      // 备注
}

type KnowsourceDeptDeleteRequest struct {
	DeptCode string `json:"deptCode"`         // 部门编码
	Cascade  uint64 `json:"cascade,optional"` // 1: 删除整棵子树；0/空: 仅删除当前（若有子部门则失败）
}

type KnowsourceDeptDocumentTypeDeleteRequest struct {
	Id int64 `json:"id"` // 关联表主键ID
}

type KnowsourceDeptDocumentTypeInfo struct {
	Id               int64  `json:"id"`
	DeptCode         string `json:"deptCode"`
	DeptName         string `json:"deptName,optional"`
	DocumentTypeCode string `json:"documentTypeCode"`
	DocumentTypeName string `json:"documentTypeName,optional"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
}

type KnowsourceDeptDocumentTypeListData struct {
	List  []KnowsourceDeptDocumentTypeInfo `json:"list"`
	Total int64                            `json:"total"`
}

type KnowsourceDeptDocumentTypeListRequest struct {
	PageRequest
	DeptCode         string `json:"deptCode,optional"`         // 部门编码（可选，用于筛选）
	DocumentTypeCode string `json:"documentTypeCode,optional"` // 文档类型编码（可选，用于筛选）
}

type KnowsourceDeptDocumentTypeListResponse struct {
	Response
	Data *KnowsourceDeptDocumentTypeListData `json:"data,omitempty"`
}

type KnowsourceDeptDocumentTypeRequest struct {
	DeptCode         string `json:"deptCode"`         // 部门编码
	DocumentTypeCode string `json:"documentTypeCode"` // 文档类型编码
}

type KnowsourceDeptListData struct {
	List  []KnowsourceDeptListItem `json:"list"`
	Total int64                    `json:"total"`
}

type KnowsourceDeptListItem struct {
	DeptCode   string `json:"deptCode"`       // 部门编码
	DeptName   string `json:"deptName"`       // 部门名称
	ParentCode string `json:"parentCode"`     // 父部门编码
	GSDM       string `json:"gsdm"`           // 公司代码
	Grade      int64  `json:"grade"`          // 级别
	EndMark    string `json:"endMark"`        // 结束标记
	Kind       string `json:"kind"`           // 类型
	B0110      string `json:"b0110,optional"` // 备注
}

type KnowsourceDeptListRequest struct {
	PageRequest
	DeptCode   string `json:"deptCode,optional"`   // 部门编码（可选，用于筛选）
	DeptName   string `json:"deptName,optional"`   // 部门名称（可选，用于筛选）
	ParentCode string `json:"parentCode,optional"` // 父部门编码（可选，用于筛选）
	Grade      int64  `json:"grade,optional"`      // 级别（可选，用于筛选）
}

type KnowsourceDeptListResponse struct {
	Response
	Data *KnowsourceDeptListData `json:"data,omitempty"`
}

type KnowsourceDeptMoveRequest struct {
	DeptCode      string `json:"deptCode"`               // 要移动的部门编码
	NewParentCode string `json:"newParentCode,optional"` // 新父部门编码；空表示移动为根节点
}

type KnowsourceDeptTreeData struct {
	Tree []KnowsourceDeptTreeNode `json:"tree"`
}

type KnowsourceDeptTreeNode struct {
	DeptCode   string                   `json:"deptCode"`       // 部门编码
	DeptName   string                   `json:"deptName"`       // 部门名称
	ParentCode string                   `json:"parentCode"`     // 父部门编码
	GSDM       string                   `json:"gsdm"`           // 公司代码
	Grade      int64                    `json:"grade"`          // 级别
	EndMark    string                   `json:"endMark"`        // 结束标记
	Kind       string                   `json:"kind"`           // 类型
	B0110      string                   `json:"b0110,optional"` // 备注
	Children   []KnowsourceDeptTreeNode `json:"children"`       // 子部门列表
}

type KnowsourceDeptTreeRequest struct {
	GSDM       string `json:"gsdm,optional"`       // 公司代码（可选，用于筛选）
	ParentCode string `json:"parentCode,optional"` // 父部门编码（可选，用于筛选）
}

type KnowsourceDeptTreeResponse struct {
	Response
	Data *KnowsourceDeptTreeData `json:"data,omitempty"`
}

type KnowsourceDeptUpdateRequest struct {
	DeptCode   string `json:"deptCode"`            // 部门编码（主键）
	DeptName   string `json:"deptName"`            // 部门名称
	ParentCode string `json:"parentCode,optional"` // 父部门编码
	GSDM       string `json:"gsdm,optional"`       // 公司代码
	Grade      int64  `json:"grade,optional"`      // 级别
	EndMark    string `json:"endMark,optional"`    // 结束标记
	Kind       string `json:"kind,optional"`       // 类型
	B0110      string `json:"b0110,optional"`      // 备注
}

type KnowsourceDocPathTreeData struct {
	Tree []KnowsourceDocPathTreeNode `json:"tree"`
}

type KnowsourceDocPathTreeNode struct {
	Name     string                      `json:"name"`     // 文件或目录名称
	Path     string                      `json:"path"`     // 完整路径
	IsDir    bool                        `json:"isDir"`    // 是否为目录
	Size     int64                       `json:"size"`     // 文件大小（目录为0）
	Children []KnowsourceDocPathTreeNode `json:"children"` // 子节点列表
}

type KnowsourceDocPathTreeRequest struct {
	Path string `json:"path,optional"` // 路径（可选，默认为根路径）
}

type KnowsourceDocPathTreeResponse struct {
	Response
	Data *KnowsourceDocPathTreeData `json:"data,omitempty"`
}

type KnowsourceEmpCreateRequest struct {
	EmpCode  string `json:"empCode"`           // 员工编码
	EmpName  string `json:"empName"`           // 员工姓名
	DeptCode string `json:"deptCode"`          // 部门编码
	Position string `json:"position,optional"` // 职位
	Status   int64  `json:"status,optional"`   // 状态（0启用/1禁用），默认0
	Branch   string `json:"branch,optional"`   // 分支
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
}

type KnowsourceEmpDeleteRequest struct {
	EmpCode string `json:"empCode"` // 员工编码
}

type KnowsourceEmpDocumentTypeDeleteRequest struct {
	Id int64 `json:"id"` // 关联表主键ID
}

type KnowsourceEmpDocumentTypeInfo struct {
	Id               int64  `json:"id"`
	EmpCode          string `json:"empCode"`
	EmpName          string `json:"empName,optional"`
	DocumentTypeCode string `json:"documentTypeCode"`
	DocumentTypeName string `json:"documentTypeName,optional"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
}

type KnowsourceEmpDocumentTypeInfoGroup struct {
	EmpCode           string   `json:"empCode"`
	EmpName           string   `json:"empName,optional"`
	DeptCode          string   `json:"deptCode,optional"`
	DeptName          string   `json:"deptName,optional"`
	CompanyName       string   `json:"companyName,optional"` // 员工部门编码前三位对应 fr_dept 的 CONTENT（公司名称）
	DocumentTypeCodes []string `json:"documentTypeCodes"`
	DocumentTypeNames []string `json:"documentTypeNames"`
}

type KnowsourceEmpDocumentTypeListData struct {
	List  []KnowsourceEmpDocumentTypeInfo `json:"list"`
	Total int64                           `json:"total"`
}

type KnowsourceEmpDocumentTypeListGroupData struct {
	List  []KnowsourceEmpDocumentTypeInfoGroup `json:"list"`
	Total int64                                `json:"total"`
}

type KnowsourceEmpDocumentTypeListGroupResponse struct {
	Response
	Data *KnowsourceEmpDocumentTypeListGroupData `json:"data,omitempty"`
}

type KnowsourceEmpDocumentTypeListRequest struct {
	PageRequest
	EmpName string `json:"empName,optional"` // 员工姓名（可选，用于筛选）
	EmpCode string `json:"empCode,optional"` // 员工编码（可选，用于筛选）
}

type KnowsourceEmpDocumentTypeListResponse struct {
	Response
	Data *KnowsourceEmpDocumentTypeListData `json:"data,omitempty"`
}

type KnowsourceEmpDocumentTypeRequest struct {
	EmpCode          string `json:"empCode"`          // 员工编码
	DocumentTypeCode string `json:"documentTypeCode"` // 文档类型编码
}

type KnowsourceEmpInfo struct {
	EmpCode        string   `json:"empCode"`
	EmpName        string   `json:"empName"`
	ClientId       string   `json:"clientId,optional"`   // 企业账户 ID（租户）
	ClientName     string   `json:"clientName,optional"` // 平台名称（来自 client.client_json_info.name）
	ClientDesp     string   `json:"clientDesp,optional"` // 平台描述（来自 client.client_json_info.desp）
	DeptCode       string   `json:"deptCode"`
	DeptName       string   `json:"deptName"`
	Status         int64    `json:"status"`
	Position       string   `json:"position"`
	Mobile         string   `json:"mobile,optional"`
	Email          string   `json:"email,optional"`
	CreatedAt      string   `json:"createdAt,optional"`
	EmpPermissions []string `json:"empPermissions,optional"`
	Roles          []string `json:"roles,optional"`
}

type KnowsourceEmpListData struct {
	List  []KnowsourceEmpListItem `json:"list"`
	Total int64                   `json:"total"`
}

type KnowsourceEmpListItem struct {
	EmpCode  string   `json:"empCode"`           // 员工编码
	EmpName  string   `json:"empName"`           // 员工姓名
	DeptCode string   `json:"deptCode"`          // 部门编码
	DeptName string   `json:"deptName,optional"` // 部门名称
	Position string   `json:"position"`          // 职位
	Status   int64    `json:"status"`            // 状态
	Branch   string   `json:"branch,optional"`   // 分支
	Roles    []string `json:"roles,optional"`    // 角色列表
}

type KnowsourceEmpListRequest struct {
	PageRequest
	EmpCode  string `json:"empCode,optional"`  // 员工编码（可选，用于筛选）
	EmpName  string `json:"empName,optional"`  // 员工姓名（可选，用于筛选）
	DeptCode string `json:"deptCode,optional"` // 部门编码（可选，用于筛选）
	Status   string `json:"status,optional"`   // 状态（可选，用于筛选）
}

type KnowsourceEmpListResponse struct {
	Response
	Data *KnowsourceEmpListData `json:"data,omitempty"`
}

type KnowsourceEmpUpdateRequest struct {
	EmpCode  string `json:"empCode"`           // 员工编码（主键）
	EmpName  string `json:"empName"`           // 员工姓名
	DeptCode string `json:"deptCode"`          // 部门编码
	Position string `json:"position,optional"` // 职位
	Status   int64  `json:"status,optional"`   // 状态（0启用/1禁用）
	Branch   string `json:"branch,optional"`   // 分支
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
}

type KnowsourceLoginData struct {
	Token    string            `json:"token"`
	UserInfo KnowsourceEmpInfo `json:"userInfo"`
}

type KnowsourceLoginRequest struct {
	ClientId  string `json:"clientId"`           // 企业账户名
	EmpCode   string `json:"empCode"`            // 员工编码
	Password  string `json:"password"`           // 密码
	Captcha   string `json:"captcha,optional"`   // 验证码
	CaptchaId string `json:"captchaId,optional"` // 验证码ID
	IsDebug   int64  `json:"isDebug,optional"`   // 是否为调试模式
}

type KnowsourceLoginResponse struct {
	Response
	Data *KnowsourceLoginData `json:"data,omitempty"`
}

type KnowsourceMyDocumentTypeInfo struct {
	DeptName         string `json:"deptName"`
	DocumentTypeCode string `json:"documentTypeCode"`
	DocumentTypeName string `json:"documentTypeName"`
	IsDisabled       int64  `json:"isDisabled,optional"`
	Description      string `json:"description,optional"`
}

type KnowsourceMyDocumentTypeListData struct {
	List  []KnowsourceMyDocumentTypeInfo `json:"list"`
	Total int64                          `json:"total"`
}

type KnowsourceMyDocumentTypeListResponse struct {
	Response
	Data *KnowsourceMyDocumentTypeListData `json:"data,omitempty"`
}

type KnowsourceOALoginRequest struct {
	ClientId string `json:"clientId"` // 企业账户名
	UserId   string `json:"userId"`   // 用户ID
	Code     string `json:"code"`     // 验证码
}

type KnowsourcePasswordResetConfirmRequest struct {
	ClientId    string `json:"clientId"`
	Channel     string `json:"channel"` // email | phone
	Email       string `json:"email,optional"`
	Phone       string `json:"phone,optional"`
	Code        string `json:"code"`
	NewPassword string `json:"newPassword"`
}

type KnowsourcePasswordResetSendCodeRequest struct {
	ClientId string `json:"clientId"`
	Channel  string `json:"channel"` // email | phone
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
}

type KnowsourceTenantRegisterData struct {
	ClientId   string `json:"clientId"`
	Username   string `json:"username"`   // 固定为 superadmin
	NeedVerify bool   `json:"needVerify"` // 是否已发送邮箱验证码，需调用 verify-email
}

type KnowsourceTenantRegisterRequest struct {
	ClientId    string `json:"clientId"`    // 企业账户名（>6 位；仅字母/数字/下划线/横线）
	CompanyName string `json:"companyName"` // 企业名称（显示名）
	OwnerEmail  string `json:"ownerEmail"`  // 邮箱（用于验证与找回）
	OwnerMobile string `json:"ownerMobile"` // 手机号（用于找回/绑定）
	Password    string `json:"password"`    // 密码：>=8 位，且包含大小写字母、数字、符号
	Desp        string `json:"desp,optional"`
}

type KnowsourceTenantRegisterResponse struct {
	Response
	Data *KnowsourceTenantRegisterData `json:"data,omitempty"`
}

type KnowsourceTenantSendVerificationCodeRequest struct {
	ClientId string `json:"clientId"`
}

type KnowsourceTenantVerifyEmailRequest struct {
	ClientId string `json:"clientId"`
	Code     string `json:"code"`
}

type LLMChatModelsData struct {
	ModelIds []string `json:"modelIds"`
}

type LLMChatModelsResponse struct {
	Response
	Data *LLMChatModelsData `json:"data,omitempty"`
}

type LLMServiceTestData struct {
	EmbeddingOk        bool      `json:"embeddingOk"`
	EmbeddingDimension int64     `json:"embeddingDimension"`
	EmbeddingError     string    `json:"embeddingError,optional"`
	RerankOk           bool      `json:"rerankOk"`
	RerankTopScore     float64   `json:"rerankTopScore,optional"`
	RerankScores       []float64 `json:"rerankScores,optional"`
	RerankError        string    `json:"rerankError,optional"`
}

type LLMServiceTestRequest struct {
	Query string `json:"query,optional"`
	Doc1  string `json:"doc1,optional"`
	Doc2  string `json:"doc2,optional"`
}

type LLMServiceTestResponse struct {
	Response
	Data *LLMServiceTestData `json:"data,omitempty"`
}

type LLMSettingData struct {
	MaxTokens                      int64   `json:"maxSize"`
	Model                          string  `json:"model"`
	CompletionUrl                  string  `json:"completionUrl,optional"`
	CompletionApiKey               string  `json:"completionApiKey,optional"`
	CompletionType                 string  `json:"completionType,optional"`
	EmbeddingModel                 string  `json:"embeddingModel,optional"`
	EmbeddingsUrl                  string  `json:"embeddingsUrl,optional"`
	EmbeddingsApiKey               string  `json:"embeddingsApiKey,optional"`
	EmbeddingsType                 string  `json:"embeddingsType,optional"`
	RerankerUrl                    string  `json:"rerankerUrl,optional"`
	RerankerApiKey                 string  `json:"rerankerApiKey,optional"`
	RerankerType                   string  `json:"rerankerType,optional"`
	RerankerModel                  string  `json:"rerankerModel,optional"`
	Temperature                    float64 `json:"temperature"`
	TopK                           int64   `json:"topK"`
	TopP                           float64 `json:"topP"`
	RepeatPenalty                  float64 `json:"repeatPenalty,optional"`
	RagEmbeddingTopK               int64   `json:"ragEmbeddingTopK,optional"`
	RagSimilarityThreshold         float64 `json:"ragSimilarityThreshold,optional"`
	RagSummarySimilarityThreshold  float64 `json:"ragSummarySimilarityThreshold,optional"`
	RagRerankTopK                  int64   `json:"ragRerankTopK,optional"`
	RagRerankScoreThreshold        float64 `json:"ragRerankScoreThreshold,optional"`
	RagSummaryRerankScoreThreshold float64 `json:"ragSummaryRerankScoreThreshold,optional"`
}

type LLMSettingResponse struct {
	Response
	Data *LLMSettingData `json:"data,omitempty"`
}

type ListAsyncTaskData struct {
	List  []AsyncTaskItem `json:"list"`
	Total int64           `json:"total"`
}

type ListAsyncTaskRequest struct {
	TaskType string `json:"taskType,optional"` // 任务类型筛选
	Status   string `json:"status,optional"`   // 空=全部状态；指定则精确匹配 init/running/canceled/success/failed
	PageRequest
}

type ListAsyncTaskResponse struct {
	Response
	Data *ListAsyncTaskData `json:"data,omitempty"`
}

type ListDirectoryRequest struct {
	Path      string `json:"path"`
	IsAllFile int64  `json:"isAllFile,optional"`
	PageRequest
}

type ListDirectoryResponse struct {
	Response
	Data *ListDirectoryResponseData `json:"data,omitempty"`
}

type ListDirectoryResponseData struct {
	Files       []FileItem `json:"files"`
	Total       uint64     `json:"total"`
	CurrentPath string     `json:"currentPath"`
}

type ListDocumentsTypeResponse struct {
	Response
	Data *DocumentsTypeData `json:"data"`
}

type ListOrgRequest struct {
	PageRequest
}

type ListOrgResp struct {
	Response
	Data ListOrgRespData `json:"data,omitempty"`
}

type ListOrgRespData struct {
	Orgs  []Organization `json:"orgs"`
	Total int            `json:"total"`
}

type ListRawDocumentQaPairsData struct {
	List  []RawDocumentQaPairItem `json:"list"`
	Total int64                   `json:"total"`
}

type ListRawDocumentQaPairsRequest struct {
	Id int64 `json:"id"` // raw_documents.id
	PageRequest
}

type ListRawDocumentQaPairsResponse struct {
	Response
	Data *ListRawDocumentQaPairsData `json:"data,omitempty"`
}

type ListRawDocumentsData struct {
	List  []RawDocuments `json:"list"`
	Total int64          `json:"total"`
}

type ListRawDocumentsRequest struct {
	DocumentCode string `json:"documentCode,optional"`
	FileName     string `json:"fileName,optional"`
	Tag          string `json:"tag,optional"`
	IsAudit      string `json:"isAudit,optional"` // 审核状态筛选：1-已审核，0-未审核；空=全部
	PageRequest
}

type ListRawDocumentsResp struct {
	Response
	Data ListRawDocumentsData `json:"data"`
}

type LoginRequest struct {
	ClientId  string `json:"clientId"` // 平台id
	Username  string `json:"username,optional"`
	Email     string `json:"email,optional"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type LoginResponse struct {
	Response
	Data *LoginResponseData `json:"data,omitempty"`
}

type LoginResponseData struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	Uuid         string `json:"uuid"`
	Avatar       string `json:"avatar"`
	Username     string `json:"username"`
	Nickname     string `json:"nickname"`
	SysRole      string `json:"sysRole"`
	Orgs         []Org  `json:"orgs"`
}

type MarkDocumentConvertedRequest struct {
	Authorization        string            `json:"Authorization,optional"`
	RawDocumentFileNames []RawDocumentInfo `json:"rawDocumentFileNames"`
}

type MarkDocumentRagedRequest struct {
	Authorization        string            `json:"Authorization,optional"`
	RawDocumentFileNames []RawDocumentInfo `json:"rawDocumentFileNames"`
}

type MysqlBackupData struct {
	FileName string `json:"fileName"` // 备份 zip 文件名（不含路径），供下载接口使用
}

type MysqlBackupDownloadRequest struct {
	File string `path:"file"`
}

type MysqlBackupResponse struct {
	Response
	Data *MysqlBackupData `json:"data,omitempty"`
}

type NavigateDirectoryRequest struct {
	Path string `json:"path"` // Target directory path
}

type OllamaRequest struct {
	Model    string      `json:"model"`
	Messages []AIMessage `json:"messages"`
	Think    bool        `json:"think"`
	Stream   bool        `json:"stream"`
}

type OllamaResponse struct {
	Model              string    `json:"model"`
	CreatedAt          string    `json:"created_at"`
	CreatedAtUnix      int64     `json:"created_at_unix"`
	Message            AIMessage `json:"message"`
	Thinking           string    `json:"thinking"`
	DoneReason         string    `json:"done_reason"`
	Done               bool      `json:"done"`
	TotalDuration      int64     `json:"total_duration"`
	LoadDuration       int64     `json:"load_duration"`
	PromptEvalCount    int       `json:"prompt_eval_count"`
	PromptEvalDuration int64     `json:"prompt_eval_duration"`
	EvalCount          int       `json:"eval_count"`
	EvalDuration       int64     `json:"eval_duration"`
}

type OrderRecords struct {
	Id            uint64 `json:"id"`
	OrderNo       string `json:"orderNo"`
	InstanceId    uint64 `json:"instanceId"`
	RunningTime   uint64 `json:"runningTime"`
	CreatedAt     uint64 `json:"createdAt"`
	BillingMethod uint64 `json:"billingMethod"`
	OrderAmount   uint64 `json:"orderAmount"`
	Discount      uint64 `json:"discount"`
	ActualAmount  uint64 `json:"actualAmount"`
	UserId        uint64 `json:"userId"`
	OrderType     uint64 `json:"orderType"`
}

type OrderRecordsListRequest struct {
	OrderType      uint   `json:"orderType,optional"`
	BeginCreatedAt uint64 `json:"beginCreatedAt,optional"`
	EndCreatedAt   uint64 `json:"endCreatedAt,optional"`
	OrderNo        string `json:"orderNo,optional"`
	PageRequest
}

type OrderRecordsListResponse struct {
	Response
	Data OrderRecordsListResponseData `json:"data,omitempty"`
}

type OrderRecordsListResponseData struct {
	Orders []OrderRecords `json:"orders"`
	Total  int            `json:"total"`
}

type Org struct {
	OrgId     uint64 `json:"orgId"`
	OrgName   string `json:"orgName"`
	IsPrivate uint64 `json:"isPrivate"`
	Role      string `json:"role"`
}

type Organization struct {
	OrgId     uint64 `json:"orgId"`
	OrgName   string `json:"orgName"`
	CreatedBy uint64 `json:"createdBy"`
	UpdatedAt uint64 `json:"updatedAt"`
	CreatedAt uint64 `json:"createdAt"`
	IsPrivate uint64 `json:"isPrivate"`
	IsDefault uint64 `json:"isDefault"`
	Username  string `json:"username"`
}

type PageFormRequest struct {
	Page     uint64 `form:"page,default=1"`
	PageSize uint64 `form:"pageSize,default=10"`
}

type PageRequest struct {
	Page     uint64 `json:"page,optional"`
	PageSize uint64 `json:"pageSize,optional"`
}

type PageResponse struct {
	Total int64       `json:"total"`
	List  interface{} `json:"list"`
}

type PathIdRequest struct {
	Id int64 `path:"id"`
}

type PathNameRequest struct {
	Name string `path:"name"`
}

type PathPageRequest struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type Permission struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
}

type PermissionListRequest struct {
	Name string `json:"name,optional"`
	Code string `json:"code,optional"`
	PageRequest
}

type PermissionListResponse struct {
	Response
	Data PermissionListResponseData `json:"data,omitempty"`
}

type PermissionListResponseData struct {
	Permissions []Permission `json:"permissions"`
	Total       uint64       `json:"total"`
}

type PermissionResponse struct {
	Response
	Data Permission `json:"data,omitempty"`
}

type PhonecodeloginRequest struct {
	ClientId string `json:"clientId"` // 平台id
	Phonenum string `json:"phonenum"`
	Code     string `json:"code"`
}

type QdrantCollectionFileInfo struct {
	Id           string `json:"id"`
	FileName     string `json:"fileName"`
	DocumentCode string `json:"documentCode"`
	Content      string `json:"content,optional"`
	Metadata     string `json:"metadata,optional"`
	Page         int64  `json:"page"`
	TotalPages   int64  `json:"totalPages"`
	Length       int64  `json:"length"`
}

type QdrantCollectionFileListData struct {
	List  []QdrantCollectionFileInfo `json:"list"`
	Total int64                      `json:"total"`
}

type QdrantCollectionFileListRequest struct {
	Collection string `json:"collection"`
}

type QdrantCollectionFileListResponse struct {
	Response
	Data *QdrantCollectionFileListData `json:"data,omitempty"`
}

type QdrantCollectionListData struct {
	List  []string `json:"list"`
	Total int64    `json:"total"`
}

type QdrantCollectionListRequest struct {
}

type QdrantCollectionListResponse struct {
	Response
	Data *QdrantCollectionListData `json:"data,omitempty"`
}

type RawDocQdrantChunkItem struct {
	QdrantId       string `json:"qdrantId"`
	PageIndex      int64  `json:"pageIndex"`
	TotalPages     int64  `json:"totalPages"`
	Length         int64  `json:"length"`
	Path           string `json:"path,optional"`
	IsSummary      bool   `json:"isSummary"`
	ContentPreview string `json:"contentPreview"`
	Content        string `json:"content"`
}

type RawDocumentFileStatus struct {
	Id           int64  `json:"id"`
	DocumentCode string `json:"documentCode"`
	FileName     string `json:"fileName"`
	FilePath     string `json:"filePath"`
	FileSize     int64  `json:"fileSize"`
	Exists       bool   `json:"exists"`
	ActualPath   string `json:"actualPath,optional"`
	Error        string `json:"error,optional"`
}

type RawDocumentInfo struct {
	ClientId     string `json:"clientId"`
	FileName     string `json:"fileName"`
	DocumentCode string `json:"documentCode"`
	Content      string `json:"content,optional"`
}

type RawDocumentQaPairItem struct {
	Id            int64  `json:"id"`
	ChunkIndex    int64  `json:"chunkIndex"`
	Question      string `json:"question"`
	Answer        string `json:"answer"`
	QdrantPointId string `json:"qdrantPointId,optional"`
	CreatedAt     int64  `json:"createdAt"`
}

type RawDocuments struct {
	Id            int64  `json:"id"`
	DocumentCode  string `json:"documentCode"`
	FileMd5       string `json:"fileMd5"`
	FileName      string `json:"fileName"`
	FilePath      string `json:"filePath"`
	FileSize      int64  `json:"fileSize"`
	Content       string `json:"content,optional"`
	ContentOrg    string `json:"contentOrg,optional"`
	FileList      string `json:"fileList,optional"` // JSON 数组字符串，解压/转换后的文件列表，用于 md-preview 校验图片路径
	Tag           string `json:"tag,optional"`
	ZipFileName   string `json:"zipFileName,optional"`
	ZipFileSize   int64  `json:"zipFileSize,optional"`
	CreatedAt     int64  `json:"createdAt"`
	UpdatedAt     int64  `json:"updatedAt"`
	IsAudit       int64  `json:"isAudit,optional"`
	IsToMd        int64  `json:"isToMd,optional"`
	IsToAi        int64  `json:"isToAi,optional"`
	UploadUser    string `json:"uploadUser,optional"`
	UploadEmpcode string `json:"uploadEmpcode,optional"`
	AuditUser     string `json:"auditUser,optional"`
	AuditedAt     int64  `json:"auditedAt,optional"`
	Status        string `json:"status,optional"`
	StatusMsg     string `json:"statusMsg,optional"`
}

type RawDocumentsMarkdownNormalizePreviewData struct {
	OriginalContent  string `json:"originalContent"`  // 规范化前的正文（与库中 content 一致）
	FormattedContent string `json:"formattedContent"` // LLM 返回的规范化 Markdown
}

type RawDocumentsMarkdownNormalizePreviewRequest struct {
	Id      int64  `json:"id"`
	Content string `json:"content,optional"` // 若传入非空则以此作为待规范化的正文（如编辑区未保存）；否则使用库中 content
}

type RawDocumentsMarkdownNormalizePreviewResponse struct {
	Response
	Data *RawDocumentsMarkdownNormalizePreviewData `json:"data"`
}

type RegenerateAllSummariesData struct {
	Total        int `json:"total"`        // 总文档数
	Processed    int `json:"processed"`    // 已处理文档数
	SuccessCount int `json:"successCount"` // 成功处理数
	FailureCount int `json:"failureCount"` // 失败处理数
}

type RegenerateAllSummariesRequest struct {
	DocumentCode string  `json:"documentCode,optional"` // 可选，指定文档类型代码，不指定则处理所有类型
	FileIds      []int64 `json:"fileIds,optional"`      // 可选，指定要处理的文件ID列表，不指定则处理所有已审核文件
}

type RegenerateAllSummariesResponse struct {
	Response
	Data *RegenerateAllSummariesData `json:"data,omitempty"`
}

type RegisterRequest struct {
	Username  string `json:"username"`
	Nickname  string `json:"nickname,optional"`
	Email     string `json:"email"`
	Phone     string `json:"phone,optional"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type RegisterResponse struct {
	Response
	Data RegisterResponseData `json:"data,omitempty"`
}

type RegisterResponseData struct {
	UserId   uint64 `json:"userId"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Orgs     []Org  `json:"orgs"`
}

type ResendEmailRequest struct {
	Email string `json:"email"`
}

type Response struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Info    string `json:"info,omitempty"`
}

type RestPassRequest struct {
	NewPassword string `json:"newPassword"`
}

type RevokeRoleRequest struct {
	UserId uint64 `json:"userId"`
	RoleId uint64 `json:"roleId"`
}

type Role struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type RoleListRequest struct {
	Name string `json:"name,optional"`
	PageRequest
}

type RoleListResponse struct {
	Response
	Data RoleListResponseData `json:"data,omitempty"`
}

type RoleListResponseData struct {
	Roles []Role `json:"roles"`
	Total uint64 `json:"total"`
}

type RoleResponse struct {
	Response
	Data Role `json:"data,omitempty"`
}

type SearchFilesRequest struct {
	Query string `json:"query"`         // Search term
	Path  string `json:"path,optional"` // Optional: limit search to specific directory
	PageRequest
}

type SearchFilesResponse struct {
	Response
	Data *SearchFilesResponseData `json:"data,omitempty"`
}

type SearchFilesResponseData struct {
	Files []FileItem `json:"files"`
	Total uint64     `json:"total"`
}

type SearchRawDocVectorsData struct {
	Query          string                         `json:"query"`
	List           []SearchRawDocVectorsItem      `json:"list"`
	Total          int                            `json:"total"`
	SearchTime     float64                        `json:"searchTime"`
	TopK           int                            `json:"topK"`
	CollectionName string                         `json:"collectionName"`
	RerankInfo     *SearchRawDocVectorsRerankInfo `json:"rerankInfo,omitempty"`
}

type SearchRawDocVectorsItem struct {
	Id              int                    `json:"id"`       // 序号
	QdrantId        string                 `json:"qdrantId"` // Qdrant 点 ID
	Path            string                 `json:"path,optional"`
	Content         string                 `json:"content"`
	SimilarityScore float64                `json:"similarityScore"`
	RerankScore     float64                `json:"rerankScore,optional"`
	Metadata        map[string]interface{} `json:"metadata,optional"`
}

type SearchRawDocVectorsRequest struct {
	Query                string    `json:"query"`
	TopK                 int       `json:"topK,optional"`                 // 默认 10，向量检索条数
	UseRerank            bool      `json:"useRerank,optional"`            // 是否使用 vLLM 重排
	RerankTopK           int       `json:"rerankTopK,optional"`           // 重排后保留条数，0 则用 TopK
	SimilarityThreshold  float64   `json:"similarityThreshold,optional"`  // 相似度底线，低于则过滤，0 表示不过滤
	RerankScoreThreshold float64   `json:"rerankScoreThreshold,optional"` // 重排分值底线，低于则过滤，0 表示不过滤
	Instruction          string    `json:"instruction,optional"`          // 重排指令（可选）
	CollectionName       string    `json:"collectionName"`                // 必填，Qdrant 集合名
	Tags                 []string  `json:"tags,optional"`                 // 过滤 tag，OR 逻辑
	FileNames            []string  `json:"fileNames,optional"`            // 过滤文件名，OR 逻辑
	QueryVector          []float32 `json:"queryVectors,optional"`
}

type SearchRawDocVectorsRerankInfo struct {
	UsedRerank    bool   `json:"usedRerank"`
	RerankTopK    int    `json:"rerankTopK,optional"`
	OriginalCount int    `json:"originalCount,optional"`
	RerankedCount int    `json:"rerankedCount,optional"`
	Error         string `json:"error,optional"`
}

type SearchRawDocVectorsResponse struct {
	Response
	Data *SearchRawDocVectorsData `json:"data,omitempty"`
}

type SearchRawDocumentsData struct {
	List  []SearchRawDocumentsItem `json:"list"`
	Total int64                    `json:"total"`
}

type SearchRawDocumentsItem struct {
	Id           int64  `json:"id"`
	DocumentCode string `json:"documentCode"`
	FileName     string `json:"fileName"`
	Tag          string `json:"tag,optional"`
	Snippet      string `json:"snippet,optional"` // 命中片段（用于列表预览）
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	IsAudit      int64  `json:"isAudit,optional"`
	IsToMd       int64  `json:"isToMd,optional"`
	IsToAi       int64  `json:"isToAi,optional"`
	Status       string `json:"status,optional"`
	StatusMsg    string `json:"statusMsg,optional"` // 异步失败原因或补充说明
}

type SearchRawDocumentsRequest struct {
	Keyword      string `json:"keyword"` // 全文检索关键字
	DocumentCode string `json:"documentCode,optional"`
	Tag          string `json:"tag,optional"`
	IsAudit      string `json:"isAudit,optional"` // 审核状态筛选：1-已审核，0-未审核；空=全部
	PageRequest
}

type SearchRawDocumentsResp struct {
	Response
	Data SearchRawDocumentsData `json:"data"`
}

type SendemailcodeRequest struct {
	Email     string `json:"email"`
	Type      string `json:"type,optional"` //register
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type SendphonecodeRequest struct {
	Phonenum  string `json:"phonenum"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type Server struct {
	ServerId uint64 `json:"serverId,optional"`
	ServerBaseField
}

type ServerBaseField struct {
	RegionId         uint64 `json:"regionId"`
	ServerName       string `json:"serverName"`
	Supplier         uint64 `json:"supplier"`
	GpuModel         string `json:"gpuModel"`
	GpuMem           uint64 `json:"gpuMem"`
	GpuCount         uint64 `json:"gpuCount"`
	GpuUsed          int64  `json:"gpuUsed"` // 已使用GPU数量
	CpuModel         string `json:"cpuModel"`
	CpuFrequency     int64  `json:"cpuFrequency"`
	CpuCores         uint64 `json:"cpuCores"`
	CpuCount         uint64 `json:"cpuCount"`
	Memory           uint64 `json:"memory"`
	SystemDisk       uint64 `json:"systemDisk,optional"`
	DataDisk         uint64 `json:"dataDisk,optional"`
	MaxDataDisk      uint64 `json:"maxDataDisk,optional"`
	SpeedDesc        string `json:"speedDesc,optional"`
	GpuDriver        string `json:"gpuDriver,optional"`
	CudaVersion      string `json:"cudaVersion,optional"`
	OsName           string `json:"osName,optional"`
	OsVersion        string `json:"osVersion,optional"`
	KernelVersion    string `json:"kernelVersion,optional"`
	DockerVersion    string `json:"dockerVersion,optional"`
	NvidiaDocker     int64  `json:"nvidiaDocker,optional"`
	NetworkDownSpeed int64  `json:"networkDownSpeed,optional"`
	NetworkUpSpeed   int64  `json:"networkUpSpeed,optional"`
	AgentVersion     string `json:"agentVersion,optional"`
	PayPrices        string `json:"payPrices,optional"`
	Available        uint64 `json:"available"`
	Total            uint64 `json:"total"`
	ExpireDate       uint64 `json:"expireDate"`
	ThreadCount      uint64 `json:"threadCount"`
	IsOnline         int64  `json:"isOnline,optional"`
	IsPayMin         int64  `json:"isPayMin,optional"`
	IsPayDaily       int64  `json:"isPayDaily,optional"`
	IsPayMonthly     int64  `json:"isPayMonthly,optional"`
	IsPayYearly      int64  `json:"isPayYearly,optional"`
	IsDeleted        int64  `json:"isDeleted,optional"`
	PerGpuMemory     uint64 `json:"perGpuMemory,optional"`
	PerGpuDisksize   uint64 `json:"perGpuDisksize,optional"`
	PerGpuCpuCore    uint64 `json:"perGpuCpuCore,optional"`
	FcbUrl           string `json:"fcbUrl,optional"`
}

type ServerListDataResp struct {
	Servers   []Server `json:"servers"`
	PageIndex int      `json:"pageIndex"`
	PageSize  int      `json:"pageSize"`
	Offset    int      `json:"offset"`
	MaxPage   int      `json:"maxPage"`
	Total     int      `json:"total"`
	Page      int      `json:"page"`
}

type ServerListRequest struct {
	RegionId     int      `json:"regionId,optional"`
	TagId        int      `json:"tagId,optional"`
	IsPayMin     int      `json:"isPayMin,optional"`
	IsPayDaily   int      `json:"isPayDaily,optional"`
	IsPayMonthly int      `json:"isPayMonthly,optional"`
	IsPayYearly  int      `json:"isPayYearly,optional"`
	GpuModel     []string `json:"gpuModel,optional"`
	GpuCount     int      `json:"gpuCount,optional"`
	GpuMem       int      `json:"gpuMem,optional"`
	CpuModel     []string `json:"cpuModel,optional"`
	CpuCores     int      `json:"cpuCores,optional"`
	Supplier     int      `json:"supplier,optional"`
	PageRequest
}

type ServerListResponse struct {
	Response
	Data *ServerListDataResp `json:"data,omitempty"`
}

type Servers struct {
	ServerId         uint64 `json:"serverId"`
	ServerName       string `json:"serverName"`
	IsOnline         int64  `json:"isOnline"`
	BillingMethod    uint64 `json:"billingMethod"` // 计费方式
	RegionId         uint64 `json:"regionId"`      // 地区
	IsPayMin         int64  `json:"isPayMin"`
	IsPayDaily       int64  `json:"isPayDaily"`
	IsPayMonthly     int64  `json:"isPayMonthly"`
	IsPayYearly      int64  `json:"isPayYearly"`
	PayPrices        string `json:"payPrices"`
	DiskPayPrices    string `json:"diskPayPrices"`
	Supplier         uint64 `json:"supplier"`         // 供应商
	GpuModel         uint64 `json:"gpuModel"`         // GPU型号
	GpuCount         uint64 `json:"gpuCount"`         // GPU数量
	GpuUsed          int64  `json:"gpuUsed"`          // 已使用GPU数量
	GpuMem           uint64 `json:"gpuMem"`           // 显存
	CpuModel         uint64 `json:"cpuModel"`         // CPU型号
	CpuCores         uint64 `json:"cpuCores"`         // CPU核数
	CpuFrequency     int64  `json:"cpuFrequency"`     // cpu频率
	ThreadCount      uint64 `json:"threadCount"`      // 处理器线程数量
	Memory           uint64 `json:"memory"`           // 内存(GB)
	SystemDisk       uint64 `json:"systemDisk"`       // 系统盘(GB)
	DataDisk         uint64 `json:"dataDisk"`         // 数据盘(GB)
	MaxDataDisk      uint64 `json:"maxDataDisk"`      // 最大数据盘(GB)
	SpeedDesc        string `json:"speedDesc"`        // 运算速度
	OsName           string `json:"osName"`           // 操作系统名称
	OsVersion        string `json:"osVersion"`        // 操作系统版本号
	KernelVersion    string `json:"kernelVersion"`    // 内核版本
	GpuDriver        string `json:"gpuDriver"`        // GPU驱动
	CudaVersion      string `json:"cudaVersion"`      // cuda版本
	DockerVersion    string `json:"dockerVersion"`    // Docker版本号
	NvidiaDocker     int64  `json:"nvidiaDocker"`     // 是否支持nvidia-docker
	NetworkDownSpeed int64  `json:"networkDownSpeed"` // 网络下载速度
	NetworkUpSpeed   int64  `json:"networkUpSpeed"`   // 网络上传速度
	AgentVersion     string `json:"agentVersion"`     // 代理版本号
	Cost             uint64 `json:"cost"`             // 费用
	Available        uint64 `json:"available"`        // 空闲数量
	Total            uint64 `json:"total"`            // 可用总量
	ExpireDate       uint64 `json:"expireDate"`       // 到期时间
	RegionName       string `json:"regionName"`       // 地区
	RegionCode       string `json:"regionCode"`
	Tags             []Tag  `json:"tags"`
}

type SessionBatchDeleteRequest struct {
	Sessions []string `json:"sessions"` // 必传，会话ID列表
}

type SessionDeleteRequest struct {
	Session string `json:"session"` // 必传，会话ID
}

type SessionDetailRequest struct {
	Session string `json:"session"` // 必传，会话ID
}

type SessionDetailResponse struct {
	Response
	Messages []AIMessage `json:"messages"` // 消息列表（按时间排序）
}

type SessionInfo struct {
	Session          string `json:"session"`          // 会话ID
	CategoryId       int64  `json:"categoryId"`       // 分类ID
	Keys             string `json:"keys"`             // 关键词
	EmpCode          string `json:"empCode"`          // 员工编码
	DocumentTypeCode string `json:"documentTypeCode"` // 文档类型编码
	Title            string `json:"title"`            // 会话标题
	Tags             string `json:"tags"`
	LastQuery        string `json:"lastQuery"`  // 最后一条提问
	LastReply        string `json:"lastReply"`  // 最后一条回复
	UpdateTime       int64  `json:"updateTime"` // 最后更新时间
}

type SysCheckData struct {
	Vllmchat      SysCheckItem `json:"vllmchat"`
	Vllmembedding SysCheckItem `json:"vllmembedding"`
	Vllmreranker  SysCheckItem `json:"vllmreranker"`
	Qdrant        SysCheckItem `json:"qdrant"`
	Redis         SysCheckItem `json:"redis"`
	Mysql         SysCheckItem `json:"mysql"`
	Mineru        SysCheckItem `json:"mineru"`
	Mail          SysCheckItem `json:"mail"`
}

type SysCheckItem struct {
	Ok       bool     `json:"ok"`                // 是否可访问
	Value    string   `json:"value"`             // 配置值/地址（脱敏可选）
	Message  string   `json:"message"`           // 错误信息或 ok 时的说明
	ModelIds []string `json:"modelIds,optional"` // vLLM /v1/models 返回的 model id 列表（仅 vllm* 服务有值）
	Type     string   `json:"type,optional"`     // 服务类型：ollama 或 vllm（仅 completion 类服务有值）
	Version  string   `json:"version,optional"`  // 版本号（如 0.1，仅支持 /api/version 或 /version 的服务有值）
}

type SysCheckResponse struct {
	Response
	Data *SysCheckData `json:"data,omitempty"`
}

type SystemStatsData struct {
	EmpCount      int64 `json:"empCount"`      // 员工总数
	DeptCount     int64 `json:"deptCount"`     // 部门总数
	DocumentCount int64 `json:"documentCount"` // 知识库总数
	SessionCount  int64 `json:"sessionCount"`  // AI 会话数
}

type SystemStatsResponse struct {
	Response
	Data *SystemStatsData `json:"data,omitempty"`
}

type Tag struct {
	TagID   uint64 `json:"tagId"`
	TagName string `json:"tagName"`
}

type TextConsistencyData struct {
	Consistent bool `json:"consistent"` // true=一致(yes)，false=不一致(no)
}

type TextConsistencyRequest struct {
	Prompt string `json:"prompt"`
	Text1  string `json:"text1"`
	Text2  string `json:"text2"`
}

type TextConsistencyResponse struct {
	Response
	Data TextConsistencyData `json:"data"`
}

type TransactionRecords struct {
	Id           uint64 `json:"id"`
	UserId       uint64 `json:"userId"`
	OrgId        uint64 `json:"orgId"`
	CreatedAt    uint64 `json:"createdAt"`
	TransType    uint64 `json:"transType"`
	PayType      string `json:"payType"`
	CurrencyCode string `json:"currencyCode"`
	Detail       string `json:"detail"`
	OrderNo      string `json:"orderNo"`
	Username     string `json:"username"`
	Amount       int64  `json:"amount"`
	Balance      int64  `json:"balance"`
}

type TransactionRecordsListRequest struct {
	OrgId          uint64 `json:"orgId,optional"`
	TransType      uint64 `json:"transType,optional"`
	CurrencyCode   string `json:"currencyCode,optional"`
	BeginCreatedAt uint64 `json:"beginCreatedAt,optional"`
	EndCreatedAt   uint64 `json:"endCreatedAt,optional"`
	OrderNo        string `json:"orderNo,optional"`
	PageRequest
}

type TransactionRecordsListResponse struct {
	Response
	Data TransactionRecordsListResponseData `json:"data,omitempty"`
}

type TransactionRecordsListResponseData struct {
	Trans []TransactionRecords `json:"trans"`
	Total int                  `json:"total"`
}

type UpdateOrgRequest struct {
	OrgId     uint64 `json:"orgId"`
	OrgName   string `json:"orgName"`
	IsPrivate uint64 `json:"isPrivate"`
	IsDefault uint64 `json:"isDefault"`
}

type UpdatePermissionRequest struct {
	Id          uint64 `json:"id" validate:"required"`
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description,optional"`
}

type UpdateRawDocumentsContentRequest struct {
	Id      int64  `json:"id"`
	Content string `json:"content"`
}

type UpdateRoleRequest struct {
	Id          uint64   `json:"id" validate:"required"`
	Name        string   `json:"name,optional"`
	Description string   `json:"description,optional"`
	Permissions []string `json:"permissions,optional"` // Permission IDs
}

type UpdateUserInfoRequest struct {
	Username        string `json:"username,optional"`
	Email           string `json:"email,optional"`
	Phone           string `json:"phone,optional"`
	Nickname        string `json:"nickname,optional"`
	IsPhoneVerified int64  `json:"isPhoneVerified,optional"`
	IsEmailVerified int64  `json:"isEmailVerified,optional"`
}

type UploadRawDocumentsRequest struct {
	FileName     string `form:"fileName"`
	FileType     string `form:"fileType"`
	DocumentCode string `form:"documentCode"`
	Tag          string `form:"tag,optional"`
}

type UploadResponse struct {
	Response
	Filename string `json:"filename"`
}

type UserBalance struct {
	OrgId        uint64 `json:"orgId"`
	OrgName      string `json:"orgName"`
	CurrencyCode string `json:"currencyCode"`
	Balance      int64  `json:"balance"`
}

type UserBalanceResponse struct {
	Response
	Data []UserBalance `json:"data,omitempty"`
}

type UserResponse struct {
	Response
	Data UserResponseData `json:"data,omitempty"`
}

type UserResponseData struct {
	UserId          uint64 `json:"userId"`
	Username        string `json:"username"`
	Nickname        string `json:"nickname"`
	Phone           string `json:"phone"`
	Email           string `json:"email"`
	HeadUrl         string `json:"headUrl"`
	SysRole         string `json:"sysRole"`
	IsDeleted       int64  `json:"isDeleted"`
	CreatedAt       uint64 `json:"createdAt"`
	Orgs            []Org  `json:"orgs,omitempty"`
	IsPhoneVerified int64  `json:"isPhoneVerified"`
	IsEmailVerified int64  `json:"isEmailVerified"`
	Uuid            string `json:"uuid"`
	Avatar          string `json:"avatar"`
	LoginedAt       uint64 `json:"loginedAt"`
}

type UserRolesResponse struct {
	Response
	Data UserRolesResponseData `json:"data,omitempty"`
}

type UserRolesResponseData struct {
	Roles []Role `json:"roles"`
}

type VLLMChoice struct {
	Index        int       `json:"index"`
	Message      AIMessage `json:"message"`
	FinishReason string    `json:"finish_reason"`
}

type VLLMRequest struct {
	Model            string      `json:"model"`
	Messages         []AIMessage `json:"messages"`
	Temperature      float64     `json:"temperature,omitempty"`
	MaxTokens        int         `json:"max_tokens,omitempty"`
	Stream           bool        `json:"stream,omitempty"`
	TopP             float64     `json:"top_p,omitempty"`
	TopK             int         `json:"top_k,omitempty"`
	Stop             []string    `json:"stop,omitempty"`
	PresencePenalty  float64     `json:"presence_penalty,omitempty"`
	FrequencyPenalty float64     `json:"frequency_penalty,omitempty"`
}

type VLLMResponse struct {
	ID      string       `json:"id"`
	Object  string       `json:"object"`
	Created int64        `json:"created"`
	Model   string       `json:"model"`
	Choices []VLLMChoice `json:"choices"`
	Usage   VLLMUsage    `json:"usage"`
}

type VLLMUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

type VerifyEmailRequest struct {
	Email string `path:"email"`
	Code  string `path:"code"`
}

type VerifyRequest struct {
	IdcardFront string `json:"idcard_front"`
	IdcardBack  string `json:"idcard_back"`
	Name        string `json:"name"`
	Idcard      string `json:"idcard"`
}
