// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"
	"time"

	admin "knowsource/api/internal/handler/admin"
	ai "knowsource/api/internal/handler/ai"
	files "knowsource/api/internal/handler/files"
	knowdata "knowsource/api/internal/handler/knowdata"
	knowsource "knowsource/api/internal/handler/knowsource"
	mysql "knowsource/api/internal/handler/mysql"
	page "knowsource/api/internal/handler/page"
	"knowsource/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/sendemailcode",
				Handler: SendemailcodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sys/hello/:name",
				Handler: HelloHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sys/info",
				Handler: InfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sys/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/captcha",
				Handler: CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/emailcodelogin",
				Handler: EmailcodeloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/phonecodelogin",
				Handler: PhonecodeloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/resend/email",
				Handler: ResendEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sendphonecode",
				Handler: SendphonecodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/verify/email/:email/:code",
				Handler: VerifyEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/instance/charge/deleted",
					Handler: AdminInstanceChargeDeletedHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/orders/list",
					Handler: AdminListOrderRecordsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/server/list",
					Handler: AdminServerListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/user/balance",
					Handler: AdminUserBalanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/user/delete",
					Handler: AdminUserDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/user/list",
					Handler: AdminUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/user/update",
					Handler: AdminUserUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders/list",
					Handler: ListOrderRecordsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/transactions/list",
					Handler: ListTransactionRecordsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/balance",
					Handler: GetUserBalanceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/bemember",
					Handler: BeMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/bind/email",
					Handler: BindEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/bind/phone",
					Handler: BindPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: UserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/info/update",
					Handler: UpdateUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/keepalive",
					Handler: KeepAliveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/keeplogin",
					Handler: KeepLoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/resetpass",
					Handler: ResetPassHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: UserUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/permission/create",
					Handler: CreatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permission/delete",
					Handler: DeletePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permission/list",
					Handler: ListPermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permission/read",
					Handler: GetPermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permission/update",
					Handler: UpdatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/create",
					Handler: CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/delete",
					Handler: DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/list",
					Handler: ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/read",
					Handler: GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/update",
					Handler: UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/role/assign",
					Handler: AssignRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/role/revoke",
					Handler: RevokeRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/roles",
					Handler: GetUserRolesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/file/static/:file",
				Handler: DownloadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/idcard/verify",
					Handler: VerifyIdcardHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/idcard/verify/get",
					Handler: GetVerifyIdcardHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/idcard/back",
					Handler: UploadIdcardBackHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/idcard/front",
					Handler: UploadIdcardFrontHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/idcard/audit",
					Handler: admin.AdminAduitIdcardHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/idcard/verify/list",
					Handler: admin.GetVerifyIdcardListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 管理员删除ailog.txt
					Method:  http.MethodGet,
					Path:    "/admin/ailog/delete/:name",
					Handler: ai.DeleteAiLogHandler(serverCtx),
				},
				{
					// 管理员获取ailog.txt
					Method:  http.MethodGet,
					Path:    "/admin/ailog/get/:name",
					Handler: ai.GetAiLogHandler(serverCtx),
				},
				{
					// 管理员获取ailog.txt list
					Method:  http.MethodGet,
					Path:    "/admin/ailog/list",
					Handler: ai.GetAiLogListHandler(serverCtx),
				},
				{
					// 超级管理员获取Qdrant集合列表
					Method:  http.MethodGet,
					Path:    "/admin/qdrant/collection/list",
					Handler: ai.GetQdrantCollectionListHandler(serverCtx),
				},
				{
					// 管理员删除问答抽取LLM日志
					Method:  http.MethodGet,
					Path:    "/admin/rawdoc/qa-llm-log/delete/:name",
					Handler: ai.DeleteRawDocQaLlmLogHandler(serverCtx),
				},
				{
					// 管理员获取问答抽取LLM日志内容
					Method:  http.MethodGet,
					Path:    "/admin/rawdoc/qa-llm-log/get/:name",
					Handler: ai.GetRawDocQaLlmLogHandler(serverCtx),
				},
				{
					// 管理员获取问答抽取LLM日志列表
					Method:  http.MethodGet,
					Path:    "/admin/rawdoc/qa-llm-log/list",
					Handler: ai.GetRawDocQaLlmLogListHandler(serverCtx),
				},
				{
					// AI聊天
					Method:  http.MethodPost,
					Path:    "/ai/chat",
					Handler: ai.AIChatHandler(serverCtx),
				},
				{
					// 批量删除历史会话
					Method:  http.MethodPost,
					Path:    "/ai/chat/history/batch-delete",
					Handler: ai.HistoryBatchDeleteHandler(serverCtx),
				},
				{
					// 删除历史会话
					Method:  http.MethodPost,
					Path:    "/ai/chat/history/delete",
					Handler: ai.HistoryDeleteHandler(serverCtx),
				},
				{
					// 历史会话详情
					Method:  http.MethodPost,
					Path:    "/ai/chat/history/detail",
					Handler: ai.SessionDetailHandler(serverCtx),
				},
				{
					// 历史会话列表
					Method:  http.MethodPost,
					Path:    "/ai/chat/history/list",
					Handler: ai.HistoryListHandler(serverCtx),
				},
				{
					// AI对话上传临时文档（txt/docx/pdf），识别内容并写入对话缓存，发下一条消息时作为参考并清除缓存
					Method:  http.MethodPost,
					Path:    "/ai/chat/upload-document",
					Handler: ai.AIChatUploadDocumentHandler(serverCtx),
				},
				{
					// AI对话删除已上传的临时文档（按文件名从缓存移除）
					Method:  http.MethodPost,
					Path:    "/ai/chat/upload-document/remove",
					Handler: ai.AIChatRemoveDocumentHandler(serverCtx),
				},
				{
					// RAG 检索预览（不走聊天模型）
					Method:  http.MethodPost,
					Path:    "/ai/rag/retrieve",
					Handler: ai.AIRagRetrieveHandler(serverCtx),
				},
				{
					// 会话聊天
					Method:  http.MethodPost,
					Path:    "/ai/session/chat",
					Handler: ai.AISessionChatHandler(serverCtx),
				},
				{
					// 会话聊天选项
					Method:  http.MethodOptions,
					Path:    "/ai/session/chat",
					Handler: ai.AISessionChatOptionsHandler(serverCtx),
				},
				{
					// 判断两段文字主要内容是否一致（调用 LLM），供测试脚本使用
					Method:  http.MethodPost,
					Path:    "/ai/text/consistency",
					Handler: ai.TextConsistencyHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
		rest.WithTimeout(300000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(120000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/directory/list",
					Handler: files.ListDirectoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/directory/navigate",
					Handler: files.NavigateDirectoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files/apply",
					Handler: files.FileApplyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files/like",
					Handler: files.FileLikeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files/partialmd5",
					Handler: files.GetFilePartialMD5Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files/read",
					Handler: files.FileReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files/search",
					Handler: files.SearchFilesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建文档类型
					Method:  http.MethodPost,
					Path:    "/documents/type/create",
					Handler: knowdata.CreateDocumentsTypeHandler(serverCtx),
				},
				{
					// 删除文档类型
					Method:  http.MethodPost,
					Path:    "/documents/type/delete",
					Handler: knowdata.DeleteDocumentsTypeHandler(serverCtx),
				},
				{
					// 获取文档类型详情
					Method:  http.MethodPost,
					Path:    "/documents/type/get",
					Handler: knowdata.GetDocumentsTypeHandler(serverCtx),
				},
				{
					// 获取文档类型列表
					Method:  http.MethodPost,
					Path:    "/documents/type/list",
					Handler: knowdata.ListDocumentsTypeHandler(serverCtx),
				},
				{
					// 更新文档类型
					Method:  http.MethodPost,
					Path:    "/documents/type/update",
					Handler: knowdata.UpdateDocumentsTypeHandler(serverCtx),
				},
				{
					// 审核原始文档。IsAudit=1 时审核通过，后台协程会异步调用 index-to-qdrant 写入向量；IsAudit=0 时取消审核，会按文件名称删除 Qdrant 中该文档的向量并更新审核标志为 0
					Method:  http.MethodPost,
					Path:    "/raw-documents/audit",
					Handler: knowdata.AuditRawDocumentsHandler(serverCtx),
				},
				{
					// 取消正在进行的审核入库任务
					Method:  http.MethodPost,
					Path:    "/raw-documents/audit/cancel",
					Handler: knowdata.CancelAuditRawDocumentsHandler(serverCtx),
				},
				{
					// 检查所有原始文档文件是否存在于硬盘
					Method:  http.MethodPost,
					Path:    "/raw-documents/check-file-exists",
					Handler: knowdata.CheckRawDocumentsFileExistsHandler(serverCtx),
				},
				{
					// 获取原始文档的原始内容和当前内容用于比较
					Method:  http.MethodPost,
					Path:    "/raw-documents/content/diff",
					Handler: knowdata.GetRawDocumentsContentDiffHandler(serverCtx),
				},
				{
					// 更新原始文档内容
					Method:  http.MethodPost,
					Path:    "/raw-documents/content/update",
					Handler: knowdata.UpdateRawDocumentsContentHandler(serverCtx),
				},
				{
					// 删除原始文档
					Method:  http.MethodPost,
					Path:    "/raw-documents/delete",
					Handler: knowdata.DeleteRawDocumentsHandler(serverCtx),
				},
				{
					// 下载原始文档源文件
					Method:  http.MethodGet,
					Path:    "/raw-documents/download/:id",
					Handler: knowdata.DownloadRawDocumentsHandler(serverCtx),
				},
				{
					// 获取原始文档
					Method:  http.MethodPost,
					Path:    "/raw-documents/get",
					Handler: knowdata.GetRawDocumentsHandler(serverCtx),
				},
				{
					// 根据文件名获取原始文档（返回 Markdown 内容）
					Method:  http.MethodPost,
					Path:    "/raw-documents/get-by-filename",
					Handler: knowdata.GetRawDocumentsByFilenameHandler(serverCtx),
				},
				{
					// 将原始文档分块并向量化写入 Qdrant
					Method:  http.MethodPost,
					Path:    "/raw-documents/index-to-qdrant",
					Handler: knowdata.IndexRawDocumentToQdrantHandler(serverCtx),
				},
				{
					// 获取原始文档列表
					Method:  http.MethodPost,
					Path:    "/raw-documents/list",
					Handler: knowdata.ListRawDocumentsHandler(serverCtx),
				},
				{
					// 查看审核入库时抽取的问答队列
					Method:  http.MethodPost,
					Path:    "/raw-documents/qa/list",
					Handler: knowdata.ListRawDocumentQaPairsHandler(serverCtx),
				},
				{
					// 查看已审核文档在 Qdrant 中的分块（主分块集合 + 全文概要集合，按 metadata.file_name 过滤）
					Method:  http.MethodPost,
					Path:    "/raw-documents/qdrant/chunks",
					Handler: knowdata.GetRawDocumentQdrantChunksHandler(serverCtx),
				},
				{
					// 全文检索原始文档
					Method:  http.MethodPost,
					Path:    "/raw-documents/search",
					Handler: knowdata.SearchRawDocumentsHandler(serverCtx),
				},
				{
					// 更改原始文档标签
					Method:  http.MethodPost,
					Path:    "/raw-documents/tag/change",
					Handler: knowdata.ChangeRawDocumentsTagHandler(serverCtx),
				},
				{
					// 获取所有不重复的Tag标签
					Method:  http.MethodPost,
					Path:    "/raw-documents/tags/distinct",
					Handler: knowdata.GetDistinctTagsHandler(serverCtx),
				},
				{
					// 上传原始文档，如果zip,自动解压
					Method:  http.MethodPost,
					Path:    "/raw-documents/upload",
					Handler: knowdata.UploadRawDocumentsHandler(serverCtx),
				},
				{
					// 原始文档向量检索（可选 vLLM 重排）
					Method:  http.MethodPost,
					Path:    "/raw-documents/vectors/search",
					Handler: knowdata.SearchRawDocVectorsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
		rest.WithTimeout(90000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// LLM 规范化 Markdown 预览：返回原文与格式化结果，确认后请调用 content/update 保存
					Method:  http.MethodPost,
					Path:    "/raw-documents/content/markdown-normalize/preview",
					Handler: knowdata.RawDocumentsMarkdownNormalizePreviewHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
		rest.WithTimeout(600000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 调用 LLM 进行单轮对话
				Method:  http.MethodPost,
				Path:    "/ai/llm/oneshot",
				Handler: knowdata.CallLLMOneShotHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(90000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 重新生成所有已审核文档的概要
					Method:  http.MethodPost,
					Path:    "/raw-documents/regenerate-summaries",
					Handler: knowdata.RegenerateAllSummariesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
		rest.WithTimeout(3600000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建AI配置
					Method:  http.MethodPost,
					Path:    "/conf/ai",
					Handler: knowdata.CreateAIConfigHandler(serverCtx),
				},
				{
					// 获取AI配置
					Method:  http.MethodGet,
					Path:    "/conf/ai/:id",
					Handler: knowdata.GetAIConfigHandler(serverCtx),
				},
				{
					// 更新AI配置
					Method:  http.MethodPost,
					Path:    "/conf/ai/:id",
					Handler: knowdata.UpdateAIConfigHandler(serverCtx),
				},
				{
					// 删除AI配置
					Method:  http.MethodDelete,
					Path:    "/conf/ai/:id",
					Handler: knowdata.DeleteAIConfigHandler(serverCtx),
				},
				{
					// 获取AI配置列表
					Method:  http.MethodGet,
					Path:    "/conf/ai/list",
					Handler: knowdata.GetAIConfigListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
		rest.WithTimeout(90000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 系统版本信息
				Method:  http.MethodGet,
				Path:    "/sys/version",
				Handler: knowdata.SysVersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(90000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取AI配置byname和documentCode
				Method:  http.MethodPost,
				Path:    "/conf/ai/code/name/get",
				Handler: knowdata.GetAIConfigByNameCodeHandler(serverCtx),
			},
			{
				// 获取AI配置
				Method:  http.MethodGet,
				Path:    "/conf/ai/name/:name",
				Handler: knowdata.GetAIConfigByNameHandler(serverCtx),
			},
			{
				// 系统状态检查
				Method:  http.MethodGet,
				Path:    "/sys/ping",
				Handler: knowdata.SysPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(90000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 公开博客详情（通过 alias 或 id，无需登录）
				Method:  http.MethodGet,
				Path:    "/blog/:slug",
				Handler: knowsource.BlogReadHandler(serverCtx),
			},
			{
				// 公开博客列表（无需登录）
				Method:  http.MethodPost,
				Path:    "/blog/list",
				Handler: knowsource.BlogListPublicHandler(serverCtx),
			},
			{
				// 员工登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: knowsource.KnowsourceLoginHandler(serverCtx),
			},
			{
				// 标注文档已转化
				Method:  http.MethodPost,
				Path:    "/mark/document/converted",
				Handler: knowsource.MarkDocumentConvertedHandler(serverCtx),
			},
			{
				// 标注文档已转化
				Method:  http.MethodPost,
				Path:    "/mark/document/raged",
				Handler: knowsource.MarkDocumentRagedHandler(serverCtx),
			},
			{
				// 员工登录
				Method:  http.MethodPost,
				Path:    "/oa/login",
				Handler: knowsource.KnowsourceOALoginHandler(serverCtx),
			},
			{
				// 忘记密码：验证码重置
				Method:  http.MethodPost,
				Path:    "/password/reset/confirm",
				Handler: knowsource.KnowsourcePasswordResetConfirmHandler(serverCtx),
			},
			{
				// 忘记密码：发送验证码（邮箱或手机）
				Method:  http.MethodPost,
				Path:    "/password/reset/send-code",
				Handler: knowsource.KnowsourcePasswordResetSendCodeHandler(serverCtx),
			},
			{
				// 租户自助注册（创建 client + superadmin，发邮箱验证码）
				Method:  http.MethodPost,
				Path:    "/tenant/register",
				Handler: knowsource.KnowsourceTenantRegisterHandler(serverCtx),
			},
			{
				// 租户发送邮箱验证码
				Method:  http.MethodPost,
				Path:    "/tenant/send-verification-code",
				Handler: knowsource.KnowsourceTenantSendVerificationCodeHandler(serverCtx),
			},
			{
				// 租户邮箱验证通过
				Method:  http.MethodPost,
				Path:    "/tenant/verify-email",
				Handler: knowsource.KnowsourceTenantVerifyEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/knowsource"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// cancel async task for current tenant
					Method:  http.MethodPost,
					Path:    "/async-task/cancel",
					Handler: knowsource.CancelAsyncTaskHandler(serverCtx),
				},
				{
					// delete async task for current tenant
					Method:  http.MethodPost,
					Path:    "/async-task/delete",
					Handler: knowsource.DeleteAsyncTaskHandler(serverCtx),
				},
				{
					// list async tasks for current tenant
					Method:  http.MethodPost,
					Path:    "/async-task/list",
					Handler: knowsource.ListAsyncTaskHandler(serverCtx),
				},
				{
					// async_task 变更水印（按租户 Redis），前端轮询与本地比较，有变化再拉列表
					Method:  http.MethodPost,
					Path:    "/async-task/watermark",
					Handler: knowsource.GetAsyncTaskWatermarkHandler(serverCtx),
				},
				{
					// cancel convert task
					Method:  http.MethodPost,
					Path:    "/document/convert/cancel",
					Handler: knowsource.CancelConvertDocumentHandler(serverCtx),
				},
				{
					// convert document to markdown
					Method:  http.MethodPost,
					Path:    "/document/convert/to/md",
					Handler: knowsource.ConvertDocumentToMDHandler(serverCtx),
				},
				{
					// convert document to zip
					Method:  http.MethodPost,
					Path:    "/document/convert/to/zip",
					Handler: knowsource.ConvertDocumentToZIPHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/knowsource"),
		rest.WithTimeout(120000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// admin 移动文件到其他文档类型
					Method:  http.MethodPost,
					Path:    "/admin/change/file/document-type",
					Handler: knowsource.AdminChangeFileDocumentTypeHandler(serverCtx),
				},
				{
					// admin 创建 client
					Method:  http.MethodPost,
					Path:    "/admin/client/create",
					Handler: knowsource.AdminClientCreateHandler(serverCtx),
				},
				{
					// admin 删除 client
					Method:  http.MethodPost,
					Path:    "/admin/client/delete",
					Handler: knowsource.AdminClientDeleteHandler(serverCtx),
				},
				{
					// 管理员：获取Client列表
					Method:  http.MethodPost,
					Path:    "/admin/client/list",
					Handler: knowsource.AdminClientListHandler(serverCtx),
				},
				{
					// admin 重置密码
					Method:  http.MethodPost,
					Path:    "/admin/reset/password",
					Handler: knowsource.AdminResetPasswordHandler(serverCtx),
				},
				{
					// admin 重置密码
					Method:  http.MethodPost,
					Path:    "/admin/set/role",
					Handler: knowsource.AdminSetRoleHandler(serverCtx),
				},
				{
					// AI 调用统计：按时间范围查询，返回总次数、人数、模型数量
					Method:  http.MethodPost,
					Path:    "/ai/call/stats/query",
					Handler: knowsource.AiCallStatsQueryHandler(serverCtx),
				},
				{
					// 博客管理创建（仅 admin 租户 superadmin）
					Method:  http.MethodPost,
					Path:    "/blog/admin/create",
					Handler: knowsource.BlogAdminCreateHandler(serverCtx),
				},
				{
					// 博客管理删除（仅 admin 租户 superadmin）
					Method:  http.MethodPost,
					Path:    "/blog/admin/delete",
					Handler: knowsource.BlogAdminDeleteHandler(serverCtx),
				},
				{
					// 博客管理详情（仅 admin 租户 superadmin）
					Method:  http.MethodPost,
					Path:    "/blog/admin/get",
					Handler: knowsource.BlogAdminGetHandler(serverCtx),
				},
				{
					// 博客管理列表（仅 admin 租户 superadmin）
					Method:  http.MethodPost,
					Path:    "/blog/admin/list",
					Handler: knowsource.BlogAdminListHandler(serverCtx),
				},
				{
					// 博客管理更新（仅 admin 租户 superadmin）
					Method:  http.MethodPost,
					Path:    "/blog/admin/update",
					Handler: knowsource.BlogAdminUpdateHandler(serverCtx),
				},
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/change-password",
					Handler: knowsource.KnowsourceChangePasswordHandler(serverCtx),
				},
				{
					// 创建部门文档类型绑定
					Method:  http.MethodPost,
					Path:    "/dept-document-type/create",
					Handler: knowsource.CreateDeptDocumentTypeHandler(serverCtx),
				},
				{
					// 删除部门文档类型绑定
					Method:  http.MethodPost,
					Path:    "/dept-document-type/delete",
					Handler: knowsource.DeleteDeptDocumentTypeHandler(serverCtx),
				},
				{
					// 获取部门文档类型绑定列表
					Method:  http.MethodPost,
					Path:    "/dept-document-type/list",
					Handler: knowsource.ListDeptDocumentTypeHandler(serverCtx),
				},
				{
					// 新增部门
					Method:  http.MethodPost,
					Path:    "/dept/create",
					Handler: knowsource.CreateDeptHandler(serverCtx),
				},
				{
					// 删除部门
					Method:  http.MethodPost,
					Path:    "/dept/delete",
					Handler: knowsource.DeleteDeptHandler(serverCtx),
				},
				{
					// 获取部门列表
					Method:  http.MethodPost,
					Path:    "/dept/list",
					Handler: knowsource.ListDeptHandler(serverCtx),
				},
				{
					// 移动部门（拖拽）
					Method:  http.MethodPost,
					Path:    "/dept/move",
					Handler: knowsource.MoveDeptHandler(serverCtx),
				},
				{
					// 获取部门树
					Method:  http.MethodPost,
					Path:    "/dept/tree",
					Handler: knowsource.GetDeptTreeHandler(serverCtx),
				},
				{
					// 修改部门
					Method:  http.MethodPost,
					Path:    "/dept/update",
					Handler: knowsource.UpdateDeptHandler(serverCtx),
				},
				{
					// get dify option
					Method:  http.MethodPost,
					Path:    "/dify/option/create",
					Handler: knowsource.CreateDifyOptionHandler(serverCtx),
				},
				{
					// Delete dify option
					Method:  http.MethodPost,
					Path:    "/dify/option/delete",
					Handler: knowsource.DeleteDifyOptionHandler(serverCtx),
				},
				{
					// get dify option
					Method:  http.MethodPost,
					Path:    "/dify/option/get",
					Handler: knowsource.GetDifyOptionHandler(serverCtx),
				},
				{
					// List dify option
					Method:  http.MethodPost,
					Path:    "/dify/option/list",
					Handler: knowsource.ListDifyOptionHandler(serverCtx),
				},
				{
					// update dify option
					Method:  http.MethodPost,
					Path:    "/dify/option/update",
					Handler: knowsource.UpdateDifyOptionHandler(serverCtx),
				},
				{
					// 获取文档路径文件树
					Method:  http.MethodPost,
					Path:    "/doc-path/tree",
					Handler: knowsource.GetDocPathTreeHandler(serverCtx),
				},
				{
					// 创建员工知识库权限
					Method:  http.MethodPost,
					Path:    "/emp-document-type/create",
					Handler: knowsource.CreateEmpDocumentTypeHandler(serverCtx),
				},
				{
					// 删除员工知识库权限
					Method:  http.MethodPost,
					Path:    "/emp-document-type/delete",
					Handler: knowsource.DeleteEmpDocumentTypeHandler(serverCtx),
				},
				{
					// 获取员工知识库权限列表
					Method:  http.MethodPost,
					Path:    "/emp-document-type/list",
					Handler: knowsource.ListEmpDocumentTypeHandler(serverCtx),
				},
				{
					// 获取员工知识库权限列表group
					Method:  http.MethodPost,
					Path:    "/emp-document-type/list/group",
					Handler: knowsource.ListEmpDocumentTypeListGroupListHandler(serverCtx),
				},
				{
					// 新增员工
					Method:  http.MethodPost,
					Path:    "/emp/create",
					Handler: knowsource.CreateEmpHandler(serverCtx),
				},
				{
					// 删除员工
					Method:  http.MethodPost,
					Path:    "/emp/delete",
					Handler: knowsource.DeleteEmpHandler(serverCtx),
				},
				{
					// 获取员工列表
					Method:  http.MethodPost,
					Path:    "/emp/list",
					Handler: knowsource.ListEmpHandler(serverCtx),
				},
				{
					// 修改员工
					Method:  http.MethodPost,
					Path:    "/emp/update",
					Handler: knowsource.UpdateEmpHandler(serverCtx),
				},
				{
					// import hr user dept
					Method:  http.MethodPost,
					Path:    "/hr/import/user/dept",
					Handler: knowsource.ImportHrUserDeptHandler(serverCtx),
				},
				{
					// 获取对话模型列表（与监控检查中 Chat 使用同一接口 /v1/models 或 Ollama /api/tags），排除名称含 embedding 的模型
					Method:  http.MethodPost,
					Path:    "/llm/chat/models",
					Handler: knowsource.GetLLMChatModelsHandler(serverCtx),
				},
				{
					// 获取 Embedding 模型列表（从 Rag.EmbeddingsUrl 拉取），仅返回名称含 embedding 的模型
					Method:  http.MethodPost,
					Path:    "/llm/embedding/models",
					Handler: knowsource.GetLLMEmbeddingModelsHandler(serverCtx),
				},
				{
					// 测试 Embedding 与 Rerank 实际调用（租户覆盖配置）
					Method:  http.MethodPost,
					Path:    "/llm/service/test",
					Handler: knowsource.TestLLMServicesHandler(serverCtx),
				},
				{
					// 获取 LLM 设置系统默认值（来自 knowsource.yaml，供界面重置，不写入租户配置）
					Method:  http.MethodPost,
					Path:    "/llm/setting/defaults",
					Handler: knowsource.LoadLLMSettingDefaultsHandler(serverCtx),
				},
				{
					// 获取设置
					Method:  http.MethodPost,
					Path:    "/llm/setting/load",
					Handler: knowsource.LoadLLMSettingHandler(serverCtx),
				},
				{
					// 更新设置
					Method:  http.MethodPost,
					Path:    "/llm/setting/save",
					Handler: knowsource.SaveLLMSettingHandler(serverCtx),
				},
				{
					// 获取我的文档类型
					Method:  http.MethodPost,
					Path:    "/my-document-type/list",
					Handler: knowsource.ListMyDocumentTypeHandler(serverCtx),
				},
				{
					// 创建权限
					Method:  http.MethodPost,
					Path:    "/permission/create",
					Handler: knowsource.CreateFrPermissionHandler(serverCtx),
				},
				{
					// 删除权限
					Method:  http.MethodPost,
					Path:    "/permission/delete",
					Handler: knowsource.DeleteFrPermissionHandler(serverCtx),
				},
				{
					// 获取权限
					Method:  http.MethodPost,
					Path:    "/permission/get",
					Handler: knowsource.GetFrPermissionHandler(serverCtx),
				},
				{
					// 获取权限列表
					Method:  http.MethodPost,
					Path:    "/permission/list",
					Handler: knowsource.ListFrPermissionHandler(serverCtx),
				},
				{
					// 更新权限
					Method:  http.MethodPost,
					Path:    "/permission/update",
					Handler: knowsource.UpdateFrPermissionHandler(serverCtx),
				},
				{
					// 绑定手机/邮箱：提交验证码
					Method:  http.MethodPost,
					Path:    "/profile/contact/bind/confirm",
					Handler: knowsource.KnowsourceContactBindConfirmHandler(serverCtx),
				},
				{
					// 绑定手机/邮箱：发送验证码
					Method:  http.MethodPost,
					Path:    "/profile/contact/bind/send",
					Handler: knowsource.KnowsourceContactBindSendHandler(serverCtx),
				},
				{
					// 获取 qrdant collection list
					Method:  http.MethodPost,
					Path:    "/qdrant/collection/file/list",
					Handler: knowsource.GetQdrantCollectionFileListHandler(serverCtx),
				},
				{
					// 获取 qrdant collection list
					Method:  http.MethodPost,
					Path:    "/qdrant/collection/list",
					Handler: knowsource.GetQdrantCollectionListHandler(serverCtx),
				},
				{
					// 刷新token
					Method:  http.MethodPost,
					Path:    "/refresh/token",
					Handler: knowsource.RefreshTokenHandler(serverCtx),
				},
				{
					// 创建角色权限关联
					Method:  http.MethodPost,
					Path:    "/role-permission/create",
					Handler: knowsource.CreateFrRolePermissionHandler(serverCtx),
				},
				{
					// 删除角色权限关联
					Method:  http.MethodPost,
					Path:    "/role-permission/delete",
					Handler: knowsource.DeleteFrRolePermissionHandler(serverCtx),
				},
				{
					// 获取角色权限关联
					Method:  http.MethodPost,
					Path:    "/role-permission/get",
					Handler: knowsource.GetFrRolePermissionHandler(serverCtx),
				},
				{
					// 获取角色权限关联列表
					Method:  http.MethodPost,
					Path:    "/role-permission/list",
					Handler: knowsource.ListFrRolePermissionHandler(serverCtx),
				},
				{
					// 更新角色权限关联
					Method:  http.MethodPost,
					Path:    "/role-permission/update",
					Handler: knowsource.UpdateFrRolePermissionHandler(serverCtx),
				},
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/role/create",
					Handler: knowsource.CreateFrRoleHandler(serverCtx),
				},
				{
					// 删除角色
					Method:  http.MethodPost,
					Path:    "/role/delete",
					Handler: knowsource.DeleteFrRoleHandler(serverCtx),
				},
				{
					// 获取角色
					Method:  http.MethodPost,
					Path:    "/role/get",
					Handler: knowsource.GetFrRoleHandler(serverCtx),
				},
				{
					// 获取角色列表
					Method:  http.MethodPost,
					Path:    "/role/list",
					Handler: knowsource.ListFrRoleHandler(serverCtx),
				},
				{
					// 更新角色
					Method:  http.MethodPost,
					Path:    "/role/update",
					Handler: knowsource.UpdateFrRoleHandler(serverCtx),
				},
				{
					// sync mysql
					Method:  http.MethodPost,
					Path:    "/sync/mysql",
					Handler: knowsource.SyncMysqlHandler(serverCtx),
				},
				{
					// 系统依赖检查：Vllmchat、Vllmembedding、Vllmreranker、Qdrant、Redis、Mysql
					Method:  http.MethodPost,
					Path:    "/sys/check",
					Handler: knowsource.SysCheckHandler(serverCtx),
				},
				{
					// 系统统计：返回员工总数、部门总数、知识库总数、AI 会话数
					Method:  http.MethodPost,
					Path:    "/system/stats",
					Handler: knowsource.GetSystemStatsHandler(serverCtx),
				},
				{
					// 创建标签
					Method:  http.MethodPost,
					Path:    "/tag/create",
					Handler: knowsource.CreateFrTagHandler(serverCtx),
				},
				{
					// 删除标签
					Method:  http.MethodPost,
					Path:    "/tag/delete",
					Handler: knowsource.DeleteFrTagHandler(serverCtx),
				},
				{
					// 获取标签
					Method:  http.MethodPost,
					Path:    "/tag/get",
					Handler: knowsource.GetFrTagHandler(serverCtx),
				},
				{
					// 获取标签列表
					Method:  http.MethodPost,
					Path:    "/tag/list",
					Handler: knowsource.ListFrTagHandler(serverCtx),
				},
				{
					// 更新标签
					Method:  http.MethodPost,
					Path:    "/tag/update",
					Handler: knowsource.UpdateFrTagHandler(serverCtx),
				},
				{
					// 创建用户角色关联
					Method:  http.MethodPost,
					Path:    "/user-role/create",
					Handler: knowsource.CreateFrUserRoleHandler(serverCtx),
				},
				{
					// 删除用户角色关联
					Method:  http.MethodPost,
					Path:    "/user-role/delete",
					Handler: knowsource.DeleteFrUserRoleHandler(serverCtx),
				},
				{
					// 获取用户角色关联
					Method:  http.MethodPost,
					Path:    "/user-role/get",
					Handler: knowsource.GetFrUserRoleHandler(serverCtx),
				},
				{
					// 获取用户角色关联列表
					Method:  http.MethodPost,
					Path:    "/user-role/list",
					Handler: knowsource.ListFrUserRoleHandler(serverCtx),
				},
				{
					// 更新用户角色关联
					Method:  http.MethodPost,
					Path:    "/user-role/update",
					Handler: knowsource.UpdateFrUserRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/knowsource"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 执行 mysqldump 并打包为 zip（仅 admin 租户且 superadmin 角色）
					Method:  http.MethodPost,
					Path:    "/mysql/backup",
					Handler: mysql.MysqlBackupHandler(serverCtx),
				},
				{
					// 下载备份 zip（仅 admin 租户且 superadmin 角色）
					Method:  http.MethodGet,
					Path:    "/mysql/download/backup/:file",
					Handler: mysql.MysqlBackupDownloadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(600000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get home page
				Method:  http.MethodGet,
				Path:    "/",
				Handler: page.GetHomeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get Privacy policy
				Method:  http.MethodGet,
				Path:    "/doc/pp",
				Handler: page.GetPPHandler(serverCtx),
			},
			{
				// Get swagger json
				Method:  http.MethodGet,
				Path:    "/doc/swagger",
				Handler: page.GetSwaggerHandler(serverCtx),
			},
			{
				// Get TOC
				Method:  http.MethodGet,
				Path:    "/doc/toc",
				Handler: page.GetTocHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(15000*time.Millisecond),
	)
}
